### ISSUE TITLE
[Crash / 0.4.0a] Startup crash.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#1]
[debug.log](https://github.com/Asek3/Rubidium/files/7971085/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/7971088/latest.log)

**Comment by Asek3** [comment]
Seems to be mod incompatibility. Can you try to run Rubidium on clean Forge?

**Comment by KKotik** [comment]
Tested it on clean forge, booting fine, but mod menu appears black when clicking on any installed mod. 
![image](https://user-images.githubusercontent.com/45950781/151808273-3fd1205a-a6e1-4d6b-a1f8-f4bbbf6ba5e6.png)

**Comment by KKotik** [comment]
Anything else that I could help?

**Comment by KKotik** [comment]
Tracked down the issues, turns out to be more than just one, will open new more information provided and related to each one of them.
