### ISSUE TITLE
[1.16.5] Support for Better Fps - Render Distance?

### ISSUE THREAD

**Issue by Vran-n** [Asek3/Rubidium#100]
Hello, I was wondering if you can support Better Fps - Render Distance for 1.16.5 as it doesn't reduce the render distance when this mod is installed. I asked the owner of the mod and they said it won't be supporting it since it breaks it.

**Comment by Asek3** [comment]
use https://www.curseforge.com/minecraft/mc-mods/magnesium-extras

**Comment by Vran-n** [comment]
Oh, thanks for the suggestion. It doesn't have the vertical render distance for the blocks though, only for the entities and stuff.
