### ISSUE TITLE
[1.18.2] Bad Performance (worse than optifine)

### ISSUE THREAD

**Issue by Tohricat** [Asek3/Rubidium#105]
When using Rubidium and Oculus on default settings, I get really bad performance. Low FPS and significant lag/slowdowns when loading chunks. Shaders make the game unplayable. I can use Optifine and Shaders and get over 200FPS.  Another user has reported the same issue in the CurseForge project comments.

My specs are 16gb of Ram, an RTX 3070 laptop GPU and an I7-10870H.

Thanks!

**Comment by Asek3** [comment]
Not issue. We can only wait for Sodium 0.5.0 release to port it for Rubidium
