### ISSUE TITLE
1.16.5 latest update. Potential compatibility issue with BetterFps Render distance?

### ISSUE THREAD

**Issue by DigitalWendigo** [Asek3/Rubidium#107]
I'm having a weird log warning that mentions mixins and betterfps. 
I didn't seem to have this issue with optifine, but since I went over to rubidium, this error pops up in the log files. 
Now I'm not sure it's even a rubidium issue, it could be something else, but the fact this happened after the change is odd and I'd like to know what you think of it. 
Can I just ignore this? 

28Apr2022 19:15:44.076] [modloading-worker-0/WARN] [mixin/]: Mixin apply failed betterfpsdist.mixins.json:LevelRendererMixin ->

The above is only a small part of the line so in case you've already seen this elsewhere, you won't have to open the log file and scroll through it to find the error. 
The actual log file is listed below. 
[latest.log](https://github.com/Asek3/Rubidium/files/8584684/latest.log)

**Comment by Asek3** [comment]
stop asking me about this shitty mod plz and use https://www.curseforge.com/minecraft/mc-mods/magnesium-extras
