### ISSUE TITLE
Client crashes when placing Wind Generator from Mekanism Generators mod

### ISSUE THREAD

**Issue by ArnoldVanN** [Asek3/Rubidium#109]
While playing on the better minecraft modpack with Mekanism and Mekanism generators installed, after placing down a Wind Generator, my and my friend's clients crash. 
I'm using Rubidium 0.5.2a and forge 40.0.54
This is the crash log https://pastebin.com/GWAy8FUQ

**Comment by ArnoldVanN** [comment]
Weirdly enough, after removing the mod from the mods folder, restarting client, then closing it again after realizing nothing renders without Rubidium, to finally add the mod back to the mods folder and once again restarting the client, the issue fixed itself. I'll leave this here in case anyone ever encounters the same problem

**Comment by ArnoldVanN** [comment]
Closed because the issue is most likely caused by placing the wind generator in a chunk that was first rendered before the Mekanism mods were added. Placing the generator in other areas works.

**Comment by WFPhantom** [comment]
Im not sure thats the issue, i got a random crash when placing a wind generator yesterday but I ignored it, I've had mekanism since the beginning of the world

**Comment by Kowantify** [comment]
I am currently having this exact same issue, is there any update?
