### ISSUE TITLE
Fabulous Graphics Issues

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Rubidium#11]
![2022-01-31_22 28 11](https://user-images.githubusercontent.com/8345523/151883812-e5df3c3c-bfbe-442c-a452-c8317080fb8c.png)

Current modlist:

- AmbientSounds
- Architect's Palette
- Architectury API
- Balm
- Ksyxis
- KubeJS
- KubeJS Create
- Placebo
- WorldEdit
- AI Improvements
- Alex's Mobs
- Artifacts
- Better Biome Blend
- Caelus API
- Carry On
- Cave Tweaks
- Chipped
- Citadel
- Cleancut
- Clumps
- Configured
- Create
- Croptopia
- Curios of Undying
- Curios API
- Curious Elytra
- Curious Shulker Boxes
- Decorative Blocks
- Dramatic Doors
- Enhanced Mob Spawners
- Enhanced Visuals
- Entity Culling
- ExpandAbility
- Farmer's Delight
- Farsight
- FeatureNBT Deadlock Be Gone
- FerriteCore
- Flywheel
- FPS Reduced
- Get It Together, Drops!
- Jade
- JEI
- Krypton Reforged
- Lazy DFU
- Loot Beams
- No Null Processors
- Patina Pipeworks
- Public GUI Announcement
- Radium Reforged
- Regrowth
- Repurposed Structures
- Rhino
- Rubidium
- Selene Lib
- Serene Seasons
- Skin Layers 3D
- Spice of Life
- Starlight
- Supplementaries
- Terralith
- Tool Belt
- Torch Slabs Mod
- Valhesia Core
- Valheslsia Structures
- Waystones
- YUNG's API
-

**Comment by Atlantispy** [comment]
![2022-01-31_22 46 39](https://user-images.githubusercontent.com/8345523/151885783-36fe0024-d590-4938-8f2b-a5c3c1c9a0d2.png)
Tinted glass appears to be invisible right now as well, including stained glass

**Comment by Asek3** [comment]
Seems to be Flywheel's offed backend problem

**Comment by Atlantispy** [comment]
Having played around with the settings, it is fixed when selecting fast or fancy, rather than fabulous

**Comment by KKotik** [comment]
Do not use fabulous graphics at all, they are broken even without sodium. Please close the issue and rename it to Fabulous Graphic issues, so people will have find the same and do not open another one.
