### ISSUE TITLE
[1.18.2] Rubidium isn't set up as a Client side only mod

### ISSUE THREAD

**Issue by WFPhantom** [Asek3/Rubidium#110]
[18:14:46] [Netty Client IO #0/INFO]: Client has mods that are missing on server: [rubidium, shutupexperimentalsettings]

**Comment by MattB70** [comment]
I believe Forge and Fabric have the same or very similar handlers for starting as either client or server and specifying which. This should get fixed easily. For now, no multiplayer though.

Reference for siding: https://mcforge.readthedocs.io/en/latest/concepts/sides/

**Comment by WFPhantom** [comment]
I believe this has been fixed with the latest update for 1.18.2
