### ISSUE TITLE
[1.18.2] Rubidium causing a hang on loading

### ISSUE THREAD

**Issue by 100chilly** [Asek3/Rubidium#112]
Hi, I'm using a custom modpack for 1.18.2 and no matter what I try Rubidium causes the client to hang and not continue to load.

Modlist: [Here](https://files.100chilly.website/Minecraft/modlist.html)
Logs: https://gist.github.com/100chilly/3722582542995f21c7f0813115f70c33

Hope this helps and it can be resolved.
Also tried disabling Better Loading Screens for #90 and no luck.

**Comment by Asek3** [comment]
Should be fixed, update mod and reopen issue if not plz.
