### ISSUE TITLE
[1.18.2] Server crash on startup

### ISSUE THREAD

**Issue by AppleMangoOrange** [Asek3/Rubidium#113]
I have a forge server with only rubidium installed. When starting up, it crashes with the message `[03May2022 09:32:39.927] [main/ERROR] [mixin/]: Mixin config rubidium.mixins.json does not specify "minVersion" property`

**Comment by Asek3** [comment]
dude

**Comment by AppleMangoOrange** [comment]
Can someone please let me know what is causing the problem here

**Comment by littlepianist** [comment]
> Can someone please let me know what is causing the problem here

this mod is a client side mod, not for servers
