### ISSUE TITLE
[1.16.5] Invisible/transparent vanilla chests

### ISSUE THREAD

**Issue by niXtou** [Asek3/Rubidium#116]
MC: 1.16.5 [Modpack: FTB University]
Forge: 36.2.19
Rubidium: 0.2.6
Oculus: 1.2.3-pre

The game doesn't render vanilla chests but the chests are working correctly. I think that's something related to this version of Rubidium, since I have tried without Oculus and it still happens. I have even tried various combinations of Rubidium settings with no luck.

![image](https://user-images.githubusercontent.com/45014927/166873582-fb402b61-28fe-490c-83fb-0ee350b19043.png)

**Comment by Asek3** [comment]
As I know FTB University has Flywheel, so probably fixed in latest versions
