### ISSUE TITLE
[Startup Crash] Mod Incompatibility with Dynamic Music mod.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#12]
https://www.curseforge.com/minecraft/mc-mods/dynamic-music?__cf_chl_jschl_tk__=TeYtPjKOm4cK.oPvVk8vhblhyTjnuZVrcXoUIqyYgdo-1643708167-0-gaNycGzNDn0

[debug.log](https://github.com/Asek3/Rubidium/files/7977311/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/7977313/latest.log)

rubidium-0.4.0c

**Comment by Asek3** [comment]
Crash is not related to Rubidium.

**Comment by KKotik** [comment]
Yeah just found out that this is Dynamic Music issue only, https://github.com/LudoCrypt/Dynamic-Music/issues/8
