### ISSUE TITLE
Incompatibility with Ecologics [1.18.2]

### ISSUE THREAD

**Issue by alexstanleeee** [Asek3/Rubidium#121]
With Rubidium and Ecologics both installed, there is a bizarre graphical glitch displaying chunk borders through the 'thin ice' block. This is an issue which I and others have reported to the creators of Ecolgics, who claim that the issue is to do with Rubidium as the transparency settings are indeed correct.
![image](https://user-images.githubusercontent.com/104217120/167262749-0ed60995-8929-453e-b047-74f4d49f06b9.png)
![image](https://user-images.githubusercontent.com/104217120/167262755-e968f5de-d6ae-4728-9bcd-a8698ce13091.png)

**Comment by Asek3** [comment]
That is Sodium's behaviour by itself, related to Translucency Sorting
