### ISSUE TITLE
[1.18.2]client crash when placing a mekanism wind generator next to a advanced solar panel

### ISSUE THREAD

**Issue by SDUBZ** [Asek3/Rubidium#123]
forge: 40.1.19
rub: rubidium-0.5.2a
logs:
[debug.log](https://github.com/Asek3/Rubidium/files/8663973/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/8663974/latest.log)

crash report:
[crash-2022-05-11_04.00.50-client.txt](https://github.com/Asek3/Rubidium/files/8663968/crash-2022-05-11_04.00.50-client.txt)

**Comment by Asek3** [comment]
Update Rubidium
