### ISSUE TITLE
[1.18.1] Immersive Engineering Rendering Issues

### ISSUE THREAD

**Issue by mszabolcs-dev** [Asek3/Rubidium#124]
### Forge Version:
39.1.0

### Modlist:
ImmersiveEngineering-1.18.1-7.1.0-145.jar
rubidium-0.5.0.jar

### Issues:

- I had the same rendering issues that are in #54 

**Except:**
- Razor wire are ok
- Cables are visible

### Pictures:

- These on the side are the extensions of the pole. The block ID is the same, but the horizontal offset is different.
![2022-05-11_20 10 09](https://user-images.githubusercontent.com/11245344/167917542-db85fc51-4303-492a-9610-642f5b75b93e.png)

- It should look like this
![image](https://user-images.githubusercontent.com/11245344/167912266-73f88287-3da2-409d-89a7-c32c77392400.png)

**Comment by Lordfirespeed** [comment]
Issue is still occuring in 1.18.2, 
IE version 1.18.2-8.0.1-147
Forge version 40.1.31
Using a minimal installation (Forge, Immersive Engineering, JEI, Rubidium)

**Comment by Asek3** [comment]
Should be resolved on the latest versions.
