### ISSUE TITLE
[1.18.2] Rubidium turns Tinker's Chest grayscale

### ISSUE THREAD

**Issue by aethaerya** [Asek3/Rubidium#126]
It is a sad day indeed.
![image](https://user-images.githubusercontent.com/28931355/168477994-d570038f-97ed-4377-9339-1339b3a4ec60.png)

It should look like this:

![image](https://user-images.githubusercontent.com/28931355/168478141-6a22700c-b732-4090-a356-3e136a941d74.png)

Reproduce with:
Rubidium 0.5.2a
Tinkers' Construct 3.5.0.17
Mantle 1.9.20

**Comment by HazardEST** [comment]
also happens on 1.16.5
