### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 8193

### ISSUE THREAD

**Issue by Benjamboo** [Asek3/Rubidium#129]
The following crash continuously occurs when playing on a modded server with friends (mod is client-side only).  Once every few hours for each player.

[crash-2022-05-18_15.55.30-client.txt](https://github.com/Asek3/Rubidium/files/8714468/crash-2022-05-18_15.55.30-client.txt)

**Comment by TheFantasticLoki** [comment]
Does the server you play on have a custom world height in any of the dimensions?

**Comment by Benjamboo** [comment]
No, no custom world height settings were changed.

**Comment by AzuCacti** [comment]
going to include several crashreports here and there, same/similar errors -1

None of the worlds using custom world heights.

[crash-2022-06-05_04.25.00-client.txt](https://github.com/Asek3/Rubidium/files/8838452/crash-2022-06-05_04.25.00-client.txt)
[crash-2022-06-04_00.38.11-client.txt](https://github.com/Asek3/Rubidium/files/8838449/crash-2022-06-04_00.38.11-client.txt)
[crash-2022-06-05_03.29.17-client.txt](https://github.com/Asek3/Rubidium/files/8838450/crash-2022-06-05_03.29.17-client.txt)
[crash-2022-06-05_04.20.57-client.txt](https://github.com/Asek3/Rubidium/files/8838451/crash-2022-06-05_04.20.57-client.txt)
[crash-2022-06-04_00.35.38-client.txt](https://github.com/Asek3/Rubidium/files/8838448/crash-2022-06-04_00.35.38-client.txt)

Without Rubidium, my game fps has gone bad :(

**Comment by Benjamboo** [comment]
After waiting a few weeks on this I just hopped to the Jellysquid discord and asked politely if Sodium had a similar issue, and they supplied the following, there's something corrupted in the code (It might not just be the fact that Rubidium isn't setup for the 1.18.2 worldheight. (I think Upstream is their term for the Fabric Sodium mod).

![Screenshot_3](https://user-images.githubusercontent.com/68694038/172302423-3467dfb7-f5eb-487f-b392-dc88378a41de.png)

**Comment by ghost** [comment]
Rubidium seems to be quite unstable on some machines. Try Chlorine! It's abandoned but I think it's one of the most compatible Sodium ports out there

**Comment by Asek3** [comment]
Update to 0.5.4
