### ISSUE TITLE
[Startup Crash] Mod Incompatibility with Sralight x Create.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#13]
https://www.curseforge.com/minecraft/mc-mods/starlight-x-create

[debug.log](https://github.com/Asek3/Rubidium/files/7977320/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/7977319/latest.log)

rubidium-0.4.0c

**Comment by Atlantispy** [comment]
I'm running with Starlight forge and experiencing no crash.

**Comment by KKotik** [comment]
Do you use Starlight x Create branch? This is totally happening for me, doing some more tests even in clear instance.

**Comment by Atlantispy** [comment]
No, just the original starlight, at the same time as create.

**Comment by KKotik** [comment]
That's the issue, because I have a branched version that support Flywheel.

**Comment by Atlantispy** [comment]
But why do you need that, I'm running both starlight and create with no issues?

**Comment by KKotik** [comment]
Place a create bell, you will be crashed.

**Comment by StarskyXIII** [comment]
To make sure you have the latest version Flywheel & Starlight [1.0.1](https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/3599856)
It seems work fine for me.

![2022-02-01_20 38 13](https://user-images.githubusercontent.com/71606873/151969809-39adf9c0-50da-4f41-b9c1-c41b538d0a49.png)

**Comment by Atlantispy** [comment]
Same, works for me too

**Comment by KKotik** [comment]
Again, I am talking about different fork. I understand that everything works fine, on different another *special version* of default startlight.

**Comment by Atlantispy** [comment]
> Again, I am talking about different fork. I understand that everything works fine, on different another _special version_ of default startlight. It also contain some bugs as well. Like missing block lighting from some blocks and as well as vanilla magma.

I think our point is why use a special version if the main version works correctly, eliminating the need for a *special* version.

**Comment by KKotik** [comment]
I got it, chaging starlight branch fixes that. I will wait when original one will have a things fixed for some modded blocks and magma blocks on their side.
