### ISSUE TITLE
[1.16.5 - Newest Version] Biome Blending Error

### ISSUE THREAD

**Issue by ThanEEpic** [Asek3/Rubidium#130]
I get a terrible biome blending issue when using this mod. I love the FPS boost(like more than double) but this issue is awful. It happens with or without other mods. Thanks!

![2022-05-18_17 36 40](https://user-images.githubusercontent.com/28547766/169160009-41392d9c-4b30-4ac7-b9ec-4251bf979f41.png)

**Comment by TheVillain-Inc** [comment]
Yup - can confirm. Also happening for me, regardless of BiomeBlend setting.

**Comment by Asek3** [comment]
Fixed in 0.2.7
