### ISSUE TITLE
1.16.5 - Crash after loading into world

### ISSUE THREAD

**Issue by SteaSteaStea** [Asek3/Rubidium#131]
I am using better end reforked which should be compatible.
The game crashed after loading into my world.
Using [Rubidium mc1.16.5-0.2.6]
https://crashy.net/0Oe1KWAR2HMUiQwHfzAX

**Comment by Delfite** [comment]
I'm having a similar issue, however this one seems to be caused by Faulty Mixins: https://pastebin.com/6NYyad6P

**Comment by Asek3** [comment]
Should be fixed in last releases
