### ISSUE TITLE
Tinted textures rendering grayscale in fluid containers

### ISSUE THREAD

**Issue by Kenpari** [Asek3/Rubidium#132]
**Minecraft Version:** 1.18.2
**Rubidium Version:** 0.5.2a

This came about after playing around with some settings in Tinker's Construct. The lanterns from that mod, which can hold a number of fluids and function as light sources using them, use a dynamic model, which can be enabled for all fluid tanks via TiC's config. This report comes about from a related issue regarding Oculus, where fluids in forge containers fail to render at all. I won't go into too much detail because this isn't about the Oculus issue, but these dynamic models enable the textures to render properly in Oculus, but Rubidium causes a secondary issue with them, where certain fluid textures will render fully in grayscale, which is what this issue is about. 

Images are produced running only Forge 40.1.19, Rubidium 0.5.2a, Tinker's Construct 3.5.0.18, and Mantle 1.9.20. The last one also includes Oculus, though the first one was tested completely without Oculus installed.

![2022-05-19_17 07 44](https://user-images.githubusercontent.com/643984/169423599-566e7a95-3daa-4ed4-b3c1-f499e960dea8.png)

This demonstrates the textures turning grayscale, minus a few select textures. The one pictured next to lava, 4th from the left on the second row, is Water.

![2022-05-19_17 02 55](https://user-images.githubusercontent.com/643984/169423242-2c57d0d1-ef68-456c-8206-69cf3a4b0ce0.png)

The only grayscale fluid in this image is Water. The others were removed, though they still appear grayscale, even with shaders active. This was just to test that Oculus does not in fact break fluids rendered in this manner, but Rubidium does break them somehow.

Some information regarding this issue from a discussion with KnightMiner, the developer of Tinker's Construct, which might be useful for diagnosing this issue:

KnightMiner — Today at 4:21 PM
I would suggest reporting this to Rubidium
they are either breaking block tinting based on TESRs, breaking fluid colors from mantles system, or breaking something else
try water, that is a tinted fluid that bypasses mantles system

(after testing with water)
KnightMiner — Today at 4:34 PM
water is a tinted texture
this confirms that the cause is all tints failing, narrows things down
I assume changing fluid amounts properly updates (note: they do), which means its the block colors is not running
makes me question if all TE based block colors are failing
Cannot think of any others to test though

**Comment by rckymtnrfc** [comment]
I'm seeing the same issue with Sophisticated Backpacks and Storage.  Blocks that are dyed look correct as items but when placed in world, they are greyish white.

Forge 40.1.19
Rubidium 0.5.2a
Sophisticated Core 0.1.0.19
Sophisticated Backpacks 3.16.4.584
Sophisticated Storage 0.0.11.26

**Comment by flarefluffsune** [comment]
> I'm seeing the same issue with Sophisticated Backpacks and Storage. Blocks that are dyed look correct as items but when placed in world, they are greyish white.

I'm having this same issue. Everything is fine when I disable Rubidium.

Forge 40.1.25
Rubidium 0.5.2a
Sophisticated Core 0.2.5.28
Sophisticated Backpacks 3.17.2.588
Sophisticated Storage 0.1.1.35

**Comment by Tander** [comment]
Minecraft Version: 1.18.2
Rubidium Version: 0.5.2a

![2022-07-09_03 11 40](https://user-images.githubusercontent.com/1059805/178083905-fb1619e7-b29d-452e-8cb9-06e6fe73f99c.png)
![2022-07-09_03 11 58](https://user-images.githubusercontent.com/1059805/178083910-3191ba3b-ed8a-41ed-9078-c812035f49a2.png)


It's biome blending. @Asek3 is it possible to fall back to vanilla blending until it fixed?

Looks similar to this issue:
https://github.com/CaffeineMC/sodium-fabric/issues/895
