### ISSUE TITLE
Got this Crash after playing for a while, Mod is incompatible with Tinkers Construct (1.16.5)

### ISSUE THREAD

**Issue by lSherozl** [Asek3/Rubidium#140]
[crash-2022-06-02_01.16.03-client.txt](https://github.com/Asek3/Rubidium/files/8821625/crash-2022-06-02_01.16.03-client.txt)

This crash is DEF CAUSED by rubidium or Oculus, one or the other, these bugs need to be fixed as soon as possible, for now will have to uninstall, as this mod is unpredictable. 

[crash-2022-06-02_22.52.45-client.txt](https://github.com/Asek3/Rubidium/files/8829597/crash-2022-06-02_22.52.45-client.txt)

Same type of flickering that happens and crash that happens again ^

So what ends up happening is you are randomly going around the world, you come across some part of the world not being loaded up properly, and then suddenly, the screen flickers a bunch of times, and then everything just becomes red and loses color and game crashes. This picture below is supposed to be of a blue slime island, as you can see it is see through even though you can stand on the blocks. Go near it, game flickers and crashes. Def will uninstall until it has been made compatible with some of the mods its crashing with. The slime islands are from tinkers construct mod, meaning even without shaders, the blocks are not visible and this is incompatible with the mod.
![284659600_531024721792911_1201236048683538580_n](https://user-images.githubusercontent.com/65663746/171789935-5860b377-7b19-4f83-a918-558331ddec10.jpg)
![284632741_682779103011228_7269464310436565806_n](https://user-images.githubusercontent.com/65663746/171819976-c7c9c4cf-2568-42e7-a235-6f58b14711fb.jpg)

**Comment by aethaerya** [comment]
You report this after testing with 460+ mods? Really?
![image](https://user-images.githubusercontent.com/28931355/172036155-d351677d-895a-438a-b6c2-89588cd4ea48.png)


![image](https://user-images.githubusercontent.com/28931355/172035911-41b225ea-db7c-4491-a22d-eb9ed714f773.png)
![image](https://user-images.githubusercontent.com/28931355/172036018-a2033ed9-6807-479e-9f59-365906f2233a.png)
![image](https://user-images.githubusercontent.com/28931355/172036039-ad248eeb-ca95-4912-9d80-66795e399c36.png)

**Comment by lSherozl** [comment]
@aethaerya  Optifine is even worse than this mod when it comes to FPS, and even it doesnt display the slime islands like that with same number of mods and I get 300 FPS without the shaders, and about 100 FPS with this mod and shaders, its a problem with this mod, not some incompatibility of why the slime islands are like that, optifine runs the same shaders at a worse fps but the slime islands are not broken...so the issue is probably a incompatibility with this mod and other ones, not the mods added before this one was.

**Comment by aethaerya** [comment]
Indeed, it is an issue with this mod, but not directly with Tinkers' Construct.

**Comment by lSherozl** [comment]
> Indeed, it is an issue with this mod, but not directly with Tinkers' Construct.

If optifine gets the slime islands right, but this mod does not, then its a problem with something this mod does or what oculus does, or how they interact with another mod, im not the only person posting reports of chunks not loading properly

**Comment by aethaerya** [comment]
It's likely a three-way mod incompatibility, not directly incompatible with Tinkers' Construct. A third mod is causing the crash, and you need to find out what that is and not do "isolation tests" with 460+ mods. You are helping no one.

**Comment by Asek3** [comment]
Should be fixed on latest versions
