### ISSUE TITLE
crash while teleporting to unloaded chunks while riding a Create contraption

### ISSUE THREAD

**Issue by SpottyTheTurtle** [Asek3/Rubidium#144]
version: 1.18.2, probably also on other versions but I haven't checked.
log: attached to issue
steps to perform: 
    1) create a cart contraption with
[crash-2022-06-08_17.06.36-client.txt](https://github.com/Asek3/Rubidium/files/8863314/crash-2022-06-08_17.06.36-client.txt)
 Create and fully assemble it before sitting in any seat attached to the entity. 
    2) tp to any spot outside of loaded chunks. Create tries to stop you from doing this so you may need to run the command multiple times
    3) game crashes

**Comment by Asek3** [comment]
Should be fixed on latest versions
