### ISSUE TITLE
[1.18.2] AE2 Component Colouring

### ISSUE THREAD

**Issue by Lordfirespeed** [Asek3/Rubidium#145]
### Mods to recreate:
Applied Energistics 2 (11.1.0)
JEI (1.18.2-9.7.0.195)
Rubidium (0.5.2a)
Forge (40.1.31)

### Description
Access terminals (and other ME components) are not correctly re-coloured when attached to a coloured ME cable.

### Recreation steps:
Place an ME controller and power it. 
Place a _coloured_ ME Smart Cable onto the ME controller.
Place any ME access terminal onto the coloured cable.

### Expected Result
ME access terminal/component changes colour to match the cable colour.

### Actual Result
ME access terminal/component always remains default colour (purple-y)

**Comment by Asek3** [comment]
Should be fixed in latest versions or next release
