### ISSUE TITLE
Project red blocks/multipart blocks not rendering (1.16.5)

### ISSUE THREAD

**Issue by GriSphera** [Asek3/Rubidium#146]
Blocks from the project red mod series don't render properly.

I've tested it and it indeed is an issue with these two mods. Maybe cbmultipart or ccl are causing the problem, since those two are requiered dependencies for it, and blocks from the multipart mod don´t render either.

Here are some screenshots of it. Some things like particles, light, and others like the timers pointer are visible though.

![2022-06-08_14 42 54](https://user-images.githubusercontent.com/88846902/172705090-8b11163d-fab9-4be9-9a60-d3968f2f8b1a.png)
![2022-06-08_14 42 59](https://user-images.githubusercontent.com/88846902/172705124-fd449370-8c4d-4d80-a5c4-03250c9fd3fd.png)
![2022-06-08_14 43 10](https://user-images.githubusercontent.com/88846902/172705161-0ad51dd7-27aa-4dbd-b499-5eb3cf2027cd.png)
![2022-06-08_14 43 25](https://user-images.githubusercontent.com/88846902/172705200-6707d061-1f3e-4ea9-b570-c67fd3076b3f.png)
![2022-06-08_14 43 29](https://user-images.githubusercontent.com/88846902/172705236-dbe061ab-d2fb-4e0b-a008-ac280e9f5cd9.png)
![2022-06-08_14 50 35](https://user-images.githubusercontent.com/88846902/172705266-6886cc5d-77a0-43a3-b19e-428909835a66.png)

**Comment by Asek3** [comment]
Fixed in 0.2.8
