### ISSUE TITLE
[Bug] Rubidium breaks AE2 ME Drive lighting

### ISSUE THREAD

**Issue by Vapaman** [Asek3/Rubidium#149]
Minecraft Version 1.18.2

**Mod versions:**
appliedenergistics2-11.1.2
rubidium-0.5.2a

**Pictures:**
With Rubidium, the front of the ME Drive is permanently cast in shadow
![kuva](https://user-images.githubusercontent.com/77460466/172957964-5f09b51e-3835-42c8-88eb-bfa4bd3bfcad.png)

For comparison, without Rubidium
![kuva](https://user-images.githubusercontent.com/77460466/172958002-84fc939a-3884-4b2d-9acc-dd790899aaff.png)

**Comment by Vapaman** [comment]
Forge version: 40.1.51

**Comment by Odey555** [comment]
Can confirm. Same thing happening on All The Mods 7 v0.4.21
Have Rubidium, Rubidium Dynamic Lights, and Rubidium Extras installed. 
ME Chest doesn't have this rendering error despite it also having inset faces. 
![image](https://user-images.githubusercontent.com/1361563/179101261-6e02a075-672d-45a6-96fb-eb858a237b57.png)

**Comment by Vapaman** [comment]
Still happens with Rubidium 0.5.3 & AE2 11.1.4

**Comment by Vapaman** [comment]
Still happens with Rubidium 0.5.3a & AE2 11.1.5
