### ISSUE TITLE
[Startup Crash] Mod Incompatibility with KubeJS.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#15]
https://www.curseforge.com/minecraft/mc-mods/kubejs-forge

[debug.log](https://github.com/Asek3/Rubidium/files/7977351/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/7977352/latest.log)

rubidium-0.4.0c

**Comment by Atlantispy** [comment]
I'm also running with KubeJS and experiencing no crash

**Comment by KKotik** [comment]
Seems like I stopped getting this crash too. U guess that closed. Migth be the issue was in something else, guess other my crash reports should be leading to that.
