### ISSUE TITLE
[1.16.5] Rubidium incompatible with BetterEnd (Forge)

### ISSUE THREAD

**Issue by Asveste** [Asek3/Rubidium#150]
Immediatley after entering the world with BetterEnd (Forge) installed the game crashes.

Mod Link: https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port

Crashlog: https://pastebin.com/FSqjwX3q
Latest Log: https://gist.github.com/Asveste/cde0c2b2e18d4e68e7e52133db20d0ab

**Comment by Asek3** [comment]
https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files
Update BetterEnd
