### ISSUE TITLE
World does not render correct with forge 41.0.35 (1.19)

### ISSUE THREAD

**Issue by agentwolf88** [Asek3/Rubidium#159]
World does not render correct with forge 41.0.35
Rubidium mc1.19-0.6.0

![2022-06-16_17 44 25](https://user-images.githubusercontent.com/9948479/174111420-1b1c52e6-d9bc-49df-bd63-03c2c9bb1bf8.png)

**Comment by Tsoccerguy3** [comment]
Everyone will have this issue with this Forge and future forge version untill method is fixed

**Comment by NoShotz** [comment]
What's exactly causing the issue?

**Comment by Asek3** [comment]
send log plz

**Comment by Atlantispy** [comment]
[debug.log](https://github.com/Asek3/Rubidium/files/8933743/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/8933744/latest.log)

Different person but same issue

**Comment by Asek3** [comment]
Update Rubidium to 0.6.0a
