### ISSUE TITLE
[1.18.2] Model Texture Glitch with IE and Mekanism

### ISSUE THREAD

**Issue by Paulie820** [Asek3/Rubidium#161]
With Rubidium 0.5.2a installed, parts of textures on mekanism and Immersive Engineering blocks are glitched as shown. This does not affect all models, seems to happen primarily with those that have connecting textures (Alloy Kiln multiblock, mekanism's cables, pipes.

![2022-06-17_23 47 14](https://user-images.githubusercontent.com/56102321/174424828-068b1777-2184-40b7-b07f-0941cc7f176b.png)

**Comment by ghost** [comment]
Issue still exists with version 0.5.3.

**Comment by LilJagty** [comment]
I experienced this glitch today with the Ultimate tier of cables, but strangely not the others. Seems to be a bit inconsistent.

**Comment by Asek3** [comment]
Fixed in https://github.com/Asek3/Rubidium/commit/65d3ddaca335215e33a18346d2c3fa8139d08653
