### ISSUE TITLE
(1.18.2) Incompatibility with Dynamic Surroundings Resurrected

### ISSUE THREAD

**Issue by Orgamorsh** [Asek3/Rubidium#170]
The footsteps in Dynamic Surroundings Resurrected do not render while rubidium installed.

**Comment by DarkSoulMastery** [comment]
I got this same issue too, I don't see any footsteps when walking on grass or snow.

**Comment by SkullDiamond** [comment]
Disable the "use particle Culling" option 
![image](https://user-images.githubusercontent.com/79324102/181123286-af7061ea-3f9f-41eb-a757-4d0d151e3e0a.png)

**Comment by Asek3** [comment]
Fixed in Dev
