### ISSUE TITLE
1.18.2 modpack crashes if Rubidium is installed

### ISSUE THREAD

**Issue by R3alRezentiX** [Asek3/Rubidium#173]
Hi, I tried to include Rubidium 0.5.2a in my 1.18.2 modpack, but it just crashes if Rubidium is installed. 
Here is crash report: https://pastebin.com/1y10sUcC

<details>
<summary>Mod list</summary>

1. 3D Skin Layer
2. Additional Banners
3. Additional Lanterns
4. AI Improvements
5. Apotheosis
6. Apple Skin
7. Architect's Palette
8. Architectury
9. Artifacts
10. AutoRegLib
11. Balm
12. Better Advancements
13. Biomes O' Plenty
14. Bookshelf
15. Bad Wither No Cookie
16. Catalogue
17. Chunk Animator
18. Client Tweaks
19. Clumps
20. CoFH Core
21. Collective
22. Configured
23. Cosmetic Armor Reworked
24. CraftTweaker
25. Create Additions
26. Create
27. Curio of Undying
28. Curios
29. Decorative Blocks
30. Ding
31. Dungeons Enhanced
32. Easy Magic
33. Ecologics
34. Engineer's Decor
35. Enhanced Celestials
36. Enlightened End
37. Ensorcellation
38. Expandability
39. FastFurnace
40. Fast Leaf Decay
41. FastWorkbench
42. Flywheel
43. Friends and Foes
44. FTB Chunks
45. FTB Library
46. FTB Quests
47. FTB Teams
48. Illagers Wear Armor
49. Immersive Weathering
50. Immersive Engineering
51. Iron Chest
52. ItemFilters
53. JEI
54. JEI Integration
55. JEI Tweaker
56. JMI
57. JourneyMap
58. Just Enough Professions
59. Just Enough Resources
60. Macaw's Bridges
61. Macaw's Doors
62. Macaw's Fences
63. Macaw's Furniture
64. Macaw's Lights
65. Macaw's Paintings
66. Macaw's Roofs
67. Macaw's Windows
68. Mod Name Tooltip
69. More Villagers
70. Mouse Tweaks
71. Nature's Compass
72. Nether Portal Fix
73. Nourished Nether
74. Patchouli
75. Placebo
76. Puzzles Lib
77. Quark
78. **Rubidium**
79. Sapience
80. Serene Seasons
81. Shut Up, Experimental Settings
82. Simple RPC
83. Structure Gel
84. SuperMartijn642's Corelib
85. TerraBlender
86. The One Probe
87. Upgraded Core
88. Upgraded Netherite
89. Villager Names
90. Yung's API
91. Yung's Better Dungeons
92. Yung's Better Strongholds
93. Yung's Bridges
94. Yung's Extras

</details>

**Comment by Asek3** [comment]
Rubidium is not compatible with ChunkAnimator
