### ISSUE TITLE
ColorSampler is called on wrong block entity

### ISSUE THREAD

**Issue by yanang007** [Asek3/Rubidium#175]
### Game version: 
1.18.2
### Mod version: 
Rubidium 0.5.2a
Reliquary 1.18.2-2.0.8.1139

### Step to reproduce:
1. Install both Reliquary and Rubidium.
1. Get into the game and place a cauldron and a mortar(any other block with block entity also works) near each other.
1. Game crashes.

### Crash report:
https://paste.ubuntu.com/p/z4ZJp9ZnTH/

Possible cause is that rubidium's color blender [LinearColorBlender](https://github.com/Asek3/Rubidium/blob/e3aea98992e110b41ceed5ab128c81ff6fd98fa0/src/main/java/me/jellysquid/mods/sodium/client/model/quad/blender/LinearColorBlender.java#L53-L56) will call this [color sampler](https://github.com/P3pp3rF1y/Reliquary/blob/b018bf4f56ee2042e230517c9da68d6b1c188bdb/src/main/java/reliquary/client/init/ModBlockColors.java#L13-L22) on registered block and its neighbouring blocks, ignoring that it is registered on a specific block entity.
According to related issues in sodium repo, there has been some solution recently. I would appreciate that if you are willing take your time to port it. : ) 

### Related Issues:
LinearColorBlender breaks any case where a precise position is required in a BlockColorProvider. ([CaffeineMC/sodium-fabric#1323](https://github.com/CaffeineMC/sodium-fabric/issues/1323))
Blockentity with color not rendered correctly ([CaffeineMC/sodium-fabric#895](https://github.com/CaffeineMC/sodium-fabric/issues/895))
[1.18.2] Game crashed when apothecary cauldron is placed near other block entities with Rubidium installed ([P3pp3rF1y/Reliquary#578](https://github.com/P3pp3rF1y/Reliquary/issues/578))

**Comment by Tander** [comment]
Seems similar to https://github.com/Asek3/Rubidium/issues/132
