### ISSUE TITLE
Error in build.gradle . sources don't compile

### ISSUE THREAD

**Issue by Tsoccerguy3** [Asek3/Rubidium#177]
I think your build.gradle needs to be updated . I have no idea where any of your dependencies can be found.

----------------------------------------------------------------------------------------------
G:\Dev\Rubidium>gradlew build

> Configure project :
Architectury Loom: 0.11.0.275

> Task :compileJava
G:\Dev\Rubidium\src\main\java\me\jellysquid\mods\sodium\client\render\chunk\tasks\ChunkRenderRebuildTask.java:16: error: package net.coderbot.iris.compat.sodium.impl.block_id does not exist
import net.coderbot.iris.compat.sodium.impl.block_id.ChunkBuildBuffersExt;
                                                    ^
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

----------------------------------------------------------------------------------------------
G:\Dev\Oculus>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\Dev\Oculus\build.gradle' line: 2

* What went wrong:
Plugin [id: 'dev.architectury.loom', version: '0.11.0-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'dev.architectury.loom:dev.architectury.loom.gradle.plugin:0.11.0-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 706ms

**Comment by Asek3** [comment]
Was fixed by https://github.com/Asek3/Rubidium/pull/407
