### ISSUE TITLE
[BUG] Tinkers Construct tools are being white instead of colored.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#18]
Tinkers Construct is not released yet, but I hope that might help fix future bug that may appear for more people.
Tinker's tools are colored by code, for some reason parts are properly colored, here example:
![image](https://user-images.githubusercontent.com/45950781/152128464-158a8b59-137b-4f38-8c3e-a804bdcfd320.png)
But tools are not:
![image](https://user-images.githubusercontent.com/45950781/152128526-64456fd5-023f-4dba-9ae7-592d140eab47.png)

Here Tinker's Construct github: https://github.com/SlimeKnights/TinkersConstruct/tree/1.18

**Comment by KKotik** [comment]
[debug.log](https://github.com/Asek3/Rubidium/files/7985191/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/7985194/latest.log)

**Comment by Asek3** [comment]
![image](https://user-images.githubusercontent.com/64613894/152130849-276abd2c-ebb8-4116-ae3e-cc58c38259d9.png)
Hmm, try to build newer TiCon and Mantle sources

**Comment by KKotik** [comment]
Using recent build still not helping, will try to dig more about it.
![image](https://user-images.githubusercontent.com/45950781/152136121-2c7c092e-8631-4860-a8d4-e3b75f8f5dc4.png)

**Comment by KKotik** [comment]
As soon as I get the mod out, it is working. 
![image](https://user-images.githubusercontent.com/45950781/152138245-da773d93-c48d-4ecd-bf2d-f36d9b3d69d4.png)

**Comment by KKotik** [comment]
I think that might be helpful.
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/commit/b9d59dfec6053cf5fda3c05378557fb79be4b065
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/commit/53f8b2743a72fcc7da9bcf8b41471a5dcd0d4bf2

**Comment by drakosoldier298** [comment]
it seems in 1.18.2 this bug may have returned.
rubidium version 0.5.2a

tinkers construct version- 3.5.1.31
![image](https://user-images.githubusercontent.com/30358222/174659015-29f18583-9810-4074-bb62-a16f81a15b04.png)

![image](https://user-images.githubusercontent.com/30358222/174659096-b0b437cc-3255-4d4c-986f-cf456c59423e.png)
