### ISSUE TITLE
[Rendering] Water side rendered improperly when near translucent blocks

### ISSUE THREAD

**Issue by yezhiyi9670** [Asek3/Rubidium#182]
Vanilla

![2022-07-06_10 21 31](https://user-images.githubusercontent.com/39194383/177454118-67ef9df6-c56b-458a-8da2-afabb0164902.png)

Rubidium

![2022-07-06_10 18 12](https://user-images.githubusercontent.com/39194383/177453674-ac8a7072-4087-4613-954e-61832538d53c.png)

Note: This issue exists in nearly all Forge ports of Sodium, except Sodium Reforged for 1.16.5. The fabric version of Sodium is probably also the case.

**Comment by Asek3** [comment]
Translucency Sorting is not present in Sodium, so probably there will be no fix. As I can remember Halogen has broken implementation of "fix"
