### ISSUE TITLE
[Forge 1.16.5] Flowing water crashes the game

### ISSUE THREAD

**Issue by hoyiliang** [Asek3/Rubidium#186]
### **How to reproduce:**
Make a flowing water with a water bucket.

### **Crash Report:**
[crash-2022-07-09_03.06.47-client.txt](https://github.com/Asek3/Rubidium/files/9074638/crash-2022-07-09_03.06.47-client.txt)

### **Screenshots:**
Safe, no issues with stand-still water.
![2022-07-09_03 27 04](https://user-images.githubusercontent.com/51823045/178058323-fe5a0634-04a1-4f2b-8654-3f12a06e38bc.png)

Game basically crashed at this point and I have to screenshot using Snippet Tool
![Crash](https://user-images.githubusercontent.com/51823045/178058373-e494c0a1-538d-448a-92d1-61511a4df62f.png)

**Comment by hoyiliang** [comment]
I found out that it only crashes when Biome Blend is turned on (any value will crash)

**Comment by Asek3** [comment]
Update https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files
