### ISSUE TITLE
Mod Incompatibility: Snow! Real Magic!

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Rubidium#19]
This mod:

https://www.curseforge.com/minecraft/mc-mods/snow-real-magic

Bug is once something has snow in the same block, IE fences or tall grass, it turns invisible.

Thanks

**Comment by KKotik** [comment]
Change the title of issue to: [BUG] Snow Real Magic Incompatibility
So people will notice that and do not report same one.

I really don't know if it possible to fix at all. Seems like default sodium is Incompatible with it even on Fabric.
This one will be real hard affort, so I bet if dev won't fix that, better to close this issue.

As for examples, here are they:

As for folliage. (Grass, flowers and etc..)
![image](https://user-images.githubusercontent.com/45950781/152364276-70a4ec9b-3306-4d61-9f9a-90124dd1c5db.png)
![image](https://user-images.githubusercontent.com/45950781/152364289-28acb06a-1419-467e-b565-e9e4988bd194.png)

As for snow logging blocks.
![image](https://user-images.githubusercontent.com/45950781/152364565-f72f2bfc-ad64-4304-bb88-773812ef12aa.png)
![image](https://user-images.githubusercontent.com/45950781/152364606-f6965880-7f21-43b7-8a55-bd06ec95c620.png)

**Comment by Atlantispy** [comment]
I mean I'm gonna leave it to see if they can fix it before closing it myself.

**Comment by Matthysse** [comment]
It's fixable, the Snow Real Magic dev made the 1.16.5 version compatible with Magnesium with these commits : https://github.com/Snownee/SnowRealMagic/commit/043918f0ae26d7e5368c53a22f162cdae2e504a6
and
https://github.com/Snownee/SnowRealMagic/commit/ff1d643873637f4039b896d914f4fb4ffa6bb9d5
As a result, both mods are perfectly compatible on 1.16.5.
I asked the dev why he didn't make this change to 1.18 as well, and he answered this:
![image](https://user-images.githubusercontent.com/32510957/153202234-d03d41a7-9cfc-4134-a374-104af02bf781.png)
Hope this can help!

**Comment by Atlantispy** [comment]
Any news on this?

**Comment by Matthysse** [comment]
Yeah, but not good news:
![image](https://user-images.githubusercontent.com/32510957/155379227-9e351e22-0de2-49b8-8081-e1ad308bea44.png)
We will have to wait long...

**Comment by Atlantispy** [comment]
<img width="1220" alt="dc4eba56bd652850867cf5a6c4dd4edc" src="https://user-images.githubusercontent.com/8345523/155589729-1ec13e74-1724-4c45-8b3b-ab9429bc254a.png">

A little better news

**Comment by IAnon** [comment]
This is mainly fixed in Snow Real Magic 4.1.0, the only issue I was seeing was the slabs were having some texture clipping issue when moving.

**Comment by Asek3** [comment]
So, resolved on their end
