### ISSUE TITLE
Game doesn't even open: spongepowered.asm.mixin.transformer

### ISSUE THREAD

**Issue by SuperSly12** [Asek3/Rubidium#190]
The moment I launch it, it crashes. I tried all Rubidium's 1.19 versions and all of them came with the same results.
\
The crash file:
[crash-2022-07-11_16.03.25-client.txt](https://github.com/Asek3/Rubidium/files/9087235/crash-2022-07-11_16.03.25-client.txt)

**Comment by Asek3** [comment]
Update Forge

**Comment by SuperSly12** [comment]
Are there 1.19 versions that are pre 41.0.63? Any version higher messes
with every other mod in my modpack.

**Comment by Asek3** [comment]
[0.6.0a](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/3839967)
