### ISSUE TITLE
1.18.2 Create Fluid Pipe Rendering Bug

### ISSUE THREAD

**Issue by Tohricat** [Asek3/Rubidium#192]
When viewing a fluid pipe at a specific angle, parts of it disappear. Thanks for the mod!
![image](https://user-images.githubusercontent.com/53372339/178804565-4bff507e-3960-4e3f-bf47-911f88038921.png)

**Comment by cyco20** [comment]
Im having the same problem

**Comment by Charismara** [comment]
Same problem here:
![2022-08-01_10 31 03](https://user-images.githubusercontent.com/14293974/182107384-31ad55b2-d8cc-4d9d-85fc-7b1cfcb08d7d.png)

**Comment by Asek3** [comment]
Seems to be fixed in next Create release https://github.com/Creators-of-Create/Create/commit/6c0af5f83f9ba576d215c3e7e26298cb605da02f

Just wait

**Comment by java-jambalaya** [comment]
In the meantime, disabling `Block Face Culling` fixed this issue for me.
