### ISSUE TITLE
[1.19, Forge 41.0.63] Crash when attempting to open Minecraft through the launcher [Probably a problem on my side, not sure but this is for reference]

### ISSUE THREAD

**Issue by A17Forkybest303** [Asek3/Rubidium#196]
Exit code 1 happens when attempting to load Minecraft through the Minecraft launcher
[crash-2022-07-19_19.39.19-client.txt](https://github.com/Asek3/Rubidium/files/9140674/crash-2022-07-19_19.39.19-client.txt)

**Comment by Asek3** [comment]
Update Forge

**Comment by A17Forkybest303** [comment]
> Update Forge

![image](https://user-images.githubusercontent.com/78596321/179743596-a0c597da-74f4-4252-bf4b-1f9c8a5cbc0f.png)
updated to forge 41.0.100
well this version crashes when i have mods in the mods folder

- reinstalled mc launcher didnt work
@Asek3
