### ISSUE TITLE
Crash on startup with Better Foliage

### ISSUE THREAD

**Issue by Jrassic** [Asek3/Rubidium#199]
### Minecraft Version

1.16.5

### Iris Version

Oculus 1.2.3 pre

### Sodium Version

Rubidium 0.2.6

### Operating System

Win 10

### What is your GPU?

Nvidia Geforce GTX 1050Ti

### Java Version

Java 8

### Reproduction Steps

1.Put Oculus, Rubidium, Better Foliage and Kotlin (dependency) into your mod folder
2. Run  Game
3. Crash (Process exited with code -1.)

It does not create a crash report

### Additional context

Better Foliage version 2.7.1

Unofficial fork "Better Foliage Renewed" works

**Comment by Enterprise12nx01** [comment]
Same issue, sadly better foliage renewed only really works with vanilla objects only

**Comment by Asek3** [comment]
That is Rubidium's issue and probably will not be fixed.
