### ISSUE TITLE
1.18.1/0.4.0a Startup crash

### ISSUE THREAD

**Issue by FrosTNoVaS** [Asek3/Rubidium#2]
[latest.log](https://github.com/Asek3/Rubidium/files/7971281/latest.log)
[debug.log](https://github.com/Asek3/Rubidium/files/7971282/debug.log)
[crash-2022-01-31_17.02.17-client.txt](https://github.com/Asek3/Rubidium/files/7971284/crash-2022-01-31_17.02.17-client.txt)

**Comment by Asek3** [comment]
Update BeyondEarth, problem was resolved on 6.0c
