### ISSUE TITLE
Thank you + 3 features suggestions

### ISSUE THREAD

**Issue by Finelarme9** [Asek3/Rubidium#20]
Hi there.

Thank you so much for that port! Indeed, you solve that problems problems I had with Magnesium (and Optifine). Also, do you plan to add 1/2/3 features below in the future please ? I really don't want to go back toward Optifine :

- Dynamic light (like Optifine) (since the mod [Dynamic light](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights) is not working fine)
- Custom Sky (like Optifine)
- Shaders (like Optifine)

In all case, thank you for your time.

**Comment by Asek3** [comment]
Okay, let's take it in order.
To my mind Rubidium should only optimize game, all additional features need to be
recreated in another mod.
What about shaders, I am already working on porting Iris.
