### ISSUE TITLE
1.16.5 -  Rubidium mc1.16.5-0.2.8 - Compatibility crash with Flywheel

### ISSUE THREAD

**Issue by shikyo13** [Asek3/Rubidium#200]
https://pastebin.com/nxEMea6p

flywheel-1.16-0.2.4.jar

rubidium-0.2.8.jar

Forge - 36.2.31

**Comment by RePixelatedMC** [comment]
It only happens when ur using batching ( it should get fixed tho )

**Comment by Asek3** [comment]
Loaded on CurseForge wrong jar, plz redownload 0.2.8

**Comment by shikyo13** [comment]
Now I am able to start the client, but crash when opening video settings. Repeatable. 

https://pastebin.com/QpnvXaZP

Edit: Updating Oculus version to your latest release Oculus mc1.16.5-1.2.5a has fixed the crash. Thanks.
