### ISSUE TITLE
JEI compat issue

### ISSUE THREAD

**Issue by PikachuGabe** [Asek3/Rubidium#202]
If you have JEI installed along with rubidium,the items will not show unless you have something in the search bar. Modpack I am using: https://www.curseforge.com/minecraft/modpacks/darklands-frontiers (you will have to manually add rubidium)
![2022-07-21_14 28 16](https://user-images.githubusercontent.com/84477180/180318294-1c6dc3b0-29e6-476b-a596-8d35114d5c52.png)
![2022-07-21_14 28 10](https://user-images.githubusercontent.com/84477180/180318297-1b31e6f0-25f6-4360-aac6-d0df2e5141a7.png)

**Comment by Asek3** [comment]
That's Rubidium Extras feature, not Rubidium's

**Comment by papillo12** [comment]
Use rei
