### ISSUE TITLE
Modpack Rubidium Crash - 1.16.5  - java.util.concurrent.CompletionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by theTyrfing** [Asek3/Rubidium#205]
### Game version:
1.16.5

### Java Version:
Java 8

### Mod version:
Rubidium 0.2.7
Magnesium Extras 1.3.1

### Other Mods:
See the crash report for the mod list. I wish multiMC had an easy way to export the mod list in a concise way.

### Step to reproduce:
1. Install mods above
2. Create a new world
3. Login into it

### Crash report:
https://bytebin.lucko.me/b0xPZRkvbH

### Notes
I was trying to switch from Optifine to Rubidium. However, I keep getting this crash upon loading the world that prevents me from doing so. I am not sure if there is a known mod conflict or another mod messing with the rendering. I have not try to individually disable and enable my mods to single it out yet. However, I would like to know if there is any known conflict before I go through that process.

**Comment by theTyrfing** [comment]
I made the title like that for people with similar error to keyword search this easier.

**Comment by ProsperCraft** [comment]
Same problem when added to my TownCraft modpack
https://gist.githubusercontent.com/ProsperCraft/a0ae219ae8d9c7800fbed9c72478dd2f/raw/0f935eee769e69c5d859a88bc08d5571e9dd2ce9/gistfile1.txt

**Comment by theTyrfing** [comment]
> Same problem when added to my TownCraft modpack https://gist.githubusercontent.com/ProsperCraft/a0ae219ae8d9c7800fbed9c72478dd2f/raw/0f935eee769e69c5d859a88bc08d5571e9dd2ce9/gistfile1.txt

@ProsperCraft 
I found the problem after much testing. We are both original version of the better end mod which has problems with sodium. There is a reforked version of it that works better now (https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked). 

Some people have encountered this problem before it seems. (https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4650)
