### ISSUE TITLE
1.7.10 support for Rubidium & Oculus?

### ISSUE THREAD

**Issue by ghost** [Asek3/Rubidium#207]
**I know it sounds crazy to even support such an outdated version** but nowadays, every Forge mod I've seen supports 1.7.10 besides this one.

**Comment by mnfu** [comment]
Pretty sure the lowest sodium goes to is 1.16, and this mod is a fork of sodium.

**Comment by Dathison** [comment]
And I'd say that putting effort into developing for the current versions will provide more value than developing for versions that released **eight years ago**.
