### ISSUE TITLE
Compatibility issue between rubidium-0.6.0b and waystones-forge-1.19-11.1.0

### ISSUE THREAD

**Issue by instinxx** [Asek3/Rubidium#209]
Also reported at Waystones - https://github.com/ModdingForBlockheads/Waystones/issues/590

Minecraft Version
1.19.x

Mod Loader
Forge

Mod Loader Version
41.1.0

Mod Version
waystones-forge-1.19-11.1.0

Describe the Issue
Testing mods in a single player in Creative Mode. Found a waystone generated at a village. Clicked on waystone to activate it and the game crashed.

Logs
https://paste.ee/p/aMKyi

**Comment by BlayTheNinth** [comment]
This was a race condition in Waystones unrelated to Rubidium.

**Comment by Asek3** [comment]
So, closed
