### ISSUE TITLE
Fabulous Water

### ISSUE THREAD

**Issue by WenXin20** [Asek3/Rubidium#21]
`Minecraft v1.18.1`
`Forge v39.0.59`
`Rubidium v0.4.0d`

Water does not render at all with Fabulous graphics enabled. Switching back to fast or fancy works as a temp fix.

![2022-02-03_11 41 09](https://user-images.githubusercontent.com/12000593/152398452-821a349f-bb70-449c-b019-1cc5ee2a7573.png)

**Comment by WenXin20** [comment]
I've also realized that water is not translucent when using fast or fancy graphics

**Comment by Asek3** [comment]
Ok, I will just put away Fabulous graphics mode because of this and due to other problems

**Comment by Asek3** [comment]
a7439966a50d43fe3650d0252180c0e067f4aba0
