### ISSUE TITLE
[1.16.5] rubidium 1.16.5 chunk rendering glitch with farsight

### ISSUE THREAD

**Issue by quentin452** [Asek3/Rubidium#210]
/Mods list

rubidium-1.16.5-0.2.8
farsight-1.7
NoFog-1.2.0_1.16.5-forge

/Describe the bug

When i load first time the chunk is normal , and when I turn around and go back to the chunk, there are glitch.

/Screenshot

First time i load the chunk : https://prnt.sc/wG7VGH0yfnju

Second time : https://prnt.sc/ob1Eh2UVcv-U

/Video

https://mega.nz/file/7t0gXRAB#tTsOV5Sy6SUFyN63c5ucBzDwliNLkT48RpMYC8r72TI

/Logs

[latest.log](https://github.com/Asek3/Rubidium/files/9223257/latest.log)

/Step to reproduce

1 : Make a default world
2 : use spectator mode to go faster
3 : advance a few chunks
4 : turn 180 degrees
5 : advance on the chunks already created
6 : watch glitch chunks

**Comment by Asek3** [comment]
Can't be resolved on our side.
