### ISSUE TITLE
[1.16.5]Client Crash With MEK wind_generator (Unexpected error)

### ISSUE THREAD

**Issue by OcrSu** [Asek3/Rubidium#211]
[crash-2022-07-31_06.44.18-client.txt](https://github.com/Asek3/Rubidium/files/9227705/crash-2022-07-31_06.44.18-client.txt)
Java11
![QQ图片20220731065209](https://user-images.githubusercontent.com/75876201/182002707-cc26c043-2717-49f7-a58a-ade9596392fd.png)

**Comment by Asek3** [comment]
Related to Mekanism
