### ISSUE TITLE
cc: tweaked advanced monitor

### ISSUE THREAD

**Issue by mjordan67** [Asek3/Rubidium#212]
Playing in ATM7 built a cc: tweaked computer and monitor...it works but is invisible...almost an x-ray machine.  works fine when I disable shaders.
I noticed another issue with invisible player hands etc  wonder if same issue?

**Comment by SmokePuddingEveryday** [comment]
I believe CC:Tweaked updated to add Oculus support 3 days ago

**Comment by Asek3** [comment]
So, this is Oculus issue and already fixed in CC
