### ISSUE TITLE
[ 1.16.5] rubidium is not compatible with better leaves

### ISSUE THREAD

**Issue by XiFengXF** [Asek3/Rubidium#213]
I tried to install rubidium into my modpack, and this problem occurred, and later found out that better leaves were not compatible with 
rubidium; this is the crash

[latest.log](https://github.com/Asek3/Rubidium/files/9242537/latest.log)
 
I'd really like to have better plant compatibility so I can completely replace OptiFine and get better performance, as well as fix rendering bugs with his other dimension mods; really hope you can fix this

**Comment by Lolothepro** [comment]
You launched Minecraft with Optifine and Rubidium, which are incompatible...

**Comment by XiFengXF** [comment]
I only added these 4 mods though and they still crash 
![image](https://user-images.githubusercontent.com/97110012/182584299-4abfc6cd-e03b-45cb-b137-d24d9bc3f240.png)

**Comment by Lolothepro** [comment]
Anyway Better Foliage is no longer maintained, and is not compatible with Sodium/Rubidium.

(
[latest.log](https://github.com/Asek3/Rubidium/files/9250468/latest.log)
)
