### ISSUE TITLE
[Crash] Game crashed while it installed with Just Enough Items 1.18.2

### ISSUE THREAD

**Issue by infidiotWolf** [Asek3/Rubidium#214]
Anything was fine while JEI under version 10. But, it failed to launch while i update it.
It success to launch while i remove the mod. Looks it remove some files Rubidium need.
![image](https://user-images.githubusercontent.com/96373780/182602935-06b5bb55-0fd9-4e9e-bc85-f446b3403239.png)
That i wish you can fix it, or whether i need remove it.
There is the log while it crashed.
[latest.log](https://github.com/Asek3/Rubidium/files/9251094/latest.log)

**Comment by infidiotWolf** [comment]
Java Version: 17.3.1
Game Version: 1.18.2
Forge Version: 40.1.68
Rubidium Version: 0.5.3
JEI Version: 10.1.3.238

**Comment by NonIntelligent** [comment]
Reported constantly, This is not fixed officially but **lofcz** in the comments provides a jar that fixes this problem
TeamDeusVult/MagnesiumExtras#26

**Comment by Asek3** [comment]
not related to us
