### ISSUE TITLE
Minecolonies Building renders not showing after adding Rubidium

### ISSUE THREAD

**Issue by pumkinhead456** [Asek3/Rubidium#215]
Rubidium: 0.6.0b
Minecolonies:1.0.912-ALPHA

I added Rubidium for the performance boost and it turns out that it causes Multiple issues with Minecolonies like the Building Previews not Rendering and the Nether Hut Item texture being purple and black. Rubidium didn't cause issues before in 1.18.2 but now it does with minecolonies.

**Comment by strongtaste57** [comment]
Having the same problem.

**Comment by krjencik** [comment]
me too

**Comment by Raycoms** [comment]
Minecolonies dev here, I'd guess it's because of the new forge rendering pipeline changes

**Comment by Asek3** [comment]
Fixed by https://github.com/Asek3/Rubidium/commit/ef5d989bcb4f8b6b9cccc4553fe0c4ffa576143e
Just wait for next release
