### ISSUE TITLE
No connected textures

### ISSUE THREAD

**Issue by WenXin20** [Asek3/Rubidium#22]
`Minecraft v1.18.1`
`Forge v39.0.59`
`Rubidium v0.4.0d`
[`Rechiseled v1.0.8`](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[`CTM v1.1.3+1`](https://www.curseforge.com/minecraft/mc-mods/ctm)
Pack used: [MC Connected CTM](https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm)

I've noticed with Rubidium that the connected textures system used by both Rechiseled and the CTM mod does not function with Rubidium, block textures simply do not connect.

![2022-02-03_12 30 51](https://user-images.githubusercontent.com/12000593/152406325-560f2d2d-3df8-40d1-aa79-d15419fc6a85.png)

**Comment by WenXin20** [comment]
Setting `mixin.features.chunk_rendering=false` in the `rubidium-mixins.properties` config file works as a temporary fix.

**Comment by KKotik** [comment]
That also fixing #19 
![image](https://user-images.githubusercontent.com/45950781/152609145-c21ee9aa-3b68-4c40-bc06-38b580bf1fa4.png)
But giving new issues to appear. Like animation blocks/items have non-animated texture, with animate only visable textures on.

**Comment by KKotik** [comment]
Also fixing #9 
![image](https://user-images.githubusercontent.com/45950781/152650765-7e419edd-aa21-491f-bed8-0e4df867f95c.png)

**Comment by Asek3** [comment]
> Also fixing #9
Obviously, setting `mixin.features.chunk_rendering=false` disables custom BlockRenderer's

**Comment by ShibeTemple** [comment]
> Obviously, setting mixin.features.chunk_rendering=false disables custom BlockRenderer's

I'm assuming this will reduce performance?

**Comment by novorow** [comment]
> Setting `mixin.features.chunk_rendering=false` in the `rubidium-mixins.properties` config file works as a temporary fix.

Is it possible to do this in 1.16 rubidium?

**Comment by Dr-WeiAL** [comment]
> Setting in the config file works as a temporary fix.`mixin.features.chunk_rendering=false``rubidium-mixins.properties`

This results in little fluid flow

**Comment by Dr-WeiAL** [comment]
I feel like Indium is needed to fix this, but Indium doesn't have a forge version

**Comment by Asek3** [comment]
ok as I can remember this was already fixed. Reopen issue if not and send some screenshots

**Comment by Dr-WeiAL** [comment]
> ok as I can remember this was already fixed. Reopen issue if not and send some screenshots

It worked, but not very well
![2022-06-28_16 53 56](https://user-images.githubusercontent.com/47446553/176138057-a2c3a58e-9814-42df-9eb1-32bce4c3d2dc.png)

**Comment by cqjdzy** [comment]
![2022-09-09_20 44 52](https://user-images.githubusercontent.com/91405582/189353211-f3b8cdf9-6529-40e1-a771-77a1bc145d07.png)

**Comment by Felix14-v2** [comment]
> I'm assuming this will reduce performance?

Yeah, this disables **most** of the mod. By saying "most" I mean giving up at least 80% of rendering  optimization.
