### ISSUE TITLE
1.19 straight up crashes

### ISSUE THREAD

**Issue by JoseBlackYT** [Asek3/Rubidium#221]
Hello, when launching Rubidium with Oculus and C'sWM, the game crashes with the message

**The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1**

i wish to know the issue, please

**Comment by Lucksinia** [comment]
Have the same problem here and...
I could add this peculiar line in crashlog, that I belive to be a culprit behind.
```
[16:46:25] [main/ERROR]: Mixin config rubidium.mixins.json does not specify "minVersion" property
```
Because previous version is working properly.
I hope this will help.

**Comment by Asek3** [comment]
Update Forge and Rubidium to latest versions.
