### ISSUE TITLE
[1.18.2] random crashing on servers

### ISSUE THREAD

**Issue by MayhemBill** [Asek3/Rubidium#225]
[crash-2022-08-09_17.47.14-client.txt](https://github.com/Asek3/Rubidium/files/9295145/crash-2022-08-09_17.47.14-client.txt)

as titled, crash log attached.

**Comment by EndEmpire** [comment]
Edit: Alright, so I just got another crash like MayhemBill's but fast suite mods were removed. I'm guessing it was entityculling this time, but that means Fastutils is probably not related to fast suite. Sorry about that!

I've experienced similar issues, it seems to be a conflict with fast utils (fast workbench, fast furnace, fast suite). So you might want to see if removing that fixes your issue, and if it does, choose between Asek3's optimization mods and fast utils mods.

**Comment by quentin452** [comment]
Does this issue happen in 1.16.5? with fastsuite and rubidium?

**Comment by EndEmpire** [comment]
> 

I'm afraid I can't say, try running the two together and check to see if your crash log looks somewhat similar to MayhemBill's I guess.

**Comment by Asek3** [comment]
Update to 0.5.4
