### ISSUE TITLE
[1.19]Does not correctly show the color of the backpack! (When standing on the ground)

### ISSUE THREAD

**Issue by MstDominik** [Asek3/Rubidium#227]
I'am playing with a backpack mod (Sophisticated backpacks) i've painted a backpack and i see the color in the inventory and when i put it on myself, i also see the color, but if i out the backpack on the block, my backpack becomes as if i didn't paint it and when i break it, i see particles of the color i painted. Please fix it :)
![2022-08-11_17 16 21](https://user-images.githubusercontent.com/79012563/184131827-a06f67dc-c263-44b1-b5c0-06715794b183.png)

**Comment by Asek3** [comment]
Send some screenshots plz

**Comment by MstDominik** [comment]
> Send some screenshots plz

look at this i put different colors side by side and these rainbow colors appeared
and another screenshot :)
![2022-08-11_17 24 28](https://user-images.githubusercontent.com/79012563/184132667-8a260ea8-2d03-46ec-88a8-b74889137fd0.png)

**Comment by MstDominik** [comment]
looks like gradient xD but i don't like this)

**Comment by MstDominik** [comment]
on the person as i say not have bugs)
![2022-08-11_17 28 27](https://user-images.githubusercontent.com/79012563/184133372-5d27e368-e928-48d3-b7ee-22f8d13df2e1.png)

**Comment by MstDominik** [comment]
interesting sodium have this glitch too?)

**Comment by Asek3** [comment]
Fixed in 0.6.1
