### ISSUE TITLE
[1.18.2] Conflict with "Snow Real Magic!" & weird ice issues...

### ISSUE THREAD

**Issue by Jusey1** [Asek3/Rubidium#231]
MC: 1.18.2
Forge: 40.1.0
Mod: 0.5.3a
![1](https://user-images.githubusercontent.com/61861078/184463812-d130e697-3979-419c-9858-4462bd3fd7f8.png)

On the East & South sides of snow covered slabs, the snow layer will be fighting the normal slab texture for dominance while Rubidium is installed...

![2](https://user-images.githubusercontent.com/61861078/184463857-83991551-235b-4e67-b92d-91317c6544fe.png)

While underwater below ice, you can see the chunk lines... It gets even weirder though when you start breaking ice. This issue only applied while below ice, water in general is fine.

**Comment by Asek3** [comment]
Z-Fighting should be fixed on their side by porting this commit to Forge branch https://github.com/Snownee/SnowRealMagic/commit/97a087e0a59b5d41524bded5f11f9bb565068a42
