### ISSUE TITLE
[1.18.2]Issues with mizuno's 16 craft textures

### ISSUE THREAD

**Issue by 0DeltaWaves** [Asek3/Rubidium#233]
Not sure if this is a problem with rubidium or oculus, but I've noticed that after switching from optifine, the glass textures from mizuno's don't dynamically update when placed adjacently to other glass blocks:

With optifine
![image](https://user-images.githubusercontent.com/82335536/184506942-6d7fcac9-9b72-4414-b2e5-8ad2b43a9ee8.png)

With rubidium/oculus
![image](https://user-images.githubusercontent.com/82335536/184506934-1c2db3c8-ff10-4709-8ff0-0cd2a90379ac.png)

**Comment by Asek3** [comment]
That's related to Optifine's CTM option. Rubidium is just an optimization mod
