### ISSUE TITLE
Glitch with Xaero's mods and new Forge

### ISSUE THREAD

**Issue by uhloin** [Asek3/Rubidium#234]
Minecraft 1.19.2
forge-1.19.2-43.0.8-installer.jar
rubidium-0.6.1.jar
Xaeros_Minimap_22.13.1_Forge_1.19.1.jar
XaerosWorldMap_1.26.4_Forge_1.19.1.jar

I have visual glitch: can see created in-game waypoint only at distance about 1 m and at left-top corner of screen. 
It was not such glitch for Minecraft 1.18.2, forge-1.18.2-40.1.51-installer.jar, rubidium-0.5.2a.jar

Comments from Xaero:
"Rubidum or Oculus are not compatible with the new Forge render events. Completely on their end. Make sure you're using their latest update, and if the issue still occurs, report it to them."
"Downgrading Forge won't do anything. The whole of 1.19.1 and 1.19.2 and newer 1.19 uses these new events. "
"Tell them that they break new world render Forge events. My waypoints not rendering correctly is just one of many issues this can cause."

**Comment by BrassMcCrafty** [comment]
same! glad it wasn't just me

**Comment by lucafer1** [comment]
It happens to me too!

**Comment by TheRealBrobie** [comment]
I see this was marked as completed, is there an ETA for when this fix will be published to Curseforge?
