### ISSUE TITLE
Immersive engineering invisible wires [1.18.2]

### ISSUE THREAD

**Issue by Phaserra** [Asek3/Rubidium#235]
### What happened?

I installed Rubidium and Oculus onto [ATM7 Modpack] to use shaders.

But upon loading up my save, I notice the wires from the immersive engineering mod were gone. (This would happen regardless if I had shaders toggled on/off)

I checked them by destroying the relays and indeed the wires dropped and was still doing their job (transferring power). 
But they were not visible, and was not causing damage like it did before whenever I touch the wires.

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 2080 Super with Max-Q Design

### Java Version

Java 8

### Additional context

Just to check again if it was Oculus/Rubidium I did remove the mod and the wires did re-appear again.

**Comment by cheesecakegangster** [comment]
they do cause damage for me, but they are invisible

**Comment by Lordfirespeed** [comment]
Same installation, same issue, minus Iris/Oculus. [ATM7 modpack](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) 0.4.9 with Rubidium and Rubidium extras added.
Wires never render, not even when initially placed. Probably an IE / Rubidium issue

**Comment by SmokePuddingEveryday** [comment]
> Same installation, same issue, minus Iris/Oculus. [ATM7 modpack](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) 0.4.9 with Rubidium and Rubidium extras added. Wires never render, not even when initially placed. Probably an IE / Rubidium issue

Oculus was just updated yesterday with a load of fixes, try giving it a go. I believe the issues pertaining to IE have been fixed.

**Comment by MrFastZombie** [comment]
> > Same installation, same issue, minus Iris/Oculus. [ATM7 modpack](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) 0.4.9 with Rubidium and Rubidium extras added. Wires never render, not even when initially placed. Probably an IE / Rubidium issue
> 
> Oculus was just updated yesterday with a load of fixes, try giving it a go. I believe the issues pertaining to IE have been fixed.

I've just done a test; the Oculus update has fixed other graphical issues I've had with IE but I'm also finding that the wires are still invisible. After testing an instance with just IE 8.0.2-149 & Rubidium 0.5.2a, it seems to be an issue with [Rubidium rather than Oculus](https://github.com/Asek3/Rubidium/issues/89).

**Comment by Asek3** [comment]
Related to Rubidium and already fixed.
