### ISSUE TITLE
biome blend 1 or more makes the water disappear and acts like x ray, Biome blend more than 3 crash the game.

### ISSUE THREAD

**Issue by zrovihr** [Asek3/Rubidium#241]
I have oculus but the Shader is currently off.
version: rubidium-1.16.5-0.2.8.jar

**Comment by Asek3** [comment]
Send me latest.log

**Comment by zrovihr** [comment]
here it is 
[latest.log](https://github.com/Asek3/Rubidium/files/9412884/latest.log)

**Comment by zrovihr** [comment]
![08_24_22_13_40z](https://user-images.githubusercontent.com/38888951/186330825-6a0a8509-579d-4a1c-81e8-579ee8ca6e4a.png)
here is how it looked like few seconds before crashing. this is biome blend 7. biome blend 1 also does this. 

the blocks are incorrectly generated. for example, suddenly there are cave walls everywhere but its just a render error so the block actually did not exist if I were turning the biome blend off

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
