### ISSUE TITLE
[Suggestion] Include Development Environment setup in README

### ISSUE THREAD

**Issue by paradoxuum** [Asek3/Rubidium#244]
As it stands, there are a few dependency issues with the project (see #177 and #74) that have to be solved manually. Including a simple guide in the README regarding setting up a development environment would solve this, and hopefully allow more developers to contribute to the project and fix bugs.

For now, the following has to be done to solve these issues;
- use `modCompileOnly` instead of `compileOnly` for dependencies
- include Oculus as a dependency with `modCompileOnly` to fix the error in `ChunkRenderRebuildTask`

**Comment by Asek3** [comment]
Was fixed by https://github.com/Asek3/Rubidium/pull/407
