### ISSUE TITLE
[1.18.2]FPS reduction when I open gui

### ISSUE THREAD

**Issue by Rikka-Lyn** [Asek3/Rubidium#245]
version:
minecraft 1.18.2
rubidium 0.5.3a
silentgear 2.10.10

I used rubidium in my modpack,when I open any gui,my fps will reduce a little(like from 120fps to 105fps)
If I open any gui include something made by silent gear,my fps will reduce a lot(e.g.If I hold a crosssbow made by silent gear,my fps will decreased from 120fps to 15fps,and the colourful parts on the gear disappeared).
I can't stop this from happening and I think this caused by rubidium,is there any way to solve this or it is a bug?

**Comment by Asek3** [comment]
Is this issue happens on vanilla?

**Comment by Asek3** [comment]
so i guess it's related to https://github.com/Asek3/Rubidium/issues/48
