### ISSUE TITLE
1.18.2 Crash when entering nether

### ISSUE THREAD

**Issue by GrizzBear01** [Asek3/Rubidium#246]
Forge 40.1.73
Minecraft 1.18.2
Rubidium 0.5.3a + Rubidium Extras 1.3.2

Recently added Rubidium to improve performance, upon entering the nether for the first time in a session the area renders for a couple seconds and then crashes game, Once returning to menu  with not enough crashes and reloading world player can leave and re-enter the nether without crashing. Not Enough Crashes suggests it could be Rubidium.

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513

Not very good at reading crash reports so apologies if Rubidium not resonsible
[crash-2022-08-06_12.20.27-client.txt](https://github.com/Asek3/Rubidium/files/9389006/crash-2022-08-06_12.20.27-client.txt)

**Comment by Asek3** [comment]
There are no Rubidium on client in crash-report

**Comment by paradoxuum** [comment]
This is an OptiFine issue. The latest preview version of OptiFine 1.18.2 fixes this.

**Comment by quentin452** [comment]
> This is an OptiFine issue. The latest preview version of OptiFine 1.18.2 fixes this.

hum rubidium is incompatible with optifine

**Comment by paradoxuum** [comment]
> > This is an OptiFine issue. The latest preview version of OptiFine 1.18.2 fixes this.
> 
> hum rubidium is incompatible with optifine

The crash mentioned here is caused by OptiFine. Rubidium was not installed.

**Comment by Asek3** [comment]
So, closed if it's unrelated to Rubidium
