### ISSUE TITLE
[1.16.5] rubidium-0.2.10 crash when i entering in worlds with magnesium/rubidium extra installed

### ISSUE THREAD

**Issue by quentin452** [Asek3/Rubidium#251]
rubidium 0.2.10 make crash with magnesium/rubidium extra installed , when i use rubidium 0.2.9 with magnesium/rubidium extra not make crash

Forge version : 36.2.39
minecraft version : 1.16.5
mods list : 
rubidium 0.2.10
magnesium_extras-mc1.16.5_v1.3.1

steps to reproduce : 

1 : make a world
2 : watch crash

crash report : [crash-2022-08-25_00.34.19-client.txt](https://github.com/Asek3/Rubidium/files/9419850/crash-2022-08-25_00.34.19-client.txt)
logs :[latest.log](https://github.com/Asek3/Rubidium/files/9419849/latest.log)

**Comment by Asek3** [comment]
That is not related to us. Report to magnesium/rubidium extra devs

**Comment by quentin452** [comment]
fixed in v1.4.0 1.16.5 magnesium extra
