### ISSUE TITLE
[1.16.5] Wrong locations of rendered textures

### ISSUE THREAD

**Issue by monroth** [Asek3/Rubidium#258]
MC 1.16.5
Forge 36.2.31
Curse modpack ATMS

When i start this modpack with Rubidium, some textures are missing (i can see internals of house through walls, internals of some caves through "holes in grass textures", etc), and some textures are here despite there is no corresponding object (seawead midair that does not exist and can't be seen without rubidium, textures of some sides of nonexistent blocks, etc). I suppose that it renders all textures and just places them in wrong spots, but i'm not sure. Anyway, after 1-5 minutes of running Minecraft client crashes with this message 
![image](https://user-images.githubusercontent.com/28282020/187086952-bf32cf9a-5398-41ef-9032-47693373cd60.png)
log of last crashed session
[latest.log](https://github.com/Asek3/Rubidium/files/9440146/latest.log)

same issues was with magnesium and on other laptop with linux and integrated graphics

**Comment by zrovihr** [comment]
I had this bug too I think. for now try to set Biome blend to 0 and see if it helps.
https://github.com/Asek3/Rubidium/issues/241 
also if you have BetterEnd, update it to this because it has Magnesium Compat https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

**Comment by Asek3** [comment]
Answer was given
