### ISSUE TITLE
Crashes during load with better foliage mod

### ISSUE THREAD

**Issue by marcell123455** [Asek3/Rubidium#260]
MC 1.16.5 crashes during startup with Rubidium 1.16.5-0.2.10 and the Better Foliage mod.

after removing better foliage it worked.

Pleas check out the crashlog.
[crash-2022-08-29_17.24.50-client.txt](https://github.com/Asek3/Rubidium/files/9445885/crash-2022-08-29_17.24.50-client.txt)

**Comment by Lolothepro** [comment]
#213
