### ISSUE TITLE
Minecolonies + Rubidium 1.19.2 Supply Camp Render Issue

### ISSUE THREAD

**Issue by SHXRKIEgg** [Asek3/Rubidium#265]
Hi, Rubidium is making Minecolonies Supply Camp Render not showing possibly due to the new forge rendering pipeline changes.

Thanks you.

**Comment by quentin452** [comment]
duplicate issue #215

**Comment by Asek3** [comment]
Fixed by https://github.com/Asek3/Rubidium/commit/ef5d989bcb4f8b6b9cccc4553fe0c4ffa576143e
Just wait for next release
