### ISSUE TITLE
Not respecting resolution settings and lack of resolution slider

### ISSUE THREAD

**Issue by Rimevel** [Asek3/Rubidium#267]
### Problem
When using Rubidium on forge the resolution settings are not shown in the config menu, and borderless mode always use resolution relative to screen resolution set in the OS. Even in fullscreen it will use screen resolution.

If I disable Rubidium and set the resolution in the regular video options, it still resets back to screen resolution after a while.

### Expected behaviour
When running Sodium on fabric, there is a slider for resolution, fullscreen have the configured resolution, and resolution in borderless mode is relative to the fullscreen resolution.

This saves a TON of performance on weaker computers without having to run in fullscreen.

### Mod Version
Rubidium 0.5.3a

### Game Version
1.18.2

### Hardware & OS
Mac, OS X

**Comment by misaki1301** [comment]
this issue still present in sodium originally, so I'd suggest to post this on it own repo of sodium

**Comment by Rimevel** [comment]
Hmm, when I use sodium on fabric there is a resolution slider. Maybe it is something they added quite recently.

**Comment by Rimevel** [comment]
Nvm, just found out I can use "shift+p" in the rubidium settings screen to get to the resolution settings. Having another issue now in borderless fullscreen but that has nothing to do with this issue, so closing this.
