### ISSUE TITLE
[1.18.2] Server crashes on startup

### ISSUE THREAD

**Issue by V972** [Asek3/Rubidium#269]
Forge: 40.1.76
Java: 17.0.4.1
Rubidium: 0.5.3a

Clean server with just Rubidium (so not even with any other mods) crashes on startup.
[debug.log](https://github.com/Asek3/Rubidium/files/9497296/debug.log)

Console output: https://hastebin.com/jikelahawi

Do I need to send something else?

**Comment by Legendile7** [comment]
Rubidium isn't working with NoCubes

**Comment by quentin452** [comment]
rubidium is client side

**Comment by V972** [comment]
...oh.
