### ISSUE TITLE
Incompatibility with Effective (forge)

### ISSUE THREAD

**Issue by Matthysse** [Asek3/Rubidium#27]
Hello!
There is a problem with this mod and Effective (forge) (https://www.curseforge.com/minecraft/mc-mods/effective-forge) : the waterfall effects (sound and particles) don't show when Rubidium is installed.

**Comment by KKotik** [comment]
Strange, totally working for me. Can you also check in clear instance to make sure this is the only mods that causing that issue?

**Comment by Matthysse** [comment]
Issue is visible on a clean instance: (latest forge version (.75):
Without Rubidium:
![2022-02-09_12 04 18](https://user-images.githubusercontent.com/32510957/153186704-c7c60939-80dc-4ba6-90c5-036cff660845.png)
With Rubidium:
![2022-02-09_11 55 30](https://user-images.githubusercontent.com/32510957/153186726-876198aa-619f-4acf-866d-a4f30a99c183.png)

**Comment by KKotik** [comment]
Oh yeah. Just tested, seems to happen for me too.

**Comment by Asek3** [comment]
Related to their side. Issue seems to get PR with fix finally https://github.com/bottomtextdanny/Effective-Forge-/pull/34
