### ISSUE TITLE
Unexpected error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65537 (Yet another ArrayIndexOutOfBoundsException again...)

### ISSUE THREAD

**Issue by Coraline774477** [Asek3/Rubidium#270]
Minecraft: 1.18.2
Forge: 40.1.76
Rubidium: 0.5.3a

Crash Report: https://gist.github.com/Coraline774477/efb36c98f09f8c7bc8dbc7efbbefeb4a

Log: https://gist.github.com/Coraline774477/e034cdf817a0a7fb32a8c44842fff1d9

Man Rubidium just can't catch a break from these "_ArrayIndexOutOfBounds_" exceptions....
Like com'on man! Fix your array errors that's causing these index out of bounds exceptions already......

I'm about to start heading back to OptiFine for the time being until you FINALLY fix all (and I mean ALL) of your array errors that's causing these exceptions and I do NOT want to have to use OptiFine ever again but if these errors arn't ever going to get fixed then I guess I'll just have to continue to use the worlds worst performance mod to have ever exist for minecraft since I'm getting sick and tired of having my game randomly crash due to Rubidium's bs, at least OptiFine doesn't cause these types of exceptions BUT I do NOT want to have to put up to OptiFine's own bs either!......

BTW I had made a report to Dynamic Trees (1.18.2) about one of these array index out of bounds exceptions thinkin that Dynamic Trees was apart of that crash I had that was obviously caused by Rubidium as well a few days ago which I had to make a new world after I had uninstalled Dynamic Trees, hoping that I don't crash again BUT I crash from Rubidium yet again!......

**Comment by Coraline774477** [comment]
> "_I'm about to start heading back to OptiFine for the time being until you FINALLY fix all (and I mean ALL) of your array errors that's causing these exceptions and I do NOT want to have to use OptiFine ever again but if these errors arn't ever going to get fixed then I guess I'll just have to continue to use the worlds worst performance mod to have ever exist for minecraft since I'm getting sick and tired of having my game randomly crash due to Rubidium's bs, at least OptiFine doesn't cause these types of exceptions BUT I do NOT want to have to put up to OptiFine's own bs either!......_"

I'm sorry for that response, It's just that I'm so tired of Minecraft randomly crashing from Rubidium in 1.18.2 and I don't want to continue to use OptiFine especially since OptiFine is a really old optimization mod which it's not looking so good after all of these years and I don't think that it's getting any better, infact OptiFine is possibly getting worse since the devs aren't exactly listening to their community to actually make it better.

Also I was tired that day since I had been playin modded minecraft for too long that day and had been awake for too long so my mind might've not been in the brightest of places at the time and the fact that I really, really, really wanted to play with Dynamic Trees again in 1.18.2 since the last time I tried to play with that mod with OptiFine in 1.16.5 which what made me stop with Dynamic Trees 1.16.5 in the first place was some OpenGL error that occurred whenever I entered a roofed forest biome since OptiFine 1.16.5 was the worst version of the mod to have ever existed for Minecraft.

There's no other mod like OptiFine or Rubidium that actually improves the game's overall performance on a not so good computer while my financial situation ain't lookin so hot right now or else I would've upgraded to a much, much better PC a long time ago so that I wouldn't have to keep complaining about how bad my PC's specs really are and battling with my own PC as well so that I wouldn't really need mods like OptiFine at all but that's not the world we/I live in sadly.

So could you please fix Rubidium's arrays* for 1.18.2 @Asek3? Please.

*TBH I don't really know what's actually wrong with Rubidium 1.18.2 since I'm not a coder nor a mod creator so I'm basically guessing what might be wrong with Rubidium since I'm trying to help you out with the issue instead of not getting the issue resolved at all so that I nor anybody else would have random crashes caused by Rubidium anymore.

(BTW I've just downloaded Rubidium 0.6.2 but I'm currently going to be on 1.18.2 till this Wednesday then I'll be on 1.19.2.)

**Comment by coderepo8593** [comment]
One of the things about Sodium which Rubidium is a port of, is that since it is a rendering engine, its code is being called for a large portion of the game loop, and a large portion of the interactions that occur in the gameworld rely on its code. Because of this, it makes it much more likely that you will see Sodium/Rubidium referenced in a log for which it has only a little or possibly nothing to do with the actual cause of the error. In fact, many times code changes will be made to compensate for other mod authors writing poor code or using hacky code.

In this case, it's unclear what the actual cause of the problem is. I noticed Offhand Combat was involved in a call lower in the callstack, so it could actually be involved.

Lastly, you should consider the impetus and imposition you place on other people. Other people can be very kind and decent to you, if you are willing to let them based upon how you treat them. No one here is your personal assistant, and we are all complete strangers to you. So the only thing we have to go by as to how you will treat others, is what you type in that text box. 

You sound very pushy, imposing, and have fully centered the conversation around what you want, your demands, and your ego.

Please understand I myself am not trying to be difficult, rude, or insult you in any way. I want to provide you a mirror with which to look and see how you appear to others. Well at least, the one person that is me.

**Comment by Coraline774477** [comment]
"I noticed Offhand Combat was involved in a call lower in the callstack, so it could actually be involved."

I've noticed that as well, at the start of every log for every game session that first is Rubidium's mixins.json isn't properly specifying "minVersion" and then OffHandCombat's two mixins (common.mixins and mixins) doesn't specify "minVersion" properly. So maybe that's what's contributing to this problem is that both Rubidium and OffHandCombat aren't specifying their minVersion properly, so I'll have to go report that over to the author of OffHandCombat about that which I do believe that OffHandCombat's mixins has been doing that for quite some time now and now to come to think about it that's starting to annoy me, so now what's annoying me is whenever a mod's mixins aren't properly specifying the minVersion when they should which why they're not is possibly cause the author hasn't updated their minVersion for quite awhile and needs to update their minVersion for their mixins.

"Please understand I myself am not trying to be difficult, rude, or insult you in any way. I want to provide you a mirror with which to look and see how you appear to others. Well at least, the one person that is me."

I always "look" at myself in the mirror and what I see is a person who's a selfish, self-centered, thinkin that bigger is better when it comes to food and drink, really lazy, pretty much no muscle at all, sorta looks like a living skeleton, doesn't go outside at all, thinks that everything outside is too boring, reeks really badly, no sense of hygiene, lowlife, piece of trash, motherf*&%er who thinks that they're special being the only human being in the while damn world who's a natural redhead aries clamin to be extra fiery than a regular redhead or aries thinkin like a warrior when that's totally not the case who's got Autism and was bullied at home which that home is a crappy apartment complex which is home for the last twenty plus years while always having thoughts about the world possibly coming to an end as of the fall of civilization as we've known it.

Yeah, I'm all of that, am I proud of being who I am both online and offline? Hell no I'm not! Sometimes I wish I wasn't born in this terrible, cruel world that we all live in which is sorta going to end soon.
Sometimes in my mind I wish that I was dead and probably in hell since I haven't been contributing to our "corrupted" society or even if our society wasn't corrupted I'm still not really contributing to society by getting employment and whatnot to prove my worth of going to heaven when my time comes, also I've not been paying attention to what's really going on in our world since I'm so tired of it all that I just want our world to come to an end already so that we nor I wouldn't have to suffer anymore!...

I know that nobody's insulting me, being rude to me or anything but whenever someone either online like on here or offline such as a family member says stuff like what you've said or something similar then I would actually insult myself by burning myself like this while kind of wishing for my own self destruction so that I dont cause any heated arguments or make more enemies which I've already made enough enemies as is since I'm full of rage that I seriously don't want to let loose which anger and violence never solves anything but causes more problems, also cause the governments have made me this way which I don't like being the way I am and I try so hard to actually change for the better and it's like I'm refusing to change. 
I'm down in my own rabbit hole which I'm still trying to figure out how to get myself out of which it's not really going to well.

I always place myself in someone else's shoes which is why I'm the way I am as well as always havin negative thoughts going around in my head which the most negativity is all of the doomsday stuff that my eldest brother tells me as well as seeing the signs of what's really happening in the world which right now how our world looks like is grim, really grim which is why I'm tryin so hard to tune all of that out with minecraft, my favorite youtubers on YouTube as well as with friends, family and my future wife but in the end my depression and dark thoughts are going to get me and end me, it's either that or WW3 with China and Russia taking out the US with nukes....

I'm going to stop talkin now and I'm just going to leave all of this alone since I ain't gettin the main problem solved by talkin trash about myself, our own world, and Rubidium.

I guess that whenever Rubidium is causing random crashes I'll just have to suck it up and continue to use Rubidium or suck it up and continue to use OptiFine or else I'll have to just stick with vanilla since Minecraft's overall performance is still going to be trash forever no matter what Mojang does to improve the game's overall performance which is cause of what Notch used to make the game and the fact that making the game literally be it's own engine isn't the brightest of ideas performance wise...

**Comment by Saereth** [comment]
Fwiw this is pretty common unfortunately, and although it may certainly relate to other mods there are plenty of stack trace/crash reports here that contain no other mods in the stacktrace (https://paste.ee/p/B7dBt) for example. I'd really love to include the mod in our upcomming FTB pack but to be frank people crashing once or twice per day across thousands of users I'm afraid would reflect poorly on me knowingly releasing a pack with this in at despite my desire to. This is a real issue but I do understand it's complicated. Certainly the initial tone and frustration of this post was not warranted towards people devoting their free time to work on this project though, best of  luck to all of you involved on this and your time is definitely appreciated.

**Comment by coderepo8593** [comment]
> Fwiw this is pretty common unfortunately, and although it may certainly relate to other mods there are plenty of stack trace/crash reports here that contain no other mods in the stacktrace (https://paste.ee/p/B7dBt) for example. I'd really love to include the mod in our upcomming FTB pack but to be frank people crashing once or twice per day across thousands of users I'm afraid would reflect poorly on me knowingly releasing a pack with this in at despite my desire to. This is a real issue but I do understand it's complicated. Certainly the initial tone and frustration of this post was not warranted towards people devoting their free time to work on this project though, best of luck to all of you involved on this and your time is definitely appreciated.

Do you think it is significant though that the call that precedes the gamerender call has a lot of render mixins from various mods? It even has flywheel, which is compatible, but you can't tell me that isn't interacting with the rendering call. These are going to be affecting the input parameters of the call and other state variables that are then used for rendering. I noticed this one has immersive engineering and ars nouveau in common with the Error that Coraline has reported in this issue.

Perhaps something is going on with Immersive Engineering here, as I see that is common to the log you posted and Coraline's log.

EDIT: I should also mention there is a very large modpack that is using Rubidium + some of the other Jellysquid ports without issue. It's a massive modpack with a huge userbase too, Medieval MC. I think this show that as long as you play with mods that have compatible render mixins, it will be stable.

**Comment by Saereth** [comment]
Yeah of course its relevant, I spoke only to the stack trace in that particular example though. When mixins are involved it's undeniably more difficult to pinpoint an issue. This is the type of discussion we hope for though, lots of us appreciate the mod and are willing to help troubleshoot and test to pin down the cause. I'll try without IE and see if I can reproduce it!

**Comment by coderepo8593** [comment]
I also noticed that you had EnhancedVisuals in there too. That could be contributing to the problem. I saw that quite a few things have to be turned off to get it to work with Optifine. That mod of all of them, next to flywheel, is going to be interacting with rendering the most.

**Comment by Saereth** [comment]
Enhanced visuals was a recent addition so while it may bring its own issues I dont think that's the only cause here (we were getting the crashes before adding it), will yank it out as well while trying to pin things down

**Comment by Saereth** [comment]
So I took immersive out and didnt get the crash for a while, after putting it back in I got the crash again and the immersive compat is in the stack trace specifically https://hastebin.com/ebezicidug.rb

Where do we go from here though, is this something we need to see if the IE dev would help with? I know modders aren't always friendly towards shaders unfortunately

**Comment by coderepo8593** [comment]
> So I took immersive out and didnt get the crash for a while, after putting it back in I got the crash again and the immersive compat is in the stack trace specifically https://hastebin.com/ebezicidug.rb
> 
> Where do we go from here though, is this something we need to see if the IE dev would help with? I know modders aren't always friendly towards shaders unfortunately

Thanks for tracking this down. It really depends on what is going on and how difficult it would be to fix. The best thing to do right now is to create an issue with Immersive Engineering to let the devs over there know. It's possible it is an area of the code they are already aware needs some improvement and just haven't gotten to it yet.

I think the popularity of Rubidium and the desire of many in the community to not have to rely upon the alternative which is closed source and not very community or developer friendly will likely be enough for people to be willing to spend time to fix it.F

@Coraline774477 would you Edit the title of this issue to indicate Immersive Engineering is incompatible with Rubidium?

**Comment by Coraline774477** [comment]
I do not have I.E installed or Ars Nouveau in my 1.18.2 mod lists as well as my 1.19.2 mods lists, BUT I do have their configuration file in my config folder but the versions of both mods config files and the mods that I have in my versions folder are pretty old by now since its been a while since the last time I played with I.E and I don't remember if I even have Ars Nouveau, if Ars was in an old version of Hexxit Updated 1.12.2 then I can see Ars being in there but it's not in there in Hexxit Updated New Year Edition 1.8.1.

Btw since yall have mentioned about some mods that use mixins for rendering purposes, I'm thinking that what caused the last crash I had with Rubidium 1.18.2 is possibly being caused by one or more of the mods in my 1.18.2 mod lists BUT I don't know which ones are the corporates that are causing Rubidium to crash.

To be perfectly frank I don't really feel like going through all three of my 1.18.2 mod lists that's for my three 1.18.2 modded worlds to find out which mods are causing this problem with Rubidium especially since I'm currently playing on 1.12.2...

Also I'm currently playing 1.12.2 mainly for The Betweenlands (for the third time retrying it, 
I have its rendering system turned off since T.B.L's built in shaders hinders my overall performance of my game since my PC's specs are total garbage...), and Advent of Ascension.

I had tried multiple times to get V.M.W (Vic's Modern Warfare: Contagion 2.0) to work but it crashs the game every time I look at its items in JEI which started from HadEnoughItems (HEI) and I've decided to pretty much never play with V.M.W ever again since it's pretty much a dead mod by now...

Also Hexxit Updated has a total of 91 mods (includes core/lib and performance mods) but I butchered the pack as of taking out the mods that I didn't want and inserted mods that I have and wanted to play with, before I added the mods that I wanted to play with I had to cut the modpack in half and then put the ones that I wanted but then for performance reasons I took out 20 or so mods (including some performance mods which one of them was causing some framerate issues which idk why the pack originally has Performant and Philosopher with FoamFix and the new performance mod CensoredASM which replaced VanillaFix...).

But the only way that I could gain access to the pack's mods folder was to launch the pack for the game to generate it's mods folder to gain access to its mods list, I can tell ya that it was faster for me to build my current 1.12.2 personal modpack from an existing one that I have played before rather than just searching for them all in my versions folder which I store old mods for old minecraft versions such as 1.12.2 so that my desktop screen wouldn't be too cluttered with different folders for multiple  minecraft worlds that are for different versions of minecraft.

Which as time goes on some of those old mods would have updates which the pack maker for Hexxit Updated had updated all of the mods that I'm currently playing with except for JEI since I already have the latest version of JEI 1.12.2. BTW my 1.12.2 mod list doesn't have I.E, Ars Nouveau or Enhanced Visuals but I do have ItemPhysic which I have ItemPhysic for 1.12.2, 1.18.2 and 1.19.2.

So could ItemPhysic (either the lite version or its full version) be causing Rubidium to malfunction and crash?

Why I'm mentioning ItemPhysic is 'cause Enhanced Visuals was made by the same author that made ItemPhysic as well as both mods use CreativeCore, also ItemPhysic does some rendering for the items when you throw items onto the ground or items fall onto the ground.

**Comment by coderepo8593** [comment]
I got your mod list confused with another recent issue someone else posted that had IE in it. I don't believe Ars Nouveau is causing any crashes. I have used it quite a bit in 1.16.5 and not received a crash.

For the log that you posted, I think the problem was most likely something with Offhand Combat.

The problem with adding your own mods to a modpack is that all the well known modpacks spend weeks if not months carefully testing, configuring, and balancing the mods that are in the modpack. By adding your own, you could very well be adding mods that the modpack authors themselves purposefully left out or removed during their testing. One of the biggest reasons certain mods will be removed is due to TPS lag issues.

**Comment by Saereth** [comment]
we're still having these issues as well with the ie removal, so far we've removed IE, enhanced visuals, and scannable and stil having the crashes so unfortunately just removing IE wasn't the solution. 

even fewer mixins:
https://hastebin.com/ayatevirel.properties

**Comment by Asek3** [comment]
Update to 0.5.4

**Comment by Coraline774477** [comment]
Why OffHandCombat is possibly showing up at the top of every log for 1.18.2 (and possibly 1.19.2 if it's been ported to that version) (as "_does not specify "minVersion" property_")  is 'cause the author for that mod hasn't updated their mixins lately?

UPDATE: Actually why OffHandCombat keeps showing up at the top of the log (same with the console I believe) is possibly because of how the mod was made/created.
Just like how Rubidium was made since Rubidium is a fork of Sodium which Sodium was possibly made poorly to try to improve performance on fabric and Rubidium being a fork of Sodium unfortunately has similar traits as Sodium as of how it was made/created which forge doesn't like poorly made mods apparently...
For Rubidium's issue with it's "MinVersion property" can't be fixed sadly since it's a fork of Sodium but OffHandCombat's "MinVersion property" can be fixed by it's creator when the mod's author improves their skill in mod making overtime.
I've already made a report about that issue in O.H.C (OffHandCombat) but haven't checked up on the report yet but I'm checking up on it now.

Btw THANK YOU @Asek3, FTB and Sodium teams for fixing the ArrayIndexOutOfBoundsExeption that was pledging us players for what felt like forever on 1.18.2!
Thankfully hasn't been happening in 1.19.2 but maybe apply the fix on 1.19.2 as well?

**Comment by Coraline774477** [comment]
I've encountered yet another array index out of bounds exeption but this time it's java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385 from 1.19.2...
So "_java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65537_" for 1.18.2 has been fixed but that one was for 1.18.2, "_Index -1 out of bounds for length 16385_" is coming from 1.19.2 as of my latest mod list...

Somebody commented in another report with the same issue (https://github.com/Asek3/Rubidium/issues/289) is saying that it's a incompatibility with another mod involving around world generation/chunk generation such as modded blocks, entities, or effects/attributes, so the incompatibility might be coming from mods that adds stuff such as modded blocks, entities and/or effects/attributes...

The last issue that was fixed " _java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65537_" was possibly similar to "_java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385_".
I've said in my last comment "_Thankfully hasn't been happening in 1.19.2 but maybe apply the fix on 1.19.2 as well_?" and now I think that you (@Asek3) should also apply a similar fix to "_java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385_"?
