### ISSUE TITLE
Xnet texture bug

### ISSUE THREAD

**Issue by bypgomes** [Asek3/Rubidium#275]
![Screenshot_1](https://user-images.githubusercontent.com/29603439/190423345-b657438c-9cb1-414b-a401-354c737148aa.png)
Whenever active I have this error with the Xnet mod.
Game: 1.18.2
Version: Rubidium mc1.18.2-0.5.3a
Modpack: ATM7

**Comment by Asek3** [comment]
Should be fixed on new versions
