### ISSUE TITLE
Game crashes whenever I join a server on All The Mods 7

### ISSUE THREAD

**Issue by Brown-Michael** [Asek3/Rubidium#28]
[latest.log](https://github.com/Asek3/Rubidium/files/8051207/latest.log)

![image](https://user-images.githubusercontent.com/83581650/153670735-51dcc444-2d96-4457-88f6-98f5fa4bf3b1.png)

My Java is up to date, server works fine and other people are using Rubidium and it works fine for them.

**Comment by Atlantispy** [comment]
This looks like you've used some JVM arguments that aren't working

**Comment by Asek3** [comment]
Try on 0.5.0
