### ISSUE TITLE
Request: port Rubidium to version 1.12.2.

### ISSUE THREAD

**Issue by RodrigoTR04** [Asek3/Rubidium#283]
This is a request and not an issue, feel free to close this if it is not the appropriate place (I couldn't find anywhere else to ask/request).

Although Rubidium supports older versions like 1.16.5 it does not do 1.12.2 which is an important version because many big modpacks are stuck there and the only option is OptiFine which is sketchy at best when it comes to compatibility, specially with many other mods being run at the same time. Many of the great Feed The Beast packs rely on that version specifically for example. My ask is for Rubidium to be backported to version 1.12.2 so it increases performance with modded Minecraft.

**Comment by Asek3** [comment]
Use https://www.curseforge.com/minecraft/mc-mods/nothirium
