### ISSUE TITLE
"Always Defer Chunk Updates"  Parity for Sodium

### ISSUE THREAD

**Issue by userriot** [Asek3/Rubidium#288]
Basically just wondering if you could add the feature.
I've recently been playing Vault Hunters and tend to get block update lag or chunk update lag. I've had the same problem on fabric and using that option fixed it, perhaps it could be added to rubidium?

**Comment by quentin452** [comment]
do you use 1.16.5? , in 1.16.5 rubidium is "Use chunk multi-draw" and higher version of rubidium is "Always defer chunk update" like sodium

**Comment by embeddedt** [comment]
This was backported in https://github.com/Asek3/Rubidium/pull/384.
