### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ShibeTemple** [Asek3/Rubidium#29]
Hello! 

Versions:
```
Forge 39.0.79
Rubidium 0.5.0 rubidium-0.5.0.jar
```

Mod list:
```
Configured - configured-1.5.3-1.18.1.jar
Controlling - Controlling-forge-1.18.1-9.0+15.jar
FPS Monitor (provides FPS text when not in F3) - FPS-Monitor-1.18-1.0.2.jar
JEI - jei-1.18.1-9.2.1.69.jar
Starlight 1.0.1 - starlight-1.0.1+forge.36a1c6c.jar
```

Hello! There is a slight increase in framerate (40 or so), however, there are significantly more stutters. Additionally, the framerate increase is less than what native Sodium or Magnesium provides. Not sure if everything is running properly. RAM usage and framerate are better on Rubidium, but stutters undermine these increases.

Tests are provided below:

VANILLA: 

![2022-02-20_11 02 20](https://user-images.githubusercontent.com/6219801/154862740-df9d49e7-11b6-4155-ac80-4fb7d023aa52.png)
![2022-02-20_11 03 26](https://user-images.githubusercontent.com/6219801/154862752-9771954c-b9d4-4271-abe4-4b366db4aace.png)
360 test/viewport movement
![2022-02-20_11 04 49](https://user-images.githubusercontent.com/6219801/154862785-e3c14023-59a0-4d8c-8a56-c4b37177796d.png)

Rubidium + Starlight:

![2022-02-20_13 07 03](https://user-images.githubusercontent.com/6219801/154864947-3d708073-dcca-4ce6-a870-2b0883971e3c.png)
![2022-02-20_13 16 53](https://user-images.githubusercontent.com/6219801/154864960-29d86c91-f7ea-44f1-9a34-d2d69ae65d91.png)
![2022-02-20_13 19 50](https://user-images.githubusercontent.com/6219801/154864971-e6496fa1-9ca8-4f8a-8c7d-685008483e67.png)
^^ the jump in the frametime graph is consistent. Every few seconds the same jump occurs. This is also not related to Java VM GC.
360 test:
![2022-02-20_13 19 54](https://user-images.githubusercontent.com/6219801/154865006-eae025da-74d9-4e04-8149-c51c5fd782c0.png)

**Comment by SzczurekYT** [comment]
Yeah, Rubidium has overall worse performance compared to magnesium. On magnesium I'm getting around 110 fps while on Rubidium around 60 fps.
Sill cool.

**Comment by Atlantispy** [comment]
I've been doing some testing today, as I get significant stutters with Rubidium. Overall I still get a performance increase so it's worth it, but would like to fix it up if I can.

I did these two:

https://spark.lucko.me/fC5WyawNYG

https://spark.lucko.me/HeeHABH3pi

Apparently when I remove Rubidium the tile entity issues are gone, specifically it's sign text causing issues from what I can see?

@Asek3

**Comment by Atlantispy** [comment]
https://spark.lucko.me/J4xnwXC2Wo

Additionally seems to be quite a performance hit when weather events are happening in the sky

**Comment by ShibeTemple** [comment]
The Sodium 5.0 rendering engine port seems to be performing much much better. However, it is currently only for version 1.18.2. @Asek3 are you planning on backporting support for the latest 1.18.2 version to 1.18.1? Aren't most of the changes between these versions related to structures? Might be an easy thing to add support for.

**Comment by Asek3** [comment]
1.18.1 is not supported anymore

**Comment by Asek3** [comment]
Soo.. I am waiting for 0.5.0 Sodium to make port for 1.18.2 and 1.19.x Forge. For now we can just wait
