### ISSUE TITLE
Game Crash with Create Mode 1.19.2 version

### ISSUE THREAD

**Issue by RedBeast1959** [Asek3/Rubidium#291]
Whenever placing cogwheel or watermill, game immediately crashed. According to Not Enough Crash mod report, Current 1.19.2 version of Create mod has some conflict with Both Rubidium and Oculus just like Immersive Enginnering mod.

Forge 43.1.27
rubidium-0.6.2
oculus-mc1.19.2-1.2.8
create-1.19.2-0.5.0.e

[crash-2022-09-26_23.21.31-client.txt](https://github.com/Asek3/Rubidium/files/9647088/crash-2022-09-26_23.21.31-client.txt)
[latest.log](https://github.com/Asek3/Rubidium/files/9647089/latest.log)

**Comment by coderepo8593** [comment]
There has been talk in the Rubidium Discord that the Create team is currently working on a fix for the compatibility issues between flywheel and Rubidium.

**Comment by Asek3** [comment]
Update Create to https://www.curseforge.com/minecraft/mc-mods/create/files/4011414
