### ISSUE TITLE
Rubidium simply doesn't load some chunks

### ISSUE THREAD

**Issue by Kayzinho** [Asek3/Rubidium#293]
I've created a new world with the following mods:

-Create
-Rubidium
-Dynamic lights

World seed: 637184628307790

So i went to the village and saw this:

![image](https://user-images.githubusercontent.com/102255682/192555255-100f370b-4296-4b92-83ed-d1808d60554c.png)
![image](https://user-images.githubusercontent.com/102255682/192555292-582fa779-62f4-4900-905a-ca27d1071063.png)
![image](https://user-images.githubusercontent.com/102255682/192555332-cf22be82-ec3b-4469-8388-b66f0e5b80d7.png)

I tried to remove Rubidium and the chunks loaded normally, same thing happens if i remove Create instead of Rubidium. How can i fix this?

Edit: Nvm, i found a way to fix this. Using the command "/flywheel backend instancing" or "/flywheel backend batching" seems to fix the problem.

**Comment by murao-kun** [comment]
This is flywheel issue that will be fix in next create release.

**Comment by Asek3** [comment]
Update Create to https://www.curseforge.com/minecraft/mc-mods/create/files/4011414
