### ISSUE TITLE
1.16.5 Game gets stuck on loading while launching Critical problem: rubidium.mixins.json:core.compat.MixinModList target net.minecraftforge.fml.ModList was loaded too early.

### ISSUE THREAD

**Issue by bravoso** [Asek3/Rubidium#294]
[latest.log](https://github.com/Asek3/Rubidium/files/9661072/latest.log)

i've no idea what is causing this issue. Any clue?

**Comment by coderepo8593** [comment]
Most likely you have a corrupt installation or bad config file somewhere. I would suggest using GDLauncher to create a new instance, which will ensure a clean install.

**Comment by CatastropheChou** [comment]
May you share your mods list please?
I do have this problem too.
