### ISSUE TITLE
[1.18.2] Rendering Bug with Corundum from Quark and Stained Glass

### ISSUE THREAD

**Issue by KazuMurako** [Asek3/Rubidium#295]
Forge Version: 40.1.68
Quark Version: Quark-3.2-358.jar
AutoRegLib Version: AutoRegLib-1.7-53.jar
Rubidium Version: rubidium-0.5.3a.jar

When Corundum blocks are placed behind Stained Glass blocks, the face of the corundum blocks don't render from some orientations. The issue occurs with both Vanilla Stained Glass, and Quark Stained Framed Glass, but not regular Glass or regular Framed Glass 

This is what the expected behavior is with just Forge, Quark, and AutoRegLib
![Expected](https://user-images.githubusercontent.com/75145296/192690646-2ab87c88-fdd4-4d0e-b1c1-d0c582d966d2.png)

This is the bug when Rubidium is installed as well
![Bug](https://user-images.githubusercontent.com/75145296/192690845-064f3614-b20d-4a90-a610-0762dfca52df.png)

**Comment by KazuMurako** [comment]
I also tested with Forge Version 40.1.80 (the latest release available in the Curse Client at the time of writing) and the bug still exists.

**Comment by Asek3** [comment]
Related to Translucency Sorting, waiting for 0.5.0 Sodium with fix.
