### ISSUE TITLE
(1.18.2) java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385

### ISSUE THREAD

**Issue by Hachuurui** [Asek3/Rubidium#297]
This appears to be an issue between Fastutil and Rubidium.

Modpack: FTB Inferno
Mod Version: 0.5.3a

Crash Log: https://pastebin.com/8PuJvada

Possibly Related: https://github.com/Asek3/Rubidium/issues/289

The crash happens pretty often. Sometimes soon as world loads, other times it takes an hour or so.
I'm going to post on the modpack issues as well, but I know they will probably just send me back here.

**Comment by Saereth** [comment]
It's the same issue, fast until is part of the Java frame work and doesn't have much to do with the problem. Rubidiums mi mixin code off pretty straight forward here as well and it's mostly likely one of the other mods overwriting it

**Comment by Hachuurui** [comment]
Yeah I've seen the same issue appear with fast util and the InControl mod as well. always with the index of -1 being passed, but usually a different type of array. Their code was straight forward as well... I wonder what mod is causing this.
