### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by Corvus20** [Asek3/Rubidium#30]
I have been adding and removing mods one by one to see what is causing this crash, and it seems rubidium is the culprit. I cannot figure out exactly why it is causing the crash, as what is being shown in the crash reports is completely new to me, and don't seem to point to a specific conflict (as far as I can tell). Perhaps you could glean more from it than I can?

[crash-2022-02-21_14.32.38-client.txt](https://github.com/Asek3/Rubidium/files/8111705/crash-2022-02-21_14.32.38-client.txt)

**Comment by freopt** [comment]
looks like rubidium and chunk animator are incompatible

**Comment by Asek3** [comment]
Please, report to ChunkAnimator's devs
