### ISSUE TITLE
It works, but the one Junk in my Base is ... clear ... its dissapers with shader activ. You know a solution?

### ISSUE THREAD

**Issue by monstaa450** [Asek3/Rubidium#301]
![2022-10-01_17 03 16](https://user-images.githubusercontent.com/68509376/193415854-4e5115ab-2b05-4c60-9862-36be81177ff3.png)

**Comment by monstaa450** [comment]
Problem appears with Creat 1.19.2 mod

**Comment by SmokePuddingEveryday** [comment]
Are you on the latest Patch F for Create 1.19.2?

**Comment by Asek3** [comment]
Update Create to https://www.curseforge.com/minecraft/mc-mods/create/files/4011414
