### ISSUE TITLE
[BUG] AE2 M.E Drive renders darker with Rubidium

### ISSUE THREAD

**Issue by Aeases** [Asek3/Rubidium#304]
#149 

AE2 M.E Drive renders darker with Rubidium

Specs / Game Info:
OS: Linux
Game Version: 1.18.2

Mods: 
> appliedenergistics2-11.5.0.jar
> rubidium-0.5.3a.jar

GPU: RTX 3070
CPU: Ryzen 5600x
RAM: 32GB

_(this is video was meant for Rubidium Extras where on Pitch Black True Darkness Mode it makes it even worse but it demonstrates the same thing when true darkness is disabled at around 0:15)_
Demonstration Video: https://youtu.be/RrtwxvV_SiA?t=14

[Latest.log](https://cdn.discordapp.com/attachments/963117719752953876/1026567157913501846/latest.log)

<br>

_possibly related?_

```rust
[02:46:14] [Render thread/WARN]: Method overwrite conflict for getSprite in ae2.mixins.json:unlitquad.BakedQuadAccessor, previously written by me.jellysquid.mods.sodium.mixin.core.pipeline.MixinBakedQuad. Skipping method.
```

<br>
<br>

![image](https://user-images.githubusercontent.com/96164686/193655547-1e7e4930-5135-4e46-af6b-08ba9d01ef59.png)

**Comment by Asek3** [comment]
Update to 0.5.4
