### ISSUE TITLE
[1.19.2 Rubidium] Frogspawn makes the water below it transparent

### ISSUE THREAD

**Issue by FinxdMC** [Asek3/Rubidium#307]
Yes, you read that right, it's such a wacky bug that i was pondering, should i make an issue. i did some research and found out that either:
1. no one has noticed this before, maybe because it may be a new issue 
2. somehow i am the only one this is happening to

it only happens with frogspawn. lilypad is fine. i made sure i am using the latest 1.19.2 forge with the latest rubidium. no other mods.

below is a screenshot
![2022-10-05_19 26 52](https://user-images.githubusercontent.com/97098979/194386126-6125b3a8-dd8d-40bc-b0b5-c6cc9e26f4a6.png)

**Comment by Lolothepro** [comment]
This will be fixed with Minecraft 1.19.3

**Comment by Lolothepro** [comment]
fixed
