### ISSUE TITLE
Breaks Immersive Engineering Textures/Models

### ISSUE THREAD

**Issue by ORCXodus** [Asek3/Rubidium#31]
The bug seems to be related to (but is not limited to) animated textures... some are completely glitched out, whereas other textures which are not animated are completely invisible. (conveyors, cable ties, electrical connectors and relays and light posts)'

block textures seem unaffected but some (not all) model textures are. Some models themselves are glitched in their shape but have the correct texture (light posts )

**Comment by ghost** [comment]
I tested this with rubidium-0.5.0 and ImmersiveEngineering-1.18.1-7.1.0-145 and could not replicate the problem with convey belts or cables but I did find a problem with the three posts

**Comment by ORCXodus** [comment]
wanted to give you an update... another player on my server is now using Rubidium as well and report that they too did not see the conveyor glitch. This has made me wonder if this is a video card / GPU related issue.. He also saw the post glitch but the cable connectors and conveyors looked normal. We made sure to set all of our video options to the same settings.

**Comment by kalilani** [comment]
I also have this issue, but I believe that the invisible blocks (specifically the electric lantern) have to do with an Oculus incompatibility, as they reappear when I disable Oculus. I do also have the texture problem with the light posts, even with Oculus disabled.

Thank you for your work on Rubidium by the way - it's been a huge upgrade in my performance!

**Comment by ghost** [comment]
Maybe rename this issue as "Breaks Immersive Engineering Texture"?

**Comment by TehFoxFire** [comment]
Any update on this issue? Im having the same issue with wires (havent tested conveyers or poles yet) on 1.18.2 with 0.5.1a.

**Comment by HydrogenC** [comment]
The multiblocks got a complete fix, but cable connectors and conveyors are still invisible with version 1.16.5-0.2.5. 
Besides, placing an IE wooden post seems to cause the crash in #69.

**Comment by Sonic1305** [comment]
Immersive Engineering wires are still invisible in the most recent version (1.18.2)
