### ISSUE TITLE
[1.16.5]java.lang.NullPointerException

### ISSUE THREAD

**Issue by OcrSu** [Asek3/Rubidium#312]
1.16.5 win11 java11
Ryzen5 5600
GT1030 DDR5 2G

[crash-2022-10-11_18.57.22-client.txt](https://github.com/Asek3/Rubidium/files/9754414/crash-2022-10-11_18.57.22-client.txt)

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
