### ISSUE TITLE
[1.19.2] [Create] Crashing upon trying to break a chest

### ISSUE THREAD

**Issue by ztx-lyghters** [Asek3/Rubidium#313]
Steps to reproduce:
Boot up a Void Linux. Open Minecraft with ATM8 modpack, load a world. If that's a new world - play it for some time. Place a vanilla chest on the ground and try to break it with a bare hand. Get a libc native code crash.

I do have a lot of mods, it's a changed ATM8 modpack with even more mods, but this bug happens ONLY with Rubidium turned on. ~~I also did get this bug on the stock ATM8 with latest two versions of ATM8~~. Disabling Rubidium solves the crash. Tried to change every possible Rubidium option (in GUI settings anyway). Tested on AMD FX-8350 with GTX 1060 3GB (attached report is from this machine) and on a laptop with Ryzen 7 (I don't remember the model, sorry) with integrated video, on both machines it crashes and the crash is related to the same error - **__memcpy_sse2_unaligned_erms+**_somehexnumber_

**Tested with Rubidium 0.6.2**
Forge is 43.1.34
I'm using VoidLinux with Java 17.0.5 and glibc 2.32, running the game with PolyMC.
[>>log file<<](https://github.com/Asek3/Rubidium/files/9766742/hs_err_pid19890.log)

**Comment by ztx-lyghters** [comment]
OK, it was a bit tedious, but I was turning off mods one by one and found the other end of this problem - **Create**.
Apparently **Rubidium and Create for 1.19 don't play together**... That's a shame.
I don't know which side should take any action, so I'll be sure to mention this problem in Create repo as well.

**Comment by SmokePuddingEveryday** [comment]
> OK, it was a bit tedious, but I was turning off mods one by one and found the other end of this problem - **Create**. Apparently **Rubidium and Create for 1.19 don't play together**... That's a shame. I don't know which side should take any action, so I'll be sure to mention this problem in Create repo as well.

Are you sure you're on the latest version of Create for 1.19.2? I believe the bug has been fixed already.

**Comment by ztx-lyghters** [comment]
> > OK, it was a bit tedious, but I was turning off mods one by one and found the other end of this problem - **Create**. Apparently **Rubidium and Create for 1.19 don't play together**... That's a shame. I don't know which side should take any action, so I'll be sure to mention this problem in Create repo as well.
> 
> Are you sure you're on the latest version of Create for 1.19.2? I believe the bug has been fixed already.

I'm using version 0.5.0.f, which is the latest available on both curseforge and modrinth.

**Comment by ztx-lyghters** [comment]
Seems like it was ATM8 specific problem, sorry about that. Closing.
https://github.com/AllTheMods/ATM-8/issues/63
