### ISSUE TITLE
Crash With Newest Rubidium in 200+ mod modpack

### ISSUE THREAD

**Issue by MCBEModder2020** [Asek3/Rubidium#314]
forge 40.1.80
Rubidium mc1.18.2-0.5.4 makes it crash when loading a world
Rubidium mc1.18.2-0.5.3a is fine
if you ask for more information i will provide it

**Comment by coderepo8593** [comment]
Do you believe you have provided enough information for someone not sitting at your computer and not experiencing the problem for themselves to troubleshoot the problem and figure out what is going on?

**Comment by YassaaaTU** [comment]
There is a conflict with citadel and rubidium that is why its crashing same thing for me I disabled Rubdium & Co. mods then mc worked fine

**Comment by MCJEModder2026** [comment]
what information is needed

**Comment by Zelioth** [comment]
If you can provide any logs and debug files that generate right after the crash. minecraft versions, modpack you are using

**Comment by MCJEModder2026** [comment]
ok il try to get some logs btw im using a custom private modpack

**Comment by MCJEModder2026** [comment]
hmmm no longer crashes i remember updating some mods so fixed?
