### ISSUE TITLE
[1.18.2] java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385

### ISSUE THREAD

**Issue by Tlotro** [Asek3/Rubidium#316]
minecraft randomly crashes when rendering new chunks (actively moving over long distances). Chunks do not need to be newly generated.

here is the crash report (most machine specification excluded for privacy reasons)
[crash-2022-10-12_22.43.47-client.txt](https://github.com/Asek3/Rubidium/files/9777010/crash-2022-10-12_22.43.47-client.txt)

**Comment by Asek3** [comment]
Update Rubidium to 0.5.4
