### ISSUE TITLE
Conflict with Citadel library mod

### ISSUE THREAD

**Issue by YassaaaTU** [Asek3/Rubidium#317]
MC Ver.: 1.19.2
Forge Ver.: 43.1.38
Mod Ver.: rubidium-0.6.2
Citadel Ver.: citadel-1.13.0-1.19

Installed Rubidium mods:
[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium), [Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra), [TexTrue's Rubidiums Options](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options), [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)

Crash Report & Logs:

> [Log file](https://mclo.gs/jPOEZ5B)
> [Crash Report](https://mclo.gs/aa3on5L) <-- This here says something about Oculus throwing errors
> 

> [Log File](https://mclo.gs/GKo2d5S)
> [Crash Report](https://mclo.gs/SoSRbTj) <-- This here is without Oculus and it says citadel but when I disabled rubidium mc works just fine
>

**Comment by Zelioth** [comment]
I also just found this issue for 1.19.2. Testing different mods that have issues with Rubidium and it's addon mods seems to have major issue with citadel Library and addons

**Comment by Kasualix** [comment]
https://github.com/dimadencep/sodium-extra-forge/issues/21
It's not Rubidium's problem.

**Comment by Asek3** [comment]
yes
