### ISSUE TITLE
Latest update bring old issue back. Mod Incompatibility with Physics mod.

### ISSUE THREAD

**Issue by KKotik** [Asek3/Rubidium#32]
But now it seems to happen when you join the world. (Not exactly #14)
[debug.log](https://github.com/Asek3/Rubidium/files/8146310/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/8146311/latest.log)

**Comment by Asek3** [comment]
Problems seems to be on their part, plz report to Physics' mods devs
