### ISSUE TITLE
Game crashed with oculus and rubidium

### ISSUE THREAD

**Issue by Akoto090** [Asek3/Rubidium#320]
My Game crash with no exit code but with crash report in single player map on the latest and penultimate version of rubidium. Idk if this is a rubidium or oculus error.
[crash-2022-10-15_17.08.46-client.txt](https://github.com/Asek3/Rubidium/files/9792594/crash-2022-10-15_17.08.46-client.txt)
[crash-2022-10-15_18.22.34-client.txt](https://github.com/Asek3/Rubidium/files/9792595/crash-2022-10-15_18.22.34-client.txt)

**Comment by Andrezinho1** [comment]
yeah it's pretty common look back in the issues it's been up for a couple days
