### ISSUE TITLE
[1.16.5] Memory leaks in the server client.

### ISSUE THREAD

**Issue by DrSigma4164** [Asek3/Rubidium#333]
Hello. After switching from Magnesium mod to yours, because the old one was abandoned, players who join a separate server or another player who started a LAN server after a while, about an hour, get an Out Of Memory error. 
  I tried with memory dumps, and yourkit program, I tried to compare the heap immediately after entering the server and when this error occurs with the settings in the 1nd screenshot. And it showed me this, which is shown in the screenshot below. 
  As far as I understand, your mod in my build, which I'll post below so you can analyze it in your own way, is rendering.
  I will say right away that I tried to turn off the shaders and the entire Oculus mod, because I thought that these lines on the screenshot were rendered from shaders.
  I hope you will help me with this.
![image](https://user-images.githubusercontent.com/93322905/199080938-552c6534-9ee2-4714-b3de-f6d351411fa4.png)

![image](https://user-images.githubusercontent.com/93322905/199081023-a0b6d973-30fc-43ca-9093-6c11afd4bc3e.png)
![image](https://user-images.githubusercontent.com/93322905/199081106-8643a354-b929-42f4-9811-7c4b873c64fa.png)
![image](https://user-images.githubusercontent.com/93322905/199081185-2c19fa92-fae2-4940-a39a-25df18931254.png)

[1.16.5_MOD_AoI-1.4.1_MemoryLeaks.zip](https://github.com/Asek3/Rubidium/files/9903815/1.16.5_MOD_AoI-1.4.1_MemoryLeaks.zip)

Also here are the log files.
[LOGS.zip](https://github.com/Asek3/Rubidium/files/9903951/LOGS.zip)

**Comment by DoctorSigma** [comment]
Also here are the log files.
[LOGS.zip](https://github.com/Asek3/Rubidium/files/9903951/LOGS.zip)

**Comment by quentin452** [comment]
i have this problem too , in my modpack

**Comment by Kasualix** [comment]
https://github.com/Asek3/Rubidium/issues/178
