### ISSUE TITLE
Random Crashes (1.19.2)

### ISSUE THREAD

**Issue by Tosh022402** [Asek3/Rubidium#336]
I´ve been making a modpack and my game sometimes just crashes randomly, its sometimes just a few mins after loading a new world or sometimes after an hour or 2. Been testing by adding/removing other mods like ferritecore, canary, forgetmechunk, create, but this problem keeps happening.
[crash-2022-11-04_18.01.31-client.txt](https://github.com/Asek3/Rubidium/files/9936792/crash-2022-11-04_18.01.31-client.txt)

**Comment by TheElectronWill** [comment]
this seems to be the same as #297 but for 1.19, I think #309 should be ported to the 1.19 branch

**Comment by genesy** [comment]
happens for me as well. https://bytebin.lucko.me/mvYfIADw5F

**Comment by Asek3** [comment]
Fixed on latest versions
