### ISSUE TITLE
Incompatibility with create/flywheel 1.19.2

### ISSUE THREAD

**Issue by skybix** [Asek3/Rubidium#338]
forge 43.1.47
rubidium-0.6.2.jar
create-1.19.2-0.5.0.f.jar
flywheel-forge-1.18.2-0.6.5.jar

crash report:
https://pastebin.com/U5WTAsSM

**Comment by Cinderheart** [comment]
Flywheel is only for 1.18. Try uninstalling it, the newest versions of Create don't use it directly anymore.
