### ISSUE TITLE
Shadow Issue.

### ISSUE THREAD

**Issue by sk-KAZU** [Asek3/Rubidium#339]
![2022-11-06_12 06 20](https://user-images.githubusercontent.com/84232965/200152118-fa6c577b-bf6a-4b91-aae3-1b22cb02ffe3.png)
When Rubidium version 1.19.2 was introduced, all the terrain became shadow like the image above. Is this a Rubidium issue? Or is it a compatibility issue with other mods?

Here is the list of mods.

AppleSkin
Balm
Cloth Config v8 API Clumps
Collective
Corpse
Create
EntityCulling
Falling Leaves
Farsight mod
FastFurnace
FastLeafDecay
Flywheel
Inventry HUD+(Forge edition)
Inventry Profiles Next
Jorneymap
Just Enogh Items
KleeSlabs
libIPN
Neat
Overloaded Armor Bar
Placebo
Puzzles Lib
ReBlured
Responsive Shields
Rubidium
Sound Physics Remastered
Stack Refill
Tax Free Levels
Visual Workbench

**Comment by devek1** [comment]
I had the same issue and it turned out that it was because the version on Modrinth is outdated (0.6.1). Downloading the latest version from CurseForge (0.6.2) fixed it for me.

**Comment by sk-KAZU** [comment]
Thanks for answering.
I fixed it too and work it well. Thanks to make this amazing mod.

**Comment by JulianGro** [comment]
Thanks. I had exactly the same issue.
@Asek3 not sure if you have seen this, since the issue has already been closed.
