### ISSUE TITLE
[Port Request] Rubidium on 1.16?

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Asek3/Rubidium#34]
Hi,

We have recently been using Magnesium on our large scale 1.16 modpack but from the looks of it that mod has since been abandoned and more issues are coming up by the day with it to the point we're having to disable parts of the mod to continue to use it,

Would it be possible for Rubidium to have a port to 1.16, I can almost guarantee mod creators across the board would be heavily grateful for this.

**Comment by Asek3** [comment]
So, idk if I can fix Magnesium's issues, so I don’t think it’s really necessary. Maybe someday I'll port Rubidium to 1.16
