### ISSUE TITLE
1.19.2: UI elements turn invisible with Create/Flywheel

### ISSUE THREAD

**Issue by MrFastZombie** [Asek3/Rubidium#340]
When looking at a certain angle, most UI elements turn invisible. I only had Create 0.5.0.f installed with Forge 43.1.1 installed other than Rubidium 0.6.1 for testing. I do not know if this is an issue on Create's end or Rubidum but it occurs only when Create and Rubidium are installed.

Here is a short video showing the issue:

https://user-images.githubusercontent.com/18253497/200453552-58725ff7-61cd-4038-ac25-7b64074629e7.mp4

**Comment by JDtheHutt** [comment]
I am experiencing the same with Rubidium 0.6.1.  Additionally, dark blocks and lighting is behaving really strangely.  Happens with or without shaders enabled with Oculus.  I wasn't sure what was causing it at first but removed Rubidium and everything returned to normal.  I switched to Rubidium 0.6.2 and my client doesn't even load, I get a crash with it showing a failure due to a conflict with Create.

**Comment by MrFastZombie** [comment]
I just tried out 0.6.2. Seems to be working for me now. I'm joining a community event this weekend, so I'll wait until then to close this issue as I'll have a chance to put it to a real-world test and make sure there aren't rarer triggers.

> I switched to Rubidium 0.6.2 and my client doesn't even load, I get a crash with it showing a failure due to a conflict with Create.

Are you using any other mods? 0.6.2 with Create 0.5.0.f & Oculus Flywheel compat 0.1.6 alpha seems to load properly on my end.
 
Edit: FYI, I think Oculus-Flywheel compat is causing a crash when placing Create components. 
Edit2: Okay, even with flywheel compat it is working for me again. I don't know what those crashes were about.

**Comment by JDtheHutt** [comment]
I have a bunch of other mods.  I stopped using Oculus Flywheel Compat as it caused so many issues with other mods.  With Oculus Flywheel Compat included again the client often just crashes before even loading, and if I get on it still crashes randomly and suddenly while playing.  Logs are a sea of major issues relating to this.  However, it does actually resolve the weird texture and gui issues.  I think for now I will just have to drop Oculus and Rubidium entirely.

**Comment by MrFastZombie** [comment]
Seems to be working good with Rubidium 0.6.2.
