### ISSUE TITLE
[1.18] Emissive textures

### ISSUE THREAD

**Issue by mortuusars** [Asek3/Rubidium#342]
For my mod I used this "hack", which I've borrowed from Refined Storage to make a quad fullbright:
```int[] vertexData = quad.getVertices().clone();
int step = vertexData.length / 4;

 // Set lighting to fullbright on all vertices
vertexData[6] = 0x00F000F0;
vertexData[6 + step] = 0x00F000F0;
vertexData[6 + 2 * step] = 0x00F000F0;
vertexData[6 + 3 * step] = 0x00F000F0;
```

Issue is - with rubidium this has no result anymore, and texture is affected by lighting.
Refined storage has the same issue (same code is used).

So my question is: 
**Is it Rubidium issue or is there a proper way to do it in 1.18?** (I know that in 1.19 forge added support for emissive textures officially)

Relevant issue from my mod: mortuusars/Chalk#29

**Comment by TheD0ct0r101** [comment]
Is this in regards to the RS Disk Drive smooth lighting bug? That's be plaguing me too. Im hoping it can be resolved on Rubidium's side, as the RS dev told me its due to how Rubidium handles forge features, not RS.

**Comment by mortuusars** [comment]
@TheD0ct0r101 
No, this is different issue. See https://github.com/mortuusars/Chalk/issues/29 for details.
