### ISSUE TITLE
Issues when opening a world with rubidium.

### ISSUE THREAD

**Issue by Ind1g0146** [Asek3/Rubidium#347]
Hi!

Recently I started curating a selection of mods to play on 1.16.5. I downloaded all of them and opened Minecraft. At first it crashed because I missed some dependencies but after installing them I managed to get into the main menu. I created a world to test them out and it crashed again, so I removed some mods and tried again. It worked so I added a few more mods. It worked again and I added another couple. I got into a world again this time but I decided to change some video settings in rubidium. After changing the settings it went to the mojang loading screen and after around 10 minutes it finally loaded, then immediately crashed. Upon opening the game I tried again and it crashed. This time I reverted some of the video settings but then it still crashed when I opened a world. Heres the crash report for more information: https://pastebin.com/raw/Yh9LwrpX

Also, I tested the game with every mod except rubidium+oculus and it was working perfectly so I know its an issues with either one of those, maybe a conflict with another mod? 

Any help would be much appreciated!

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
