### ISSUE TITLE
[1.19.2} Visual issues with transparent blocks

### ISSUE THREAD

**Issue by IlTAKlI** [Asek3/Rubidium#351]
Transparent blocks at chunk borders cause a really bizarre issue, I'm not sure how to explain it but here's some pictures

![2022-11-17_01 40 04](https://user-images.githubusercontent.com/99926595/202538577-59a03bb1-6d4a-49d2-a714-c3d1c263c575.png)
![2022-11-17_01 40 56](https://user-images.githubusercontent.com/99926595/202538590-82b42f4a-dd38-4cef-9192-e272c7f7ac16.png)

You can see the border of chunks when two transparent blocks are against it

**Comment by Dzuco** [comment]
I have the same issue

**Comment by Asek3** [comment]
Translucency sorting issue, which cannot be fixed by me
