### ISSUE TITLE
Avaritia items turn white when using Rubidium

### ISSUE THREAD

**Issue by maike03030** [Asek3/Rubidium#356]
Avaritia items turn white when using Rubidium

![Screenshot_171](https://user-images.githubusercontent.com/62162055/203449027-8d59f2b3-ce39-44fc-a69d-91907395667b.png)

**Comment by menga28** [comment]
Still same problem, with latest version 0.5.4

**Comment by SSUPII** [comment]
Confirming the issue being present in build 0.5.4.

**Comment by Asek3** [comment]
Fixed in latest versions
