### ISSUE TITLE
weird chunk rendering crash

### ISSUE THREAD

**Issue by DKLYNTLY** [Asek3/Rubidium#358]
[crash-2022-11-24_12.44.43-client.txt](https://github.com/Asek3/Rubidium/files/10086852/crash-2022-11-24_12.44.43-client.txt)
[crash-2022-11-24_13.31.32-client.txt](https://github.com/Asek3/Rubidium/files/10086853/crash-2022-11-24_13.31.32-client.txt)

**Comment by Asek3** [comment]
Probably related to Forgery, try update or delete mod
