### ISSUE TITLE
Crashing trying to enter server

### ISSUE THREAD

**Issue by Eterst** [Asek3/Rubidium#359]
### **Version Information**
- rubidium-0.2.7
- Minecraft 1.16.5
- Forge Server
### **Reproduction Steps***
- Install rubidium
- Enter multiplayer server
### **Description**
The client crashes trying to enter multiplayer server. In singleplayer worlds it works fine.
### **Crash Report file**
[crash-2022-12-02_11.04.08-client.txt](https://github.com/Asek3/Rubidium/files/10142948/crash-2022-12-02_11.04.08-client.txt)

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
