### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65537 (minecraft 1.19.2, forge 43.1.52)

### ISSUE THREAD

**Issue by KoryAlbright** [Asek3/Rubidium#362]
[crash-2022-12-03_15.37.44-client.txt](https://github.com/Asek3/Rubidium/files/10147544/crash-2022-12-03_15.37.44-client.txt)

**Comment by Asek3** [comment]
Fixed on latest versions
