### ISSUE TITLE
Modded worlds wont load after installing rubidium.

### ISSUE THREAD

**Issue by Aerhtjiz** [Asek3/Rubidium#364]
I made a massive modpack to play and when making new worlds with rubidium it created the world but then says saving world and get stuck there. There are no crash or logs so i've got no clue

**Comment by CoryGuy** [comment]
If you're using the latest Forge 43.2.0, Rubidium and Oculus are not supported yet.

**Comment by Aerhtjiz** [comment]
> If you're using the latest Forge 43.2.0, Rubidium and Oculus are not supported yet.

I wasn't using oculus only rubidium

**Comment by Bmedina82** [comment]
What is the latest forge that rubidium supports? 43.1.65 crashes on startup.

**Comment by willrun4fun** [comment]
Comments on the Oculus Curse say to stick with 43.1.57.  I've had it running on 43.1.58 though.
