### ISSUE TITLE
1.16.5 Fluids not showing right colors

### ISSUE THREAD

**Issue by mxnmnm** [Asek3/Rubidium#370]
Rubidium acts weird with certain fluids making them look blue. 
![2022-12-12_00 15 11](https://user-images.githubusercontent.com/8508976/206995028-4a588c89-a440-4969-8633-4d17c8f4f040.png)

**Comment by Kasualix** [comment]
I also have this problem.
All fluids I customize by KubeJS look blue.

**Comment by Asek3** [comment]
Fixed in Dev
