### ISSUE TITLE
1.18.2 Rubidium invisible chunks 

### ISSUE THREAD

**Issue by Zoomanata** [Asek3/Rubidium#374]
So randomly after playing for a few days, my friends house has suddenly gone half invisible and am unsure what to do, i assume it could be an incompatible mod. Ive tried to remove create and some others but they dont solve it. Removing this mod fixes the issue, but subsequently i have roughly 30 - 40 fps as opposed to a nice 100+ fps. Ive done some research and can not find anything that has helped :(  i am using 1.18.2,  forge 40.1.84, rubidium 5.4 (the latest) have also tried different versions of rubidium which didnt help XD

Here is the modlist: 
[modlist.pdf](https://github.com/Asek3/Rubidium/files/10249652/modlist.pdf)

Thanks in advance! :P
![2022-12-16_21 46 53](https://user-images.githubusercontent.com/97367828/208196338-2aab0054-a3d2-418d-b0fb-032eb9163e73.png)

 
![2022-12-16_21 46 37](https://user-images.githubusercontent.com/97367828/208196372-a27bab06-2be2-40ae-94c5-205009db2285.png)
![2022-12-16_21 45 17](https://user-images.githubusercontent.com/97367828/208196388-1760c475-eb5e-46ff-962f-543c1c005e09.png)
![2022-12-16_21 44 58](https://user-images.githubusercontent.com/97367828/208196391-f74eeebd-ae8e-4ffe-81ad-026e0c4811e8.png)

**Comment by budgej** [comment]
Seeing the same thing in Odyssey 3.

**Comment by Zoomanata** [comment]
> Seeing the same thing in Odyssey 3.

so im not sure what fixed it but i did update some of / the rest of my mods, maybe you need to update the modpack i guess?!?!
