### ISSUE TITLE
[Forge 1.19.2-43.2.0] Wont start combined with Optifine Mod

### ISSUE THREAD

**Issue by Fireflasher21** [Asek3/Rubidium#377]
Problem:
- Started Mc with Rubidium-0.6.2 and Optifine-HD-U-H9_Mod
- Crashed before it Mc could launch, straight back to Launcher exit Code 1
- Following logs of latest.log and debug.log:
latest: https://pastes.dev/R8eV6ABGWt
debug: https://pastes.dev/xh96zxGTVl
launcher: https://pastes.dev/09bCdLrpFe

**Comment by Mitchell5200** [comment]
Of course it won't, Optifine is generally incompatible with most things and as per the CF page for Rubidium it's also incompatible here too
![Screenshot 2022-12-21 11 48 04](https://user-images.githubusercontent.com/45913837/208817201-0858c9a1-e14a-4c22-880e-4f63190b4b93.png)

**Comment by Fireflasher21** [comment]
I figured as soon as i posted the issue xD
Sry bout that
