### ISSUE TITLE
Crash when joining server world

### ISSUE THREAD

**Issue by thebikwirm** [Asek3/Rubidium#378]
[crash-2022-12-23_17.00.54-client.txt](https://github.com/Asek3/Rubidium/files/10294290/crash-2022-12-23_17.00.54-client.txt)
How do I fix this issue
I have just installed the mod and loaded into a new world on my server and i have this issue, I also have oculus installed but no shaders running

**Comment by Asek3** [comment]
Update BetterEnd to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090
