### ISSUE TITLE
[1.19.2]Random crashes while playing on multiplayer

### ISSUE THREAD

**Issue by Metasura** [Asek3/Rubidium#379]
Hello i'm having JRE crashes while playing on my server (1.19.2 heavily modded on a separate dedicated machine rubidium version 0.6.2) and they always happen at random times (around 1 hour or so).
I'll link the crash log (https://hastebin.com/okobunilig.yaml) unfortunately google did not help me with this one even when researching the problematic frame.
All i know is that this is a render issue and that my graphic driver reboot when it happens and that i saw a sodium line in the java frames of the error. 
If anyone has any clues to what is happening (rolled back graphic drivers, changed java provider microsoft => oracle, i'm allocating 9GB of ram. That should be plenty for what i'm playing and i'm the only one of my friends who is having issues.
My pc specs are rtx 2060 6GB, ryzen 5 3600 and 16GB of ram.

**Comment by Alanimdeo** [comment]
#309 resolves the error, but it is for 1.19.3 so we can't use it in 1.19.2. We need 0.6.3 version of Rubidium for 1.19.2.

I tried to build with fixes, but Gradle says "ChunkRenderRebuildTask.java:17: error: package net.coderbot.iris.compat.sodium.impl.block_id does not exist".

**Comment by Metasura** [comment]
What i'm getting seems different from Index out of bound exception as it is not minecraft that crashes but the entire java VM and the game does not output a crash log but the jv does and the name look more like "hs_err_pid****.log". They may be related but i'm the only one of my friend who's having this issue (but the more i look into it the more it seems something is sucking up vram on my gc then causes the driver to either reboot or freeze thus causing this crash)

**Comment by Metasura** [comment]
Okay after a bit of investigation there seems to be a bug with nvidia drivers and sodium (so maybe rubidium too) and that seems to be exactly what i'm getting, The sodium issue is here https://github.com/CaffeineMC/sodium-fabric/issues/1486.

**Comment by Metasura** [comment]
So after reinstalling windows i don't experience this crash anymore so i think it had to do more with a faulty windows install rather than an issue with the mod so i'm closing this issue
