### ISSUE TITLE
[Issue] Mixin min version

### ISSUE THREAD

**Issue by rabrunos** [Asek3/Rubidium#38]
Mixin's minimum version was not specified.
![image](https://user-images.githubusercontent.com/83606488/158711556-8285461d-aa46-4aa9-8e22-d34f6665abb1.png)

The link below is saying that it is important, although Rubidium is working perfectly, even without specifying the minimum version.
(_Only this error appears in the LOG_)
[Mixin version history](https://github.com/SpongePowered/Mixin#version-history)

**Comment by Asek3** [comment]
just warning
