### ISSUE TITLE
Rubidium Doesn't let Bisect Hosting server start

### ISSUE THREAD

**Issue by MrMc1ean** [Asek3/Rubidium#383]
I try to add Rubidium to my server on bisect hosting but every time it doesn't start, when I remove Rubidium it starts fine I am playing on 1.18.2 Vault Hunters 3rd edition modpack and I downloaded the 1.18.2 Rubidium. Thanks :)

**Comment by quentin452** [comment]
rubidium is client side

**Comment by Asek3** [comment]
Rubidium should be loaded only on client
