### ISSUE TITLE
[1.18.2]water visual glitch with only rubidium loaded

### ISSUE THREAD

**Issue by Athurrender** [Asek3/Rubidium#387]
![2023-01-11_20 35 41](https://user-images.githubusercontent.com/122013559/211810767-25692125-b298-4371-aa8f-5c18739cf24a.png)
Just as the picture shows
I have tested sodium 1.18.2 and found the same issue.SAD

**Comment by Nat-133** [comment]
Able to replicate in 1.19.2 - 0.6.2b
It only seems to be an issue when air is behind the water (tested with glass as well)
![image](https://github.com/Asek3/Rubidium/assets/38531548/16e4d068-7c9a-43bc-b551-8dc678f0c25f)
![image](https://github.com/Asek3/Rubidium/assets/38531548/f365fa05-7102-48e5-90af-b63ec0aeb61d)
![image](https://github.com/Asek3/Rubidium/assets/38531548/6f13cfb2-cd89-44c4-8399-b02bc8128fa6)
![image](https://github.com/Asek3/Rubidium/assets/38531548/8847e8bb-a651-46d9-9c0f-5a059be7fbc6)

**Comment by Asek3** [comment]
Related to translucency sorting which cannot be fixed by us
