### ISSUE TITLE
(1.19.2) Rubidium causes rendering issues with pneumatic craft tanks

### ISSUE THREAD

**Issue by fixthissitepls** [Asek3/Rubidium#388]
The transparent part of Tanks from pneumatic craft render black and white when placed down. Removing or adding fluids won't change the texture at all.
I already posted the issue on the pneumatic craft GitHub, but I was told that the issue is caused by rubidium, so here i am.
![2023-01-11_15 35 27](https://user-images.githubusercontent.com/118289704/211979125-c6e1d35c-a82c-43b8-b085-86c8e8eb9ae7.png)

https://github.com/TeamPneumatic/pnc-repressurized/issues/1121

**Comment by Asek3** [comment]
Update Rubidium
