### ISSUE TITLE
API to allow other mods to enable/disable certain mixins selectively is commented out and unimplemented.

### ISSUE THREAD

**Issue by alcatrazEscapee** [Asek3/Rubidium#393]
I would like to disable `mixin.feature.fast_biome_colors`, as indicated [here](https://github.com/Asek3/Rubidium/blob/f93e979e6a4caeb8c620370a5911d825098b172f/src/main/java/me/jellysquid/mods/sodium/common/config/SodiumConfig.java#L53), with a specific mod present, as it breaks the sky color of said mod. Unfortunately, this API is commented out and unimplemented with no alternative presented:

https://github.com/Asek3/Rubidium/blob/32c5ed34c3cd816705f065e8d482ddc6ab1ec828/src/main/java/me/jellysquid/mods/sodium/common/config/SodiumConfig.java#L97-L139

**Comment by Asek3** [comment]
https://github.com/Asek3/Rubidium/commit/1c6cc83a662bb42f63e8ef23f62fecf789263687
Will be added in next release

**Comment by Asek3** [comment]
Example: https://github.com/Asek3/Oculus/blob/1.19.4/src/main/resources/META-INF/mods.toml
