### ISSUE TITLE
A fork to fix the OutOfBounds crash in 1.19.2

### ISSUE THREAD

**Issue by Dunkmania101** [Asek3/Rubidium#396]
> #309 resolves the error, but it is for 1.19.3 so we can't use it in 1.19.2. We need 0.6.3 version of Rubidium for 1.19.2.
> 
> I tried to build with fixes, but Gradle says "ChunkRenderRebuildTask.java:17: error: package net.coderbot.iris.compat.sodium.impl.block_id does not exist".

After much fiddling, I did get my fork to build. runClient fails complaining about vanilla classes somehow loading, but the built jar file works just fine in game. I also took the liberty of using CurseMaven instead of requiring local jars.

In case anyone wants to use it, just clone my fork and run `gradlew.bat genEclipseRuns` if you're on Windows or `gradlew genEclipseRuns` anywhere else, then run `gradlew.bat build` if you're on Windows or `gradlew build` anywhere else. The built jar file will be saved at `build/libs/rubidium-{version}.jar`.
Here ye goes:
[https://github.com/Dunkmania101/Rubidium-1.19.2-fix.git](https://github.com/Dunkmania101/Rubidium-1.19.2-fix.git)

Alternatively, I've uploaded a prebuilt jar as a release in my repository.
[https://github.com/Dunkmania101/Rubidium-1.19.2-fix/releases/latest](https://github.com/Dunkmania101/Rubidium-1.19.2-fix/releases/latest)

**Comment by Socianxious** [comment]
idk how to do it, i ran gradlew.bat build, and after it's finished doing its thing, what next?

**Comment by Dunkmania101** [comment]
> idk how to do it, i ran gradlew.bat build, and after it's finished doing its thing, what next?

I updated the original comment with the specific path.

**Comment by Socianxious** [comment]
there's only loom-cache which is empty, do i need to put the original rubidium 0.6.2 file in the directory folder first before i run it?

**Comment by Dunkmania101** [comment]
I guess you need to run `gradlew.bat genEclipseRuns` first, then the build command. I thought it would handle that part automatically, but I now realize it probably doesn't. I'll update the original comment accordingly. Thank you for pointing this part out, I'd have almost certainly not noticed it myself. I assume it only worked for me because I *had* run the genEclipseRuns command for development, which naturally happens before building.

**Comment by Socianxious** [comment]
oh, sure i guess. but thank you for making this, i assume i have to download that somewhere?

**Comment by Dunkmania101** [comment]
Download what? You don't need to download Eclipse if that's what you're asking about. You could also run `gradlew{.bat} genIdeaWorkspace`, it just needs to be something that prepares the workspace.

**Comment by Socianxious** [comment]
idk where gradlew.bat genEclipseRuns is

**Comment by Dunkmania101** [comment]
Oh, it's not a file called `gradlew.bat genEclipseRuns`. It's a file called `gradlew.bat`, the same one used for building, but run with `genEclipseRuns` as a parameter instead of `build`. I should clarify that the file needs to be run from a shell, not double clicked from a file explorer. I forget the exact shortcut, but I think on Windows you can open a command prompt window in a directory from the file explorer by replacing the path in the top bar with the text `cmd` and pressing enter.

As a side note, I suppose the file *can* be run with a double click, but it will just complain about not knowing what you want it to do and exit.

**Comment by Socianxious** [comment]
i can't figure out how to do it, i'm too dumb T^T

**Comment by Socianxious** [comment]
could u send the fixed mod file instead?

**Comment by Dunkmania101** [comment]
I uploaded it as a release in my fork's repository. There's a direct link in the original comment above.

**Comment by Socianxious** [comment]
ohhh, thank you so much

**Comment by genesy** [comment]
rubidium for 1.19.2 is abandoned, must cherry pick future fixes ourselves
