### ISSUE TITLE
Enigmatica 6 and this

### ISSUE THREAD

**Issue by Abalieno** [Asek3/Rubidium#41]
This seems the only port of Sodium currently seeing activity, and now it has a 1.16.5 version, so I wonder if it's possible to look into the Enigmatica 6 pack.

I don't know if it's a specific mod conflict, but the problems are evident by simply logging into the game. It seems with both Magnesium and Rubidium transparent blocks aren't rendered, like all water. And instead of a sea in front of me I can see all the caves underground.

It also usually crashes shortly after.

It seems like a basic rendering issue rather than a specific mod. The other performance mods are fine (Roadrunner, Starlight...).

**Comment by Asek3** [comment]
Send some screenshots & crash-reports plz

**Comment by novorow** [comment]
Unrelated, but in Enigmatica 6 there is no water in this multiblock, when they should be water

With Rubidium
![2022-03-21_19 04 33](https://user-images.githubusercontent.com/97646254/159377678-8a1cea2b-db99-4d59-9802-69712676bafa.png)

Without Rubidium
![2022-03-22_06 07 58](https://user-images.githubusercontent.com/97646254/159377751-b102ab75-0189-4506-b889-6c8a1e0f8f95.png)

-----------------------------------------------------------------------------------------------------------------------------------------
![2022-03-21_19 04 42](https://user-images.githubusercontent.com/97646254/159377798-f07e6b80-e0a7-4ce2-b7ab-f99ba03e709a.png)

**Comment by Abalieno** [comment]
[crash-2022-03-22_03.27.17-client.txt](https://github.com/Asek3/Rubidium/files/8320532/crash-2022-03-22_03.27.17-client.txt)

If it's of any help. As far as I know it seems to have problems retrieving some value about fluids.

Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.handler$zgm000$getWaterColor(SourceFile:558) ~[?:?] 
{re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:BiomeColorsMixin,pl:mixin:A}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[forge:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.lambda$static$0(FluidRenderer.java:39) ~[rubidium:?] {re:classloading}

Can't add screenshots because even after several attempts the game now crashes too soon as I log in. But what I see is still what I described: instead of water I see a myriad of caves and lava that would otherwise be obscured.

**Comment by Asek3** [comment]
Plz recheck issues on Rubidium 0.2.3

**Comment by Abalieno** [comment]
Tried with 0.2.3 > created new world > crashed two seconds in

Crash log looks the same.

I was able to take a screenshot immediately before the crash, but the world was still loading.

[crash-2022-03-27_05.21.04-client.txt](https://github.com/Asek3/Rubidium/files/8356760/crash-2022-03-27_05.21.04-client.txt)

![2022-03-27_05 21 01](https://user-images.githubusercontent.com/4656436/160265251-eab87581-7b67-4db9-8623-3f18494158e3.png)

**Comment by Asek3** [comment]
Ok, so u have old BetterEnd version. Plz update to https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files/3523090 this
