### ISSUE TITLE
Rendering issue on improved blast furnace from immersive engineering when using the mod with rubidium. minecraft version 1.19.2 newest version of both mods

### ISSUE THREAD

**Issue by math8742** [Asek3/Rubidium#415]
![rubidium immersive engineering glitch](https://user-images.githubusercontent.com/125552946/219326716-daf3a99f-e329-4067-ad3c-792b356941ce.png)

As described in the title and the image the following visual glitch happens when using newest versions of both mods on minecraft version 1.19.2. Saving the game and reloading does not fix it, neither does turning off VBO rendering in immersive engineering. Removing rubidium from the mods folder fixes the issue. The list of mods I am using are the following:

![modlist 1](https://user-images.githubusercontent.com/125552946/219328118-ee2a4bd3-f16f-4acc-b0d3-f4db1501a36b.png)
![modlist 2](https://user-images.githubusercontent.com/125552946/219328134-82ed8f63-2045-413a-971b-34398725cde9.png)
![modlist 3](https://user-images.githubusercontent.com/125552946/219328151-f839d342-3863-4045-9961-fa318e3a6e4d.png)

**Comment by math8742** [comment]
This actually seems to be a 8-way mod compatibility issue that is only present when all 8 of the following mods are enabled:
Ad Astra
Rubidium
Connected glass
Create
PneumaticCraft: Repressurized
ChemLib
+some mystery mod in the list I have as of yet been unable to identify
Immersive engineering (which is the mod the rendering issue is caused with). 

Disabling any single one of these mods (except immersive engineering) fixes the issue, so 7 of the mods can be enabled at the same time, but not 8.

**Comment by math8742** [comment]
The mystery mod was mekanism. Forge version is 43.2.4. Pastebin of forced crash log: https://pastebin.com/jaxnLccu

**Comment by math8742** [comment]
Can be reproduced with the following 16 mods:
<img width="1493" alt="modlistbugfull" src="https://user-images.githubusercontent.com/125552946/219389589-4e73d30e-edf9-4224-b4c5-619569130fea.png">

**Comment by Asek3** [comment]
Fixed in 0.6.2a, update mod
