### ISSUE TITLE
[1.16.5] [0.2.11] Crash with Ice and Fire Dragon Pathfinding

### ISSUE THREAD

**Issue by Syrikal** [Asek3/Rubidium#418]
If I had to take a guess, it's this:
- Backported Direction.getFacing optimization

Ice & Fire dragons cause crashes while pathfinding with Rubidium 0.2.11. 0.2.10 does not cause this issue.

The log is here.
[debug-5.log](https://github.com/Asek3/Rubidium/files/10777325/debug-5.log)

Relevant section:

> [19Feb2023 10:07:11.230] [Ice and Fire Pathfinding Worker #0/WARN] [com.github.alexthe666.iceandfire.IceAndFire/]: Pathfinding Exception
> java.lang.IllegalStateException: Unable to get Y-rotated facing of down
> 	at net.minecraft.util.Direction.func_176746_e(Direction.java:170) ~[?:?]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.isPassableBB(AbstractPathJob.java:1361) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.checkHeadBlock(AbstractPathJob.java:1207) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.getGroundHeight(AbstractPathJob.java:1009) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walk(AbstractPathJob.java:879) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.walkCurrentNode(AbstractPathJob.java:657) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.search(AbstractPathJob.java:596) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.PathJobMoveToLocation.search(PathJobMoveToLocation.java:62) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:541) [?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.pathjobs.AbstractPathJob.call(AbstractPathJob.java:46) [?:2.1.11-1.16.5]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
> [19Feb2023 10:07:11.298] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID cd98f55f-b518-4c06-85f6-0f8e1ec28b39
> [19Feb2023 10:07:11.308] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> net.minecraft.crash.ReportedException: Ticking entity
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
> 	at net.minecraft.server.MinecraftServer$$Lambda$14993/1224937848.run(Unknown Source) [?:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
> Caused by: java.lang.NullPointerException
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.processCompletedCalculationResult(AdvancedPathNavigate.java:549) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.pathfinding.raycoms.AdvancedPathNavigate.func_75501_e(AdvancedPathNavigate.java:271) ~[?:2.1.11-1.16.5]
> 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:685) ~[?:?]
> 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?]
> 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
> 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
> 	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?]
> 	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70636_d(EntityDragonBase.java:1728) ~[?:2.1.11-1.16.5]
> 	at com.github.alexthe666.iceandfire.entity.EntityFireDragon.func_70636_d(EntityFireDragon.java:169) ~[?:2.1.11-1.16.5]
> 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?]
> 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
> 	at com.github.alexthe666.iceandfire.entity.EntityDragonBase.func_70071_h_(EntityDragonBase.java:1688) ~[?:2.1.11-1.16.5]
> 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
> 	at net.minecraft.world.server.ServerWorld$$Lambda$15820/1749786644.accept(Unknown Source) ~[?:?]
> 	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
> 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
> 	... 6 more
> [19Feb2023 10:07:11.314] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: E:\Minecraft\.minecraft folders\1.16 Reforged\crash-reports

**Comment by SpecialtyK** [comment]
I am having the same issue. If "Backported Direction.getFacing optimization" is the culprit is there a way to disable just that part in the config and enjoy the rest of the benefits of the update so it can work with Ice and Fire?

**Comment by qwertie64982** [comment]
@SpecialtyK I've been hitting something similar. Downgrading Rubidium to 0.2.10 is my workaround for now

Oops, just noticed you already mentioned the 0.2.10 downgrade temp fix.

**Comment by OverEarth12** [comment]
same with me.

**Comment by qwertie64982** [comment]
One piece of info I don't see above that could be helpful is this:
```
-- Entity being ticked --
Details:
	Entity Type: iceandfire:fire_dragon (com.github.alexthe666.iceandfire.entity.EntityFireDragon)
	Entity ID: 272
	Entity Name: Fire Dragon
	Entity's Exact location: 29.70, 68.85, -207.84
	Entity's Block location: World: (29,68,-208), Chunk: (at 13,4,0 in 1,-13; contains blocks 16,0,-208 to 31,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.06, -0.45, -0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```
I've repro'd this with both hippogryph and fire dragon. World runs fine until an ice and fire creature is spawned in -> crash.

**Comment by Jake0light** [comment]
i had the same problem with this but mine fixed i went back a couple versions 2.1.9 version worked for me hope it fixes for you
(btw i was playing medieval minecraft pack)

**Comment by SpecialtyK** [comment]
So far no crashing with iceandfire-2.1.12-1.16.5.jar

**Comment by Asek3** [comment]
Update Ice & Fire
