### ISSUE TITLE
[1.19.3] [0.6.3] No animations with Rubidium installed.

### ISSUE THREAD

**Issue by twojamama1** [Asek3/Rubidium#419]
Hello. I have a problem.
When I have Rubidium installed, Minecraft has no animations (water, lava, fire, etc.). I have searched all the settings and there is nothing about the animations. Without Rubidium, there are animations. How to fix it?

**Comment by twojamama1** [comment]
Oh, and if i turn off "animate only visible textures" Minecraft crashes with error code -1
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin me.jellysquid.mods.sodium.mixin.features.texture_updates.SpriteInfoAnimationAccessor. The mixin is missing from rubidium.mixins.json which owns package me.jellysquid.mods.sodium.mixin.* and the mixin has not been applied.

**Comment by FrozenDragon0** [comment]
Can confirm I've received the same problem.

**Comment by BJHero14** [comment]
Having exact same problem. If "animate visible textures" is on, lava and water will no longer be animated. If this option is turned off in-game it will crash. If it is turned on at the menu, upon world loading it will crash. Pls fix!!

Exit Code: -1
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin me.jellysquid.mods.sodium.mixin.features.texture_updates.SpriteInfoAnimationAccessor. The mixin is missing from rubidium.mixins.json which owns package me.jellysquid.mods.sodium.mixin.* and the mixin has not been applied.

**Comment by Stanislav228Bebrochka** [comment]
i have another mod, and what you think? rubidium turned off animations for this mod too!

**Comment by Brinkki** [comment]
I have the same issue.

Edit: I found a way to fix it.

**Comment by twojamama1** [comment]
@Brinkki how did you fix it?

**Comment by FrozenDragon0** [comment]
> I have the same issue.
> 
> Edit: I found a way to fix it.

Well? Care to explain the way to fix it?

**Comment by Brinkki** [comment]
> > I have the same issue.
> > Edit: I found a way to fix it.
> 
> Well? Care to explain the way to fix it?

@twojamama1 
@FrozenDragon0 

I turned off the "animate only visible textures" settings (Which results in with the crash), so then I opened the rubidium jar file and edited the "rubidium.mixins.json" file by adding some missing mixins in there (Missing ones are AnimationAccessor, AnimationFrameAccessor, SpriteInfoAccessor and SpriteInfoAnimationAccessor). It worked for me at least.

**Comment by ThymeParadox** [comment]
> 
 How exactly do you do that? Or could you send me the edited file? I've been trying to fix this exact problem

**Comment by Brinkki** [comment]
@ThymeParadox Alright, here is the edited "rubidium.mixins.json" file: https://pastebin.com/ua29P29S (You can open the "rubidium-0.6.3.jar" file with WinRar or 7-Zip, then find the "rubidium.mixins.json" file, then open it and paste the code from my pastebin)

**Comment by ThymeParadox** [comment]
Modified the file with your changes and got this as a result "The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/gui/options/TextProvider" did you get anything like this?

**Comment by ThymeParadox** [comment]
Fix worked, I appreciate it, the bug was bothering me while I was working on my modpack

**Comment by Brinkki** [comment]
@ThymeParadox The pleasure is mine.

**Comment by Asek3** [comment]
Fixed in 0.6.4, update to 1.19.4
