### ISSUE TITLE
[1.16.5] Rubidium and CaveBiomeAPI [Forge] causes an immediate crash on joining a singleplayer world

### ISSUE THREAD

**Issue by varyxc** [Asek3/Rubidium#42]
[crash-2022-03-24_05.46.36-client.txt](https://github.com/Asek3/Rubidium/files/8336928/crash-2022-03-24_05.46.36-client.txt)

cavebiomeapi-1.16.5-1.3.7.jar
rubidium-0.2.2.jar

Launching the game is completely fine. It crashes as soon as I join a singleplayer world.

**Comment by KarinMiku** [comment]
have you tried using latest version of the cavebiomeapi? your version is 1.3.7 and latest one is 1.4.2

**Comment by Asek3** [comment]
Okay, this crash is really annoying and needs to be resolved on CaveBiomeAPI's dev's end

**Comment by Asek3** [comment]
Can't do more than this on my side 🤷‍♂️
![image](https://user-images.githubusercontent.com/64613894/160011254-bc79a0fb-8826-4aac-a7c7-9dedd2f6dad9.png)

**Comment by Asek3** [comment]
Ok, found a way to fix this issue better, but still is awful
![image](https://user-images.githubusercontent.com/64613894/160013244-2398c5d8-bd46-4237-8377-b0c4e646b591.png)
