### ISSUE TITLE
[1.19.3] [0.6.3] Crash

### ISSUE THREAD

**Issue by Zarandolph01** [Asek3/Rubidium#420]
Crashed while loading the world.
https://crashy.net/741a9f9d-bdf5-459a-8e81-b9c1f01e222f
[debug.log](https://github.com/Asek3/Rubidium/files/10778280/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/10778281/latest.log)

**Comment by Zarandolph01** [comment]
Still having this issue.

**Comment by Asek3** [comment]
Fixed in 0.6.4, update to 1.19.4
