### ISSUE TITLE
Invisible Chunks (1.19.2)

### ISSUE THREAD

**Issue by TheRealKuro** [Asek3/Rubidium#422]
Hello, not sure if this is an issue with rubidium or oculus, but since it only appears with those mods and shaders turned on I think this might be the spot to post this issue. (:

![image](https://user-images.githubusercontent.com/126349063/221371431-45bc668e-3beb-4258-8d74-2deca51da39c.png)

You can see that random chunks in the world can't load, and this is not fixable by reloading chunks or anything. I tried to turn on and off every possible option in rubidium and also tried to reinstall my drivers, literally everything, but yea I'm still stuck with this.

Btw, this appeared yesterday, everything worked fine until then.

I'm using Forge 4.3.20 with the newest rubidium and oculus versions for 1.19.2
~144 mods
starlight is also installed
as well as entityculling (in case this is somehow important)
Shader doesn't matter, it happends with any shader, but I'm using complementary reimagined

Thank you in advance

**Comment by Wouink** [comment]
Hi,

Is [Furnish](https://www.curseforge.com/minecraft/mc-mods/furnish) installed in your modpack?
If it is, there is a good chance it might have caused this issue.

It turns out I had made a mistake in my code which caused chunks to not be rendered, event when forcing a reload. I patched the bug in Furnish v21, which is available for download.

Sorry for the inconvenience!
Wouink
_Furnish Dev_

**Comment by agentwolf88** [comment]
Furnish has fixed this problem.

**Comment by TheRealKuro** [comment]
> Hi,
> 
> Is [Furnish](https://www.curseforge.com/minecraft/mc-mods/furnish) installed in your modpack? If it is, there is a good chance it might have caused this issue.
> 
> It turns out I had made a mistake in my code which caused chunks to not be rendered, event when forcing a reload. I patched the bug in Furnish v21, which is available for download.
> 
> Sorry for the inconvenience! Wouink _Furnish Dev_

Thank you very much, furnish was the issue.
Since it's fixed, I will reinstall your mod, of course (:
