### ISSUE TITLE
In world rendering issue with Pneumaticcraft:Repressurized tanks

### ISSUE THREAD

**Issue by Branjoman** [Asek3/Rubidium#427]
When any of the tanks are placed in the world, the rendering of them does not function correctly. Instead of the window being transparent and rendering fluids inside, the window is instead opaque with vertical white and black lines. Screenshot of the issue:
https://i.imgur.com/Tly8k58.jpg
Note that the rendering of the tanks when in your inventory works fine.

Duplicate of the issue over on the Pneumaticcraft:Repressurized github for reference:
https://github.com/TeamPneumatic/pnc-repressurized/issues/1150

Mod Versions:
 - Pneumaticcraft:Repressurized version 4.3.3-22
 - Rubidium version 0.6.2

**Comment by desht** [comment]
I should mention here that this worked OK in 1.18.2 with Rubidium installed.  PNC:R tanks aren't anything special, other than the BER to render fluids (and even with the BER disabled, Rubidium breaks tank rendering in 1.19.2).

Tank model, for reference:  https://github.com/TeamPneumatic/pnc-repressurized/blob/1.19.2/src/main/resources/assets/pneumaticcraft/blockstates/small_tank.json

A pretty standard `multipart` model, consisting of three JSON submodels.  Tanks can stack vertically; stacked tanks exclude the top and/or bottom submodels, hence the multipart blockstate JSON.  Tanks which exclude both the top and bottom submodels actually render OK with Rubidium present, but not when either or both of the top/bottom submodels are present.  Hope that info helps in debugging the issue.

**Comment by Asek3** [comment]
Was fixed in 0.6.2b, update mod
