### ISSUE TITLE
[1.16.5]Render and biome blend issue

### ISSUE THREAD

**Issue by SkullDiamond** [Asek3/Rubidium#43]
![2022-03-25_08 17 34](https://user-images.githubusercontent.com/79324102/160073667-444c8d0f-57de-4022-b20a-72accb809f70.png)

![2022-03-25_08 18 08](https://user-images.githubusercontent.com/79324102/160073679-f71ffd9c-559d-4613-b089-b2a309e25a09.png)

also if I puch the inviseble blocks on the first image the game crash
crah.log:https://pastebin.com/3XiqGsQd

**Comment by Atopik2** [comment]
I have the same biome blend issue
![2022-04-17_16 12 21](https://user-images.githubusercontent.com/73999067/163715940-260498d9-399e-4b81-9a80-4bf6904db7bf.png)
e

**Comment by SkullDiamond** [comment]
any plans for this to fix?

**Comment by ThanEEpic** [comment]
God I hope so because I have this as well.

**Comment by TheVillain-Inc** [comment]
I think this has been double posted. 
https://github.com/Asek3/Rubidium/issues/130

Also, can confirm this is happening for me also.
![2022-05-26_19 09 24](https://user-images.githubusercontent.com/25729205/170550416-7262c7ed-a84a-4381-b755-7faa97327ccf.png)

**Comment by SkullDiamond** [comment]
Is 1.16.5 unsupported ?

**Comment by Asek3** [comment]
forgot to answer the issue, was fixed in 0.2.7
