### ISSUE TITLE
[1.19.2] [0.6.2] No animations with Rubidium installed (with texturepack/resourcepack "FreshAnimations" and others)

### ISSUE THREAD

**Issue by PixelSymbols** [Asek3/Rubidium#433]
Hello. I have a problem, maybe the same as the other guy (read further).
When I have Rubidium installed, Minecraft has not only no animations as they should be (mobs) but also their eyes are gone xd
( https://media.discordapp.net/attachments/997199746114523158/1085234693722619965/image.png?width=515&height=683 )

but also connected textures texturepack/resoursepack wont work either
( https://media.discordapp.net/attachments/1024715657473962098/1085240357115138198/image.png?width=860&height=190 )

i saw you fixed it for 1.19.3 version ( https://github.com/Asek3/Rubidium/issues/419 ), so can you fix it for 1.19.2 please?

Without Rubidium, there are animations and everything works smoothly.

**Comment by Asek3** [comment]
I sure they won't work without Rubidium cuz these resourcepacks is for Optifine.
Rubidium is optimization mod and not contains Optifine specific features as CTM or Custom Entity Models
