### ISSUE TITLE
Incompatibility with Snow Real Magic [1.19.2]

### ISSUE THREAD

**Issue by Jusey1** [Asek3/Rubidium#439]
Minecraft: 1.19.2
Forge: 43.2.4
Snow Real Magic: 6.4.4
Rubidium: 0.6.2a

I really love the Snow Real Magic mod but it breaks a bit with Rubidium by causing a lot of z-fighting with the snow layers on stairs, slabs, and full blocks while also causing snowed plants to become invisible, which can be used for cheating on servers for example:
![Untitled](https://user-images.githubusercontent.com/61861078/226999429-3a28e4f7-f235-425e-bdd4-d57fb5604e5a.png)

The z-fighting and invisible blocks only happens when the mod is with Rubidium so I ain't sure what's going on completely... Also to note that the z-fighting only happens on two sides of the blocks on average and doesn't happen at all on snowed fences and gates.

**Comment by Asek3** [comment]
Should be fixed on their side
