### ISSUE TITLE
Crash and chunks all over the place with Immersive Engineering mod on 1.18.2

### ISSUE THREAD

**Issue by spader1302** [Asek3/Rubidium#441]
With the new Rubidium and Oculus update, I get this weird chunk loading issue and crash a few seconds after I load into a new world. It only happens with the Immersive Engineering mod enabled, will also report on their end.

Minecraft: 1.18.2
Forge: 40.2.1
Rubidium: 0.5.5
Oculus: 1.5.2
Immersive Engineering: 1.18.2-8.4.0-161

Crash report: https://mclo.gs/3r5PTGL

![2023-03-23_18 49 34](https://user-images.githubusercontent.com/76409510/227302275-6a01e1bc-0cb8-4a9b-86eb-6aba75d55e60.png)

**Comment by spader1302** [comment]
#https://github.com/BluSunrize/ImmersiveEngineering/issues/5629

**Comment by Dr-WeiAL** [comment]
![2023-03-24_06 13 00](https://user-images.githubusercontent.com/47446553/227376681-245f46c3-7909-4a06-9858-de68150a59ae.png)
I also encountered this problem

**Comment by Shibva** [comment]
IE will most likely not fix this. It must be one of the changes made between 0.5.4 and 0.5.5; however, I can assure you that #417 is not what's causing it. I have tested a version of 0.5.4 and swaped out that mixin file that was changed in 417 and this rendering issue does not exist while the patch itself works.

**Comment by emanuele246gi** [comment]
Yeah but is there a solution?

**Comment by radiomike** [comment]
Try adding `mixin.features.chunk_rendering=false` to `config/rubidium-mixins.properties`
This fixes the rendering issues with IE for me.

**Comment by emanuele246gi** [comment]
Could this be the reason I can't see animated textures? They are still

**Comment by xSyphel** [comment]
Came here to say, that I too am experiencing this issue, been trying to figure out what it is as I've updated rubidium to 0.5.5.
