### ISSUE TITLE
Crash with Rubidium

### ISSUE THREAD

**Issue by ghost** [Asek3/Rubidium#446]
https://paste.gg/p/anonymous/f45c6e511f2c4ae48316263ccd092f16

**Comment by ScarlettQueen** [comment]
Downgrade to 0.5.4

**Comment by ghost** [comment]
It wasn't Rubidium I tried run Rubidium + Magnesium together or something lol, still, is there a chance that Immersive Portals will works with Rubidium on 1.16.5?

**Comment by Kasualix** [comment]
Impossible.
Immersive Portals has stopped supporting 1.16.5 Forge for a long time.

**Comment by ghost** [comment]
Why matter, it's about Rubidium

**Comment by Asek3** [comment]
Compatibility with Immersive Portals should be fixed on their side
