### ISSUE TITLE
I've a glitch visual with the new update of Rubidium

### ISSUE THREAD

**Issue by Vincy-2515** [Asek3/Rubidium#447]
https://user-images.githubusercontent.com/110780936/227783260-a4dc1a46-3ac1-45a4-8ae1-52cdef7b8999.mp4

Since I installed the new Rubidium update I started having this problem, how can I fix it?

**Comment by tiagopestanak** [comment]
Downgrade your Rubidium version, to 0.5.4. That should fix your issue.

**Comment by Sukid** [comment]
I'm also getting a lot of invisible chunks and it stopped when I disabled Rubidium. But then I made an instance with nothing but Rubidum installed and it worked perfectly fine. So there might be a mod conflict going on somewhere, just not sure where... I'll get disabling and loading and see what happens.

EDIT: It might be Distant Horizons? I turned that off and it was fine.

**Comment by Enderteck** [comment]
> [Vhincy](/Vhincy)

I have the same problem with the last version of rubidium and oculus for 1.18.2

**Comment by emanuele246gi** [comment]
Same for me but with Immersive Engineering

**Comment by Vincy-2515** [comment]
> Same for me but with Immersive Engineering

I actually have Immersive Engineering in my modpack

**Comment by oliverrook** [comment]
Same here.

**Comment by Lordmau5** [comment]
> EDIT: It might be Distant Horizons? I turned that off and it was fine.

In that case that means it's another mod that also causes these issues.

I'm currently playing the FTB StoneBlock 3 v1.6.1 pack and it works fine with Rubidium v0.5.4, but v0.5.5 brings in these rendering issues.

I also have no idea which blocks in particular are causing these issues unfortunately, as the log doesn't mention anything.

**Comment by Sukid** [comment]
It might have just been a Forge issue. Not seeing it anymore

**Comment by Asek3** [comment]
Update Rubidium

**Comment by Vincy-2515** [comment]
> Update Rubidium
Thank you very much, now everything works perfectly
