### ISSUE TITLE
Texture Glitch with Immersive Engineering wooden post

### ISSUE THREAD

**Issue by rrrr4201** [Asek3/Rubidium#451]
![Texture issue](https://user-images.githubusercontent.com/129680167/229365662-ba09a1e3-d97f-4dda-bb65-1e729cb8c6ff.png)

As the image above shows, the Immersive Engineering wooden post has abnormal line patterns in its texture.
Applying/not applying the shader DOES NOT fix the glitch; the wooden post looks identically glitched.
*Note: aluminium and steel posts look absolutely normal

Minecraft version: 1.19.2
Rubidium version: 0.6.2a
Immersive Engineering version: 1.91.2-9.2.0-162

Does anybody know how to fix this issue?

**Comment by Asek3** [comment]
Fixed in 0.6.2b

**Comment by rrrr4201** [comment]
> Fixed in 0.6.2b

Thank you for your diligent work and kind assistance. Would you please delete this issue then? Thanks.
