### ISSUE TITLE
Game freezes randomly with rubidium.

### ISSUE THREAD

**Issue by Nediamail05** [Asek3/Rubidium#453]
So whenever I play with rubidium my game will randomly freeze, but not crash. Then seconds later with unfreeze everything but my video. So I can move, and hear sounds, but not see. I have an i7 processor, rtx 3070, and 8gb of ram so I have more than enough. Lmk if you want me to test some things or experiment.

**Comment by Nediamail05** [comment]
So I figured out something. According to nvidia overlay rubidium disables my gpu. Like literally 0% usage.

**Comment by MagmaSlime123** [comment]
The game will simply crash on world join/creation for me.

https://pastebin.com/FmyTEggY

**Comment by MagmaSlime123** [comment]
@Nediamail05 Try Embeddium.
