### ISSUE TITLE
Crashes on world creation/join.

### ISSUE THREAD

**Issue by MagmaSlime123** [Asek3/Rubidium#454]
Title. Modlist in report.

https://pastebin.com/FmyTEggY

**Comment by VOLKOUL** [comment]
Same here, posted an issue a while back
Am using 1.18.2 0.5.5

**Comment by VOLKOUL** [comment]
FOUND OUT WHY (on my modpack)
**Update SnowRealMagic** and/or **3DSkinLayers**
Also Immersive Engineering is _veeery_ bugged with Rubidium 0.5.5

**Comment by monkeyzone456** [comment]
theres a bugreport on here where if you go to rhubidium-mixins in the config and add 
mixin.features.chunk_rendering=false
it fixed it at least for me

**Comment by Asek3** [comment]
Update Rubidium
