### ISSUE TITLE
[1.18.2] IMMERSIVE ENGINEERING IS GOING BONKERS (chunk glitch)

### ISSUE THREAD

**Issue by VOLKOUL** [Asek3/Rubidium#457]
So apparently it is claimed on Immersive Engineering's issue tab that it it a Rubidium 0.5.5 issue.
**It's like cubic chunks got splattered all over the place.**
There are screenshots both on their issues tab as well as on this one, a few publications back: https://github.com/Asek3/Rubidium/issues/441
Btw, I am aware that it can be "fixed" by adding mixin.features.chunk_rendering=false to config/rubidium-mixins.properties, but it creates weird animation glitches (water, kelp for example), makes trees have what seems to be -∞ mipmaps and also decreases fps.

DIS BETTAH BE FIXED [insert angry anvil sound ^^]

**Comment by Sky-Evil** [comment]
The same problem, only in my case adding mixin.features.chunk_rendering=false greatly reduces fps and causes freezes

**Comment by MCJEModder2026** [comment]
same?

or is this something else
![image](https://user-images.githubusercontent.com/78447517/232212862-d5db5909-3023-4deb-92b7-65abec0570cd.png)

**Comment by Asek3** [comment]
Update Rubidium
