### ISSUE TITLE
[1.16.5] Everytime I enter the nether with rubidium my game crashes.

### ISSUE THREAD

**Issue by ForzaWasTaken** [Asek3/Rubidium#461]
It works fine without rubidium but its laggy and i've tried to roll back my graphic drivers to 522.25  and rolling back by one version of rubidium. I have also tried to pre generate the nether as well but it doesn't work and I think it happens with every dimension as well (however i'm not 100% sure because I haven't tried)

Crash report: https://bytebin.lucko.me/O8jEYldKU6

**Comment by Kasualix** [comment]
inspirations-client.toml→turn off customPortalColor

**Comment by ForzaWasTaken** [comment]
> inspirations-client.toml→turn off customPortalColor

Ok Ill try

**Comment by ForzaWasTaken** [comment]
> inspirations-client.toml→turn off customPortalColor

Wow. Thank you it worked
