### ISSUE TITLE
1.18.2 - version 0.5.5 - Crash with immersive portals + shimmer

### ISSUE THREAD

**Issue by maxim0p** [Asek3/Rubidium#462]
[crash log](https://pastebin.com/EZWCbEqR)

Immersive portals and shimmer work together, but crashes when rubidium is installed. 
The crash happens when loading into a world.

Edit: I would also like to add that rubidium works with immersive portals and shimmer individually, but crashes when they are together, so I'm assuming its a rubidium issue, not the other mods.

**Comment by Asek3** [comment]
Related to Immersive Portals, not Rubidium

**Comment by Lolothepro** [comment]
Shimmer is only supported from Iris 1.6.0
