### ISSUE TITLE
Rubidium crash in my modpack

### ISSUE THREAD

**Issue by TysonTheEmber** [Asek3/Rubidium#463]
[EmberCraft bad.zip](https://github.com/Asek3/Rubidium/files/11227186/EmberCraft.bad.zip)
crash log- https://mclo.gs/VbxtS4r

**Comment by TainanRezende** [comment]
I have the same problem in version 0.5.5

**Comment by Kasualix** [comment]
remove chunkanimator.

**Comment by TysonTheEmber** [comment]
thx

**Comment by TysonTheEmber** [comment]
then this happens https://mclo.gs/kEwxwhs

**Comment by Asek3** [comment]
Update Rubidium
