### ISSUE TITLE
1.18.2 - version 0.5.5 - Minecraft loading bar not moving

### ISSUE THREAD

**Issue by ghost** [Asek3/Rubidium#464]
So when I open minecraft forge with rubidium, the loading bar doesn't move, and after a few seconds, minecraft says it's not responding, and it's going to stay like that forever, I left my computer running minecraft overnight and it didn't change.
![Screenshot_1](https://user-images.githubusercontent.com/56805779/232245674-8a4a85b4-ccb1-4ea5-a785-73b3d1cd79ab.png)

**Comment by VOLKOUL** [comment]
Probably an issue with another mod. When Rubidium updates some mods must be updated too. How to find which one? 
**M A N U A L L Y___O N E___B Y___O N E** (well, at least that's how _I_ did it)
In my case it was SnowRealMagic, yours must be different. P.S: _GLHV!_
(I should probably mention that this is but a mere speculation and your issue might be of completely unrelated origin)

**Comment by ghost** [comment]
I think this is not a problem with another mod, because this happens even when I open Minecraft with just Rubidium.

**Comment by VOLKOUL** [comment]
Rubidium just had an update, might be fixed now)

**Comment by ghost** [comment]
no, i think that the problem is with my computer, but thx for the help

**Comment by ghost** [comment]
and I discovered the problem, my computer didn't have Java 8 installed
