### ISSUE TITLE
[1.16.5] Invisible Textures and Water

### ISSUE THREAD

**Issue by Damien1991** [Asek3/Rubidium#47]
With Rubidium:
![2022-03-31_14 20 18](https://user-images.githubusercontent.com/100287649/161056208-284bda82-6dac-4fd6-b291-88dc85ecc0c7.png)
Without Rubidium:
![2022-04-01_12 36 17](https://user-images.githubusercontent.com/100287649/161247675-df279b49-fffd-4385-9ae9-4b0e93d9aac7.png)

I also had the same issue with magnesium.

**Comment by Asek3** [comment]
Try to use with https://www.curseforge.com/minecraft/mc-mods/magnesium-extras

**Comment by Damien1991** [comment]
I have tested the mod in other packs and it seems to specifically be the pack that I was trying to use, FTB ocean block must have a mod conflicting and causing the graphical issues. Running it with vanilla + forge gives no issues, FTB university also works without any issues.

**Comment by Damien1991** [comment]
If someone else is facing this issue, I have a workaround for now. if you install this mod: https://www.curseforge.com/minecraft/mc-mods/calcium and combine it with magnesium (its not compatible with rubidium, even though it mentions the mod). This seems to resolve the missing textures issue.

**Comment by lenase0077** [comment]
U find another solution? I want to use oculus :c

**Comment by Asek3** [comment]
Should be fixed on latest Rubidium's versions
