### ISSUE TITLE
[1.16.5] Crashing after adding Rubidium

### ISSUE THREAD

**Issue by Subthy** [Asek3/Rubidium#477]
So, I heard that this mod helps people a lot and is way better than Optifine, but when I added it to my pack it just keeps crashing it unlike Optifine.

The crash is in the latest log, as it didn't generate a crash report
[latest.log](https://github.com/Asek3/Rubidium/files/11360302/latest.log)

**Comment by Kasualix** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-potato-edition

**Comment by Subthy** [comment]
Thanks, that worked
