### ISSUE TITLE
This mod is causing Ice and Fire dragons to NOT WALK.

### ISSUE THREAD

**Issue by jpaulo-rb** [Asek3/Rubidium#489]
Using this mod together with Ice and Fire causes dragons to stop moving
They are able to fly, attack, jump, and do other things, but they don't walk, they simply stay still or fly
I tested it using only those two mods, and the error persisted

MC - 1.18.2 ;   Forge - 40.2.2
Ice and Fire - 2.1.12 beta2 ;   Citadel - 1.11.3
Rubidium - 0.5.6

![image](https://github.com/Asek3/Rubidium/assets/77559222/a4356184-f321-4965-b2c4-12e1a0867d9d)

**Comment by Asek3** [comment]
Update Ice & Fire
