### ISSUE TITLE
[1.18.1] Visual glitches with Vampirism's Blood Containers

### ISSUE THREAD

**Issue by AzaleaFlame59** [Asek3/Rubidium#49]
Vampirism and Ender Chests mods both have visual glitches with Rubidium. I have made separate posts for each. I do have many other mods (around 150), but every time I disable Rubidium, they're fixed, and when I enable it, they're broke (so it could be a mix issue, but I don't think so as I'm pretty sure I once disabled every other mod but these 3, if not almost every other mod)
A note, I haven't really posted on here before, so apologies if anything doesn't show up quite like it should.

Vampirism's blood containers
- Issue is when the container has any amount of blood in it, the south and east faces are completely invisible as if the container is empty (except it isn't empty), and the north and west faces flicker like crazy.
- How to recreate: Install Rubidium & Vampirism, latest 1.18.1 versions (1.8.0 for vampirism, 0.5.0 for Rubidium), load up a singleplayer world, place a filled "blood container" from creative inventory, and look at it.
![2022-03-31_19 35 58](https://user-images.githubusercontent.com/43221064/161185522-a08bd294-f1b6-44ad-9ccb-4256e7292735.png)
![2022-03-31_19 35 51](https://user-images.githubusercontent.com/43221064/161185525-142980dc-ed41-4953-bf47-21169759a8e3.png)

**Comment by guivnf** [comment]
I'm having a simmilar issue, vampirism has an altar that should've been filled with blood, its working just fine, but visually its empty, 
![image](https://github.com/Asek3/Rubidium/assets/77132244/843e2a44-446d-465e-b0a3-089cb68bcb16)
