### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by Maikidott** [Asek3/Rubidium#491]
Minecraft launcher says it's an exit code 1 error. Log is included. Game was only crashing after I installed Rubidium.
[latest.log](https://github.com/Asek3/Rubidium/files/11472426/latest.log)

**Comment by Kasualix** [comment]
not a rubidium issue at all 
Do you install FABRIC Chunk Pregenerator?
https://github.com/jaskarth/fabric-chunkpregenerator/blob/master/src/main/resources/chunkpregen.mixins.json

**Comment by Kasualix** [comment]
Oh, I got it, seems you are using stupid CurseForge launcher lol
![image](https://github.com/Asek3/Rubidium/assets/110756250/8a991c14-831f-4fb3-9da2-b77537538a74)

**Comment by Maikidott** [comment]
Even after removing chunk pregenerator the game still crashes.

**Comment by Kasualix** [comment]
latest log

**Comment by Maikidott** [comment]
[here it is](https://github.com/Asek3/Rubidium/files/11472546/latest.log)

**Comment by Kasualix** [comment]
Still not a rubidium issue
install [this](https://www.curseforge.com/minecraft/mc-mods/night-config-fixes) to fix

**Comment by Maikidott** [comment]
[The game still crashes.](https://github.com/Asek3/Rubidium/files/11472560/latest.log) Also, I wasn't sure if it was Rubidium specifically, but the crashes only happen when it's installed.

**Comment by Kasualix** [comment]
I'm sure it definitely has nothing to do with Rubidium.
This time your config/fml.toml went wrong and crashed the game just as Night Config Fixes CurseForge desc tells.
You'd better check it out and delete to reset it.

**Comment by Maikidott** [comment]
Seems like it's fixed now. Thanks for the help even though it wasn't Rubidium (sorry)
