### ISSUE TITLE
Immersive Engineering wire is invisible 1.19.4

### ISSUE THREAD

**Issue by DavidGmc18** [Asek3/Rubidium#492]
![2023-05-16_18 24 34](https://github.com/Asek3/Rubidium/assets/108219222/039c746a-eb67-4ec7-8b6e-1838c1d8820f)
This connectors and relay is connected with LV wire, but it is not visible. MV and HV wires are not visible too.
Without Rubidium wires are visible. 
Rubidium version: 0.6.4
MC version: 1.19.4
Forge version: 45.0.63 
Immersive Engineering version: 1.19.4-9.4.0-166

**Comment by Tursiops-G** [comment]
Having same issue.
Same Mod versions,
Forge Version 45.0.64

Without Rubidium:
![Without Rubidium](https://github.com/Asek3/Rubidium/assets/97983160/ec340f72-041e-4356-9676-a609c5b7a820)
With Rubidium:
![With Rubidium](https://github.com/Asek3/Rubidium/assets/97983160/1ef00c82-e299-4217-bb34-f2ab6382bec7)

**Comment by simonwoegerb** [comment]
this issue is still occurring for me as well on the most up-to-date versions of everything. quite annoying, as my friends game is unplayable on our modpack without rubidium.

**Comment by Asek3** [comment]
1.19.4 is abandoned
