### ISSUE TITLE
Conflicting between Rubidium and unknown mods, causes crash when injected

### ISSUE THREAD

**Issue by milkmoemoe** [Asek3/Rubidium#493]
I pretty much just need help with finding out exactly which mods are conflicting with Rubidium so I may utilize it in my personal mod pack, it would be much appreciated : )

Here's the console log

https://paste.atlauncher.com/view/a1ac6265-2e99-4f6e-a457-1b61b3d54109

**Comment by 48004800** [comment]
Optifine

**Comment by milkmoemoe** [comment]
> 48004800

damn
that sucks
