### ISSUE TITLE
Unloaded Chunks in 1.19.4

### ISSUE THREAD

**Issue by Steve982950** [Asek3/Rubidium#495]
Version:
1.19.4

Mod version:
0.6.4

Description:
When I installed 1.19.4 Rubidium, THERE WERE UNLOADED CHUNKS! FIX NOW! 😡😡😡😡😡

Screenshots:
![krlurOg](https://github.com/Asek3/Rubidium/assets/128298281/554a03b0-f4f1-49c5-9cfc-1652c6e45881)

**Comment by u7f8au7fbd** [comment]
The bug that causes chunks to be hidden is from sodium.

**Comment by Steve982950** [comment]
WELL THEN ''HELPER OF ASEK'' ASK ASEK TO FIX THIS! IT RUINS MY GAME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by u7f8au7fbd** [comment]
Try disabling the following items. There is a possibility that this may solve the problem.

Video Setting➡Performance ➡Use Block Face Culling

Sodium has had cases where the above techniques have solved the problem. Please give it a try.

**Comment by Steve982950** [comment]
ok. TY

**Comment by u7f8au7fbd** [comment]
Is this problem solved?

**Comment by Steve982950** [comment]
For the moment...yes

**Comment by Steve982950** [comment]
> For the moment...yes

EDIT: It STILL Happens. SO IT DIDNT WORK!!!! If AsekHelper=true, pls ask him to fix it manually without changing settings.
                                                       Translation: If you are a helper of Asek, pls tell him to fix it.

**Comment by Lolothepro** [comment]
> > For the moment...yes
> 
> EDIT: It STILL Happens. SO IT DIDNT WORK!!!! If AsekHelper=true, pls ask him to fix it manually without changing settings. Translation: If you are a helper of Asek, pls tell him to fix it.

Wait for this bug to be fixed. (https://github.com/Asek3/Rubidium/pull/448)

**Comment by bipsydev** [comment]
In case anyone else finds this and is in dire need of this fix, [here's a current dev build including the PR that fixes this incompatibility with The Aether](https://drive.google.com/file/d/1Y2rUojTOgOq2gWL0T2fsgqRGLuzw89Si/view?usp=sharing) I made just for you!

**Comment by Steve982950** [comment]
OMG TY! hope this works
