### ISSUE TITLE
[1.18.1] Visual glitches with EnderChest's colour bands.

### ISSUE THREAD

**Issue by AzaleaFlame59** [Asek3/Rubidium#50]
Vampirism and Ender Chests mods both have visual glitches with Rubidium. I have made separate posts for each. I do have many other mods (around 150), but every time I disable Rubidium, they're fixed, and when I enable it, they're broke (so it could be a mix issue, but I don't think so as I'm pretty sure I once disabled every other mod but these 3, if not almost every other mod)
A note, I haven't really posted on here before, so apologies if anything doesn't show up quite like it should.

Ender Chests' colour bands
- Issue is when placed, the bands of colour on the ender chests are.. I'm not sure the right words, but like someone threw in too much white/dulled the colours. You can only very barely see that there's any colour at all, it might as well be white. Interestingly, when placing multiple in a line, the center gets slightly more saturated (really only noticeable when placing in my opinion, but it's there nonetheless)
- How to recreate: Install Rubidium & EnderChests, latest 1.18.1 versions (1.9.2 for EnderChests, 0.5.0 for Rubidium), load up a singleplayer world, place any of the "Ender Chest" blocks with coloured bands on them from the creative inventory, and look at it.
- For reference in the pictures - top band is blue, middle is cyan, bottom is green, for all of the ender chests. This occurs for every colour.
![2022-03-31_20 01 46](https://user-images.githubusercontent.com/43221064/161188635-7954b739-1195-4dee-a88e-a7551e23e93d.png)
![2022-03-31_20 05 59](https://user-images.githubusercontent.com/43221064/161188639-1b8562d8-1cec-4fc6-9c9d-b5527cf3394d.png)

**Comment by Asek3** [comment]
Fixed on 1.18.2
