### ISSUE TITLE
Stoneblock 3 1.7.1 Error loading oculus-mc1.18.2-1.6.4 + rubidium-0.6.5

### ISSUE THREAD

**Issue by brainshead** [Asek3/Rubidium#526]
Stoneblock 3 stops loading while added these 2 addons.
Oculus only loaded works fine(but will say its missing Rubidium)
when adding  Rubidium the minecraft  crashes .
Remove both mods , it is loading fine with no problems.

[debug.log](https://github.com/Asek3/Rubidium/files/11995351/debug.log)

**Comment by Asek3** [comment]
Fixed in dev https://github.com/Asek3/Rubidium/commit/2099882e05a2749400886391a5aa274fe4689363
