### ISSUE TITLE
[1.19.2] [Rubidium 0.6.2b] Square visible underwater through glass ceiling

### ISSUE THREAD

**Issue by Khauvinkh** [Asek3/Rubidium#528]
Hello.

When underwater, viewing the surface through a glass or ice ceiling reveals a square of a different color.
I think it's only visible through the horizontal faces of the glass blocks.

Forge 43.2.14, Rubidium 0.6.2b is the only installed mod.

![ReproductionStructure](https://github.com/Asek3/Rubidium/assets/16191072/53dc22d7-0889-4bc1-8756-c766e237e277)
![BugVisible](https://github.com/Asek3/Rubidium/assets/16191072/3449f63a-45ff-4fc9-a99b-51be696a7124)
![OnlyHorizontal](https://github.com/Asek3/Rubidium/assets/16191072/ad6bd8f2-5518-49df-8791-0cc0ac2529a0)

**Comment by Asek3** [comment]
Related to translucency sorting which cannot be fixed by me
