### ISSUE TITLE
server crashing after adding rubidium

### ISSUE THREAD

**Issue by yollk** [Asek3/Rubidium#53]
I added rubidium and oculus to the mods folder and now every time I try to start the server it just stops after a few seconds, the last console info is this:
![obraz](https://user-images.githubusercontent.com/102907174/161428085-262d1da1-8b90-4666-aa3a-c55cc6bf3d7d.png)

simultaneously, the same mods work flawlessly on clients (modpacks for the client and the server are exactly the same)

any ideas about what is this all about?

**Comment by Asek3** [comment]
dude wtf

**Comment by Asek3** [comment]
this is clientside only mods

**Comment by yollk** [comment]
yeah but when modpacks differ between the client and the server, trying to connect fails. is there any way to use rubidium on multiplayer mode then?

**Comment by HydrogenC** [comment]
> yeah but when modpacks differ between the client and the server, trying to connect fails. is there any way to use rubidium on multiplayer mode then?

That won't happen for client-only mods. It's OK to connect to a server without some client-only mods.
