### ISSUE TITLE
[1.18.2] Immersive Engineering Rendering Issues

### ISSUE THREAD

**Issue by rowanthemodder** [Asek3/Rubidium#54]
# Forge Version:
40.0.19
# Modlist:
- Immersive Engineering 1.18.2 8.0.0
- Rubidium 0.5.1a
# Issues
- IE post models are messed up
- Stained and tinted glass on conveyors isn't transparent
- Lantern model always takes on the same model despite a different blockstate
- Wires and cables don't render at all (Those are linked connectors with LV wire and steel cables)
![image](https://user-images.githubusercontent.com/46363164/161537892-bc01a645-8403-4d55-aea4-614ef2896055.png)
- Razor wire connected model endpoints are flipped
![image](https://user-images.githubusercontent.com/46363164/161538875-96f2d77a-3652-48cf-b963-ddf6ad2da892.png)

**Comment by samiam567** [comment]
I am having the same issue

**Comment by Asek3** [comment]
Probably resolved every issue, except invinsible wires

**Comment by mszabolcs-dev** [comment]
### Forge Version:
40.0.52

### Modlist:
ImmersiveEngineering-1.18.2-8.0.1-147.jar
rubidium-0.5.2a.jar

### Resolved:
- IE post model are good
- Lantern model takes the correct model

### Issues:
- invinsible wires (As you mentioned its still not fixed)
- Razor wire connected model endpoints are still flipped
![image](https://user-images.githubusercontent.com/11245344/167914469-228fa10c-2da4-443b-a352-9c3fb505c67a.png)
