### ISSUE TITLE
I need to change the shaders reload hotkey.

### ISSUE THREAD

**Issue by ZealBlox** [Asek3/Rubidium#544]
How do you change the shaders reload hotkey? I am using a mod called epic fight and whenever I press R when I go in combat mode. It reloads my shaders. Can you help me figure out how to change the hotkey?

**Comment by Ludi87** [comment]
In your controls

![image](https://github.com/Asek3/Rubidium/assets/13112051/9eb717a1-3631-4cbc-bc7a-a83007a5551f)
