### ISSUE TITLE
Rubidium crashes when combined with Twilight Forest

### ISSUE THREAD

**Issue by TheeStickmahn** [Asek3/Rubidium#548]
MC - 1.20.1
Forge - 47.1.30
Rubidium - 0.6.5

[latest.log](https://github.com/Asek3/Rubidium/files/12267717/latest.log)
[latest_crash.txt](https://github.com/Asek3/Rubidium/files/12267718/crash-2023-08-05_19.04.05-client.txt)

Game crashes while loading mods.

**Comment by Asek3** [comment]
Related to BetterFPSDist
