### ISSUE TITLE
Crash with Sophisticated Storage [1.20.1 - Forge 47.1.43]

### ISSUE THREAD

**Issue by RawlethS** [Asek3/Rubidium#551]
I don't know if this would be relevant posting it here, but I'll post anyways. I've already posted on the other mod's page.

Crash on boot up.

MC Version: 1.20.1
Forge Version: 47.1.43 (also crashed on 47.1.1 and 47.1.3)

Mod list:
Rubidium 1.20.1-0.7.0a
Sophisticated Core 1.20.1-0.5.83.395
Sophisticated Storage 1.20.1-0.8.44.571

Log:
https://mclo.gs/fTOVO2q

**Comment by Asek3** [comment]
Report to Sophisticated Storage dev
