### ISSUE TITLE
Game crashes when loading world...

### ISSUE THREAD

**Issue by Gantros** [Asek3/Rubidium#552]
The game boots to the main menu fine, but when I start up my world, it gets to 100% and then crashes to desktop:

Minecraft v1.21.1
Forge v47.1.43
Rubidium v0.7.0a

https://pastebin.com/ptx9QKQ7

**Comment by BugmanBugman** [comment]
Getting this too

**Comment by Asek3** [comment]
Report to Snow Real Magic devs
