### ISSUE TITLE
Rubidium 0.7.0a x 1.20.1

### ISSUE THREAD

**Issue by aNinjin** [Asek3/Rubidium#554]
**Minecraft Version:** _1.20.1_
**Forge Version:** _47.1.1_

Rubidium 0.6.5 works perfectly fine when installed. I ran into crashes on start when updating to 0.7.0. The next update, 0.7.0a seems to be doing the same thing. I get no crash logs generated nor does the latest.log have anything useful to tell me why/what is causing it. I do know it's rubidium since if I go back to 0.6.5, my game doesn't crash.

This is a crash on startup.

Let me know if you need me to help troubleshoot this issue :).

**Comment by SiverDX** [comment]
https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/

or

https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/

**Comment by aNinjin** [comment]
Game output: https://paste.gg/p/anonymous/d45bbc28f5544fbc811584f8b915d3e5
Launcher_log: https://paste.gg/p/anonymous/25c3a9ca7b2a439a862cdccd03301cb3 (Looks like the crash happens at line 5054).

**Comment by aNinjin** [comment]
> https://minecrafthopper.net/help/guides/getting-minecraft-launcher-log/
> 
> or
> 
> https://minecrafthopper.net/help/guides/getting-minecraft-game-output-log/

Here are those files. I didn't know these logs even existed.

Game output: https://paste.gg/p/anonymous/d45bbc28f5544fbc811584f8b915d3e5
Launcher_log: https://paste.gg/p/anonymous/25c3a9ca7b2a439a862cdccd03301cb3 (Looks like the crash happens at line 5054).

**Comment by SiverDX** [comment]
oculus is not yet compatible with the latest rubidium version

**Comment by aNinjin** [comment]
> oculus is not yet compatible with the latest rubidium version

I was thinking that was the case but I didn't want to assume. Should I bring this to their attention or just leave it be?

**Comment by SiverDX** [comment]
the dev is aware, they mentioned it in the rubidium update announcement after all 

(rubidium and oculus dev is the same person)

**Comment by aNinjin** [comment]
> the dev is aware, they mentioned it in the rubidium update announcement after all
> 
> (rubidium and oculus dev is the same person)

I did not know that! oops.
Where do they post announcements at?

**Comment by SiverDX** [comment]
in the discord, its linked here: https://www.curseforge.com/minecraft/mc-mods/rubidium
