### ISSUE TITLE
[1.20.1] - Transparency on modded blocks not rendering properly

### ISSUE THREAD

**Issue by ImTheLion** [Asek3/Rubidium#557]
**Versions:**
- Forge: 47.1.43
- Minecraft: 1.20.1
- Rubidium: 0.7.0

**Issue:**
Modded Blocks which require full or semi-transparency render without transparency. Vanilla blocks ***DO NOT*** have the same issue.

**Without Rubidium:**
![2023-08-07_15 09 36](https://github.com/Asek3/Rubidium/assets/85840208/5a1a1c09-211b-4885-ad08-d66ab64b630a)

**With Rubidium:**
![2023-08-07_15 18 33](https://github.com/Asek3/Rubidium/assets/85840208/ea7a1e05-b9c7-4c85-a159-6579b19f9e02)

**Mod list:**
client-1.20.1-20230612.114412-srg.jar   
rsrequestify-1.20.1-2.3.2.jar           
torchmaster-20.1.4.jar                  
trade-cycling-forge-1.20.1-1.0.7.jar    
fullbrightnesstoggle-1.20.1-3.0.jar     
moonlight-1.20-2.7.2-forge.jar          
Compressium-3.0.2-build.12+mc1.20.jar   
jei-1.20.1-forge-15.2.0.23.jar          
spectrelib-forge-0.13.12+1.20.1.jar     
easy_villagers-1.20.1-1.0.12.jar        
rubidium-mc1.20.1-0.7.0.jar             
flywheel-forge-1.20-0.6.9-4.jar         
create-1.20.1-0.5.1.d.jar               
waystones-forge-1.20-14.0.1.jar         
collective-1.20.1-6.65.jar              
Controlling-forge-1.20.1-12.0.2.jar     
Searchables-forge-1.20.1-1.0.1.jar      
polymorph-forge-0.49.0+1.20.1.jar       
comforts-forge-6.3.3+1.20.1.jar         
storagedrawers-1.20.1-12.0.2.jar        
NaturesCompass-1.20.1-1.11.1-forge.jar  
elevatorid-1.20.1-1.8.14.jar            
cfm-forge-1.20.1-7.0.0-pre36.jar        
ferritecore-6.0.0-forge.jar             
balm-forge-1.20-7.0.7.jar               
Terralith_1.20.1_v2.4.3.jar             
justzoom_forge_1.0.2_MC_1.20.1.jar      
mininggadgets-1.15.0.jar                
JustEnoughResources-1.20.1-1.4.0.222.jar
forge-1.20.1-47.1.43-universal.jar      
supplementaries-1.20-2.5.21.jar         
refinedstorage-1.12.3.jar               
refinedstorageaddons-0.10.0.jar         
konkrete_forge_1.6.1-2_MC_1.20.jar

**Extra info:**
Issue also appeared while using the mod "Twigs": The twig and the rock items (and possibly more) rendered a brown and gray square around the actual block when placed. I do not have any screenshots of this since I removed the mod before investigating the issue.

If you need any more information just let me know :)

**Comment by Asek3** [comment]
Update to 0.7.0a
