### ISSUE TITLE
[1.16.5] TConstruct molten Fluids turn blue in thier placed form

### ISSUE THREAD

**Issue by MundM2007** [Asek3/Rubidium#574]
**Describe the bug**
All Tconstruct molten fluids are blue if installing rubidium and tconstruct. Like in this screenshot (This is molten iron):
![image](https://github.com/Asek3/Rubidium/assets/85188362/d83da3d7-087f-4bdc-b3e8-6100d1ae8565)

**To Reproduce**
1. Install Rubidium and Tconstruct
2. Start game and open a world
3. place Tconstruct molten fluid
4. See that it's blue

**Expected behavior**
That the color of the fluids would stay the same

**Versions:**
- Rubidium Version: rubidium-0.2.12.jar
- Tconstruct Version: TConstruct-1.16.5-3.3.4.335.jar
- Forge Version: 36.2.39

**Additional context**
This may also affect other game versions.

**Comment by Asek3** [comment]
Fixed in https://github.com/Asek3/Rubidium/commit/266d068792c4cbce8fc3a66b9bb25109a30b1b07#diff-3486df2d697d632a02fa5eaeb85a0590a3a1e89df7c11488eeb9cf8b92d41fbbR361
