### ISSUE TITLE
Holes in the World In Rubidium 1.19.4 

### ISSUE THREAD

**Issue by AFaxMachine2** [Asek3/Rubidium#575]
Random sections of land are not rendering and are appearing transparent in single player worlds and on servers

**Comment by AFaxMachine2** [comment]
> 
The version used is 0.6.4 on 1.19.4

**Comment by Asek3** [comment]
1.19.4 is abandoned, however, there exists jar with fix https://drive.google.com/file/d/1Y2rUojTOgOq2gWL0T2fsgqRGLuzw89Si/view?usp=sharing
