### ISSUE TITLE
[1.20.1] Crash while rendering any model data from @Hostile Neural Networks in JEI or in inventory.

### ISSUE THREAD

**Issue by Gbergz** [Asek3/Rubidium#584]
`("GhostVertexBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter")`

### Versions:
MC: 1.20.1
Forge(not Neo): 47.1.3
Hostile Neural Networks: 5.1.3 | https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks/files/4711380
Placebo: 8.3.5
Rubidium: 0.6.5
JEI: 15.2.0.25
EMI: 1.0.19 (happens without too, just JEI.)

### Crash Reports
**Link with EMI:** https://gist.githubusercontent.com/Gbergz/b74cbe71a550ee87d9971a2db281dfa6/raw/c365dcc299b373197222bf974ac2d5709a3ed3f9/gistfile1.txt
**With just JEI:** https://gist.githubusercontent.com/Gbergz/41dafd9bdd1b28f49c943e8938059e3e/raw/a435640e185ce449eccd0c189b163f0aa0a1c8e0/gistfile1.txt

**Crash Report when right clicking an entity to build a data model:**
https://gist.githubusercontent.com/Gbergz/91d4a26cc9df89753aa53955d89b9ec9/raw/dd0de620d8a3781baf935535fd0aebe70f6ce6b4/gistfile1.txt

### Other info:
Rendering any data module in JEI / EMI from the Hostile Neural Networks results in a crash.

### Other:
Report originally reported here:
`https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/35`

**Comment by aking4125** [comment]
Embeddium has the same issue. This issue was reported to the pixelmon team and they stated [here](https://pixelmonmod.com/tracker.php?p=2&t=20867) that they will not fix it.

https://pixelmonmod.com/tracker.php?p=2&t=20914

Discussed [here](https://github.com/embeddedt/embeddium/issues/9) with embeddedt for some additional details.

**Comment by Asek3** [comment]
Update Rubidium to 0.7.1
