### ISSUE TITLE
[1.20.1]Crash while opening Create's creative tab

### ISSUE THREAD

**Issue by 12345hhh** [Asek3/Rubidium#590]
[debug.log](https://github.com/Asek3/Rubidium/files/12416753/debug.log)
[latest.log](https://github.com/Asek3/Rubidium/files/12416755/latest.log)
[crash-2023-08-23_16.05.58-client.txt](https://github.com/Asek3/Rubidium/files/12416756/crash-2023-08-23_16.05.58-client.txt)
Appears only when two mods are added simultaneously

**Comment by 12345hhh** [comment]
mod version: 0.7.0 and 0.7.0a

**Comment by Andrii-Vovk** [comment]
+1

**Comment by kahd0** [comment]
same here

**Comment by GolfinhoVoador** [comment]
Can't reproduce here

**Comment by xiale2015** [comment]
+1

**Comment by Flintley** [comment]
will this be fixed, or is the issue unknown?
and does it work with older versions of rubidium/create?

**Comment by LadyValishade** [comment]
same issue

**Comment by GolfinhoVoador** [comment]
> will this be fixed, or is the issue unknown? and does it work with older versions of rubidium/create?

pretty sure it works fine with rubidium 0.6.5

**Comment by Flintley** [comment]
> pretty sure it works fine with rubidium 0.6.5

i'll test it out

**Comment by Flintley** [comment]
it works with these rubidium (addon) mods:
<img width="389" alt="image" src="https://github.com/Asek3/Rubidium/assets/111710468/8be3ddc6-910a-455a-a7f1-83b69780dba0">

**Comment by Asek3** [comment]
Update Rubidium to 0.7.1
