### ISSUE TITLE
[1.16.5]Can You Fix Conflict For Use "BetterFoliage"?

### ISSUE THREAD

**Issue by At87668** [Asek3/Rubidium#593]
Minecraft Version : 1.16.5
Forge Version : 36.2.39
Rubidium Version : 0.2.11
BetterFoliage Version : 2.7.1

I want to install "BetterFoliage" mod, but Minecraft is no response.
I looked the logs, found is a problem of "Sodium", but I'm using Rubidium.
I want you can fix conflict for use "BetterFoliage".
Thanks.

**Comment by At87668** [comment]
[Log](https://paste.gg/p/anonymous/660496ee58764c93b22546d389267859)
No crash-reports.

**Comment by Asek3** [comment]
Better Foliage conflict cannot be fixed only on our side, partially, we fixed issue in 0.2.13, but there are still incompatibility
