### ISSUE TITLE
Incompatible with multiple mods

### ISSUE THREAD

**Issue by Mevillius** [Asek3/Rubidium#598]
crashes the game before making it into main menu
to find what mods this crashes with just go to the bytebin, CTRL+F and look for "APP:"

https://bytebin.lucko.me/Pvm9hw2fmk

https://crashy.net/06c6c8e5-a384-4078-b177-d25084685fcd

**Comment by mindforger** [comment]
looks like a combination of a mod displaying a mob or entity in the main menu (can not remember out of the head if there is supposed to be rendered one at this point) in combination with "neat" mod not being able to identify applied enchantments on that rendered entitiy

**Comment by Mevillius** [comment]
> looks like a combination of a mod displaying a mob or entity in the main menu (can not remember out of the head if there is supposed to be rendered one at this point) in combination with "neat" mod not being able to identify applied enchantments on that rendered entitiy

Thank you so much, i've removed the mod causing all of that and now i can play perfectly fine, tbh didnt expect such a quick response so THANK YOU AGAIN!
