### ISSUE TITLE
[1.16.5] Rendering issue with immersive engineering and other child mods

### ISSUE THREAD

**Issue by GekidoLukas** [Asek3/Rubidium#60]
The rendering of multiblock structures is very weird using Oculus and Rubium. Each Block of the structure displays the whole structure
![2022-04-05_17 44 37](https://user-images.githubusercontent.com/59490449/161795287-0cf39bea-3478-4ec9-ad98-954da154e82f.png)
![2022-04-05_17 44 40](https://user-images.githubusercontent.com/59490449/161795301-58331b1f-e69d-4c52-b05a-c091f7dee5bf.png)
.
I hope you will find a fix, because this is kind of game breaking and I love this mod ^^"

**Comment by GekidoLukas** [comment]
Also, the rotation is also always towards north

**Comment by Asek3** [comment]
Rubidium's issue, not Oculus'
