### ISSUE TITLE
(1.19.4/mc1.19.4-0.6.4) holes in world rendering

### ISSUE THREAD

**Issue by ophiocordyceps** [Asek3/Rubidium#602]
literally no idea what the issue is here, but it's definitely a rubidium thing, i tested a few of my mods and these went away when rubidium was removed. F3+a does not solve it.
![2023-09-12_11 57 27](https://github.com/Asek3/Rubidium/assets/87246648/02f85879-76b4-4e59-92ba-1738517e0840)
![2023-09-12_11 59 55](https://github.com/Asek3/Rubidium/assets/87246648/1c29fed4-e6d7-4f17-a49c-777123e9cffe)
![2023-09-12_12 00 07](https://github.com/Asek3/Rubidium/assets/87246648/494c4ab4-2c82-4c46-aa0d-b7aee1496f2b)
![2023-09-12_12 00 16](https://github.com/Asek3/Rubidium/assets/87246648/6515f182-6a12-4344-a391-afe9063cde3e)
![2023-09-12_12 00 39](https://github.com/Asek3/Rubidium/assets/87246648/ce493d7e-6e3f-4be6-84fb-184b5cec5800)
![2023-09-12_12 00 45](https://github.com/Asek3/Rubidium/assets/87246648/98cf1f65-e1cf-4652-ab43-af3bfd06e1ad)
![2023-09-12_12 01 04](https://github.com/Asek3/Rubidium/assets/87246648/bd6e3702-eeb9-4293-970e-5fa4d2365018)
![2023-09-12_12 01 47](https://github.com/Asek3/Rubidium/assets/87246648/ad021019-3ebd-44ba-91fa-8e97cf4b853b)
![2023-09-12_12 02 00](https://github.com/Asek3/Rubidium/assets/87246648/99373bf6-899c-44ba-91ba-43ec4e262a65)

**Comment by Asek3** [comment]
1.19.4 is abandoned
