### ISSUE TITLE
1.19.2 Heavly Modded Minecraft Crashing with Error "1073741819" After Working for 20 Seconds~

### ISSUE THREAD

**Issue by Ashxy-Wolf** [Asek3/Rubidium#606]
I understand Optimization mods and Minecraft dont Generally mix, but what's Geting to me is that it works fine for about twenty seconds before Exiting with "1073741819" I looked it up and it seems to be ether minecraft trying to [accesses a file being copied](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjptMaj262BAxUhMVkFHTH8ANoQFnoECBsQAw&url=https%3A%2F%2Fwww.minitool.com%2Fnews%2Fminecraft-exit-code-1073741819.html%23%3A~%3Atext%3DThe%2520Minecraft%2520exit%2520code%2520often%2Cfile%2520that%2520was%2520being%2520copied.&usg=AOvVaw0WKkm7rezqPBFiWTFARXQn&opi=89978449) or [A driver outdated ](https://gameserrors.com/minecraft-error-code-1073741819/) Any help?

**Comment by Ashxy-Wolf** [comment]
Logs 
[crash-2023-09-15_18.40.48-client.txt](https://github.com/Asek3/Rubidium/files/12629250/crash-2023-09-15_18.40.48-client.txt)

**Comment by Asek3** [comment]
FancyDyes mod issue, report to them
