### ISSUE TITLE
Rubidium crashes when using - Dark Mode Everywhere Mod

### ISSUE THREAD

**Issue by SirTwsted** [Asek3/Rubidium#609]
This is the pastebin crash log.

https://pastebin.com/tgrbKjzL

Minecraft v1.20.1
Forge v47.1.46  and also tested it on Forge v47.1.47
Using latest Java version.

**Comment by Asek3** [comment]
Fixed in 0.7.1

**Comment by SirTwsted** [comment]
When pressing update, thinking a newer version after v7.1 might have been released.
The mod reverts back to 7.0a when pressing the update button in CurseForge.

Here is the picture showing the mod saying it has an update,
even though its the latest version.  And when you press it to update it, it reverts back to 7.0a.
Thought you should know  🤓👍

![Rubidium keeps reverting back to 7 0a when updating](https://github.com/Asek3/Rubidium/assets/15247713/6395f3fc-ecc6-4e46-bd33-a6cd319417a1)

**Comment by SirTwsted** [comment]
Hey @Asek3 

I also wanted to point out.  At very specific times (in game time)  
During Sun Rise and Sunsets
Sun Rise @ 0.00 to 0.59 
and
Sunset @ 9.00 to 10.00

I get this every single time.  I tried on BSL, Sildur's and Complementary Shader's,  to make sure it was not the shaders themselves.


![2023-09-25_14 27 54](https://github.com/Asek3/Rubidium/assets/15247713/43a87f2c-15aa-4a04-89bb-5205afe20208)


![2023-09-25_14 32 46](https://github.com/Asek3/Rubidium/assets/15247713/28a580c5-8db0-46a8-b88c-e39d67000da9)


![2023-09-25_14 33 25](https://github.com/Asek3/Rubidium/assets/15247713/8a05dcb8-de14-44b7-abf5-10bba609b379)


![2023-09-25_14 33 34](https://github.com/Asek3/Rubidium/assets/15247713/e2ff3a33-e061-480b-935c-f4c3201c1956)



Sorry.   😢  I don't mean to bring you more headaches than you have.  😳

.

**Comment by SirTwsted** [comment]
And these are the sunrise ones.   

![2023-09-25_14 16 39](https://github.com/Asek3/Rubidium/assets/15247713/eeec4a62-867c-4798-aa2f-d58d08ddddf2)


![2023-09-25_14 16 50](https://github.com/Asek3/Rubidium/assets/15247713/c7f11c0d-a0f6-4019-abff-c1c9df566e57)


![2023-09-25_14 17 06](https://github.com/Asek3/Rubidium/assets/15247713/37a17f35-539b-41a5-a38d-02b6a3895957)

**Comment by SirTwsted** [comment]
**During the day and middle of the night it works perfect.  As you can see.**



![2023-09-25_14 23 37](https://github.com/Asek3/Rubidium/assets/15247713/017f92b9-63ed-440c-aeea-2d7e3ab10b72)


![2023-09-25_14 12 27](https://github.com/Asek3/Rubidium/assets/15247713/3b2202e2-98c4-4f93-8a1f-6a81bdf98c72)
