### ISSUE TITLE
Incorrect rendering of dynamic trees.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Rubidium#61]
Oculus makes dynamic trees render incorrectly.

With Oculus:
![2022-04-05_13 12 53](https://user-images.githubusercontent.com/47157784/161841154-4d851f2e-1555-43c9-b96e-0bfeb0e91ac7.png)

Without Oculus:
![image](https://user-images.githubusercontent.com/47157784/161841279-86608022-c48a-4317-a50b-d34b4dab98a9.png)

Oculus version: 1.16.5-1.2.2

**Comment by Asek3** [comment]
Probably Rubidium related issue, not Oculus'
