### ISSUE TITLE
Rubidium crashes when using JEI.

### ISSUE THREAD

**Issue by SirTwsted** [Asek3/Rubidium#611]
I get crashes when using Rubidium and opening JEI.
As soon as I click on next page and previous page in JEI, the game immediately crashes.

The crash splash screen says:

`The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null`

Here is the crash report:
https://pastebin.com/G4FhbfJd

CurseForge v0.234.3.1
Minecraft v1.20.1
Forge v47.1.43
Rubidium v0.7.0a

🤷‍♀️

**Comment by Asek3** [comment]
Update Rubidium to 0.7.1

**Comment by SirTwsted** [comment]
Works like a charm thank you.  🤓👍
