### ISSUE TITLE
Rubidium v0.6.5 with Oculus v1.6.4  Crashes modded minecraft v1.20.1

### ISSUE THREAD

**Issue by SirTwsted** [Asek3/Rubidium#616]
I was told to try to use Rubidium v0.6.5 to see if I have any problems with crashes.
And I still do.

Rubidium v0.6.5 with Oculus v1.6.4  Crashes modded minecraft v1.20.1
Using Complementary Unbound Shaders Pack.

Minecraft v1.20.1
Forge v47.1.46
Rubidium v0.6.5
Oculus v1.6.4

Used on Curseforge Launcher.

Here is the Splash Screen Error Code.

`The game crashed whilst rendering overlay
Error: java.lang.ClassCastException: class net.roguelogix.quartz.internal.common.InternalMesh$Builder$BufferBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (net.roguelogix.quartz.internal.common.InternalMesh$Builder$BufferBuilder is in module quartz@0.2.0-alpha of loader 'TRANSFORMER' @67292fc7; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @67292fc7)`

This is the crash report.
https://pastebin.com/ghDEFXLh

🤷‍♀️

**Comment by Asek3** [comment]
Try to update to 0.7.1, anyway it should be fixed on their side
