### ISSUE TITLE
[1.20.1] Client crash with "Snow! Real Magic!"

### ISSUE THREAD

**Issue by mosharky** [Asek3/Rubidium#623]
[This mod](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) has some mixin conflict with Rubidium on 0.7.1

crash report: https://gist.github.com/mosharky/dd5271702bc4da41fd51ff537ce8dbc9

**Comment by Asek3** [comment]
Can be fixed only on their side

**Comment by mosharky** [comment]
thanks for the quick reply, I reported it there now
