### ISSUE TITLE
Rubidium causes Causes connected texture mod packs to not function correctly

### ISSUE THREAD

**Issue by thelegitdolt** [Asek3/Rubidium#64]

**Comment by HydrogenC** [comment]
Same problem.

**Comment by Asek3** [comment]
wdym

**Comment by DommyDCoder** [comment]
I also have this issue. I was using rubidium with the create mod, and the blocks that were supposed to have connected textures just appeared to be not so connected.. for example: the pillar block variants

**Comment by aethaerya** [comment]
Mods and RPs that rely on ConnectedTexturesMod get weird

Enderium glass from Thermal series
![image](https://user-images.githubusercontent.com/28931355/170965775-9db60f11-533f-4910-9221-3cf51c9ec62f.png)

**Comment by Vapaman** [comment]
Can confirm this is happening still. A workaround for now is to reload the chunks with F3+A after placing the blocks.

**Comment by Phantom914** [comment]
Yeah it happens with Chisel, and certain other mods still on 1.16. reChiseled works fine though weirdly. F3+A doesn't do anything, but going to another dimension and coming back does fix it. If you start replacing those blocks however after coming back then it gets weirder with how it renders

**Comment by Phantom914** [comment]
![2022-08-26_13 28 07](https://user-images.githubusercontent.com/81133126/186960057-a7460ac5-7877-4948-8f64-13b669c4c745.png)

**Comment by Phantom914** [comment]
![2022-08-26_13 37 37](https://user-images.githubusercontent.com/81133126/186961596-6734481d-f77c-454d-9a13-a917b3ffb43b.png)

**Comment by DevStark22** [comment]
same here

**Comment by JNCHGTR** [comment]
Just wanted to say this is still an issue.

MC 1.16.5 - Forge 36.2.39 and 36.2.34

**Comment by JNCHGTR** [comment]
![image](https://user-images.githubusercontent.com/96136588/227070725-2d058e89-bacd-4c4a-8c44-5a360deeb016.png)

**Comment by Asek3** [comment]
Fixed in Dev
