### ISSUE TITLE
Incompatibility with Immersive Portals.

### ISSUE THREAD

**Issue by naughtius-maximus-8492** [Asek3/Rubidium#66]
Rubidium appears to be incompatible with Immersive Portals, no blocks render at all.

Versions:

Forge - 36.2.33
Rubidium - 0.2.5
Immersive Portals (for Forge) - 0.17

Steps to reproduce:

1) Install the above mods onto client
2) Load up a single player world with default settings
3) Issue present as seen below

![Screenshot 2022-04-06 232339](https://user-images.githubusercontent.com/52298445/162082553-2d6d4cf5-7e45-4af6-94f3-7f4054ce3f78.png)

Logs:

[latest - Copy.log](https://github.com/Asek3/Rubidium/files/8433286/latest.-.Copy.log)

Other notes:

Game otherwise "runs" fine, I observed no crashes.

**Comment by nc5432** [comment]
I just came across this issue as well. It is a very strange bug. It has the same issue if you join a server, the blocks are still invisible, but the server runs fine.

**Comment by Asek3** [comment]
Can't be fixed on our side. As I know soon there will be 1.18 and 1.19 Immersive Portal versions for Forge, which has compatibility with Rubidium.

**Comment by border999** [comment]
Update on this. Just tried opening a nether portal in 1.18.2 with immersive-portals-1.4.13 and Rubidium mc1.18.2-0.5.5. No dice, crash.
[crash-2023-03-24_21.33.46-client.txt](https://github.com/Asek3/Rubidium/files/11067688/crash-2023-03-24_21.33.46-client.txt)
