### ISSUE TITLE
Crash when joining server in Enigmatica 6

### ISSUE THREAD

**Issue by themaster402** [Asek3/Rubidium#68]
[crash-2022-04-06_17.50.23-client.txt](https://github.com/Asek3/Rubidium/files/8438849/crash-2022-04-06_17.50.23-client.txt)
On Enigmatica 6: Expert, with BetterEnd Reforked and Rubidium.

**Comment by StarskyXIII** [comment]
Same issue, but have the different crash report.
[crash-2022-04-08_16.26.07-client.txt](https://github.com/Asek3/Rubidium/files/8450090/crash-2022-04-08_16.26.07-client.txt)

**Comment by themaster402** [comment]
Manually fixing a badly generated options .json as I described in #67 seems to fix this.

**Comment by themaster402** [comment]
Fixed in the latest release.
