### ISSUE TITLE
[1.16.5] Incompatibility with CTM/Chisel

### ISSUE THREAD

**Issue by Quickburst** [Asek3/Rubidium#69]
I loaded up a world with the new version and odd rendering glitched started appearing. When I broke a block in a chunk, it would fix the errors in that chunk. That is, until it crashed
[crash-2022-04-07_12.07.06-client.txt](https://github.com/Asek3/Rubidium/files/8439105/crash-2022-04-07_12.07.06-client.txt)
.

**Comment by Quickburst** [comment]
Another crash when teleporting to an unloaded chunk.
[crash-2022-04-07_12.18.42-client.txt](https://github.com/Asek3/Rubidium/files/8439137/crash-2022-04-07_12.18.42-client.txt)

**Comment by HydrogenC** [comment]
This also happens to me when placing a glass block with CTM installed.

**Comment by HydrogenC** [comment]
> Another crash when teleporting to an unloaded chunk. [crash-2022-04-07_12.18.42-client.txt](https://github.com/Asek3/Rubidium/files/8439137/crash-2022-04-07_12.18.42-client.txt)

The same crash also happens to me when placing a glass block with CTM installed.

**Comment by HydrogenC** [comment]
@Quickburst I've made some tests around this and confirmed that this crash is caused by CTM. you can remove it for a temporary fix, as CTM actually doesn't function (see #22).

**Comment by Quickburst** [comment]
@HydrogenC  Deleting CTM isn't really an option as it is required by Chisel.

**Comment by Quickburst** [comment]
And adding mixin.features.chunk_rendering=false crashes the game upon joining a world.

**Comment by HydrogenC** [comment]
> And adding mixin.features.chunk_rendering=false crashes the game upon joining a world.

Yeah, I also encountered that.

**Comment by Quickburst** [comment]
I can't really play Minecraft without this so it'd be really nice if this issue was addressed.

**Comment by Nevrai** [comment]
This still occurs in 0.5.3a of Rubidium in 1.18.2. Was this not fixed?

**Comment by DrymarchonShaun** [comment]
Still occurring in 0.6.2a, 1.19.2 (All The Mods 8)
