### ISSUE TITLE
1.18.2 не отображаются провода и другие некоторые части мультиблоков + разрыв текстур

### ISSUE THREAD

**Issue by XionioXMaster** [Asek3/Rubidium#71]
![image](https://user-images.githubusercontent.com/86433158/162309231-4b82c0b3-fe33-4423-b82b-f06aabf620b3.png)

пробовал покавырятся в настройках, но чёт не к чиму не пришел

на сере та же хрень

например в штуковине справа должны быть лезвия

Мод иммерсивинженерик

Помимо этого в моде Minecolonies разрывает иконки уведомлений в жителей на всю карту
![image](https://user-images.githubusercontent.com/86433158/162309827-a7013947-a4f2-4d4d-9514-da2995fbe808.png)

**Comment by Asek3** [comment]
Probably Oculus' issue

**Comment by XionioXMaster** [comment]
> Probably Oculus' issue

this does not fix immersive rendering
