### ISSUE TITLE
1.16.5 crash with Ender Storage 1.8.+

### ISSUE THREAD

**Issue by mvadovszki** [Asek3/Rubidium#72]
minecraft: 1.16.5
rubidium: 0.2.5
EnderStorage: 2.8.0.168 (same as used in latest version of ATM6 & Enigmatica6)

https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8

[crash-2022-04-07_17.47.20-client.txt](https://github.com/Asek3/Rubidium/files/8447479/crash-2022-04-07_17.47.20-client.txt)

To reproduce:
use creative mode or JEI to search for the added ender chest, which triggers the crash.

**Comment by Asek3** [comment]
Should be fixed in last releases
