### ISSUE TITLE
Trojan Virus 

### ISSUE THREAD

**Issue by Daedalos77** [Asek3/Rubidium#724]
On my laptop the security programm just detected the file rubidium-mc1.20.1-0.7.1.jar as a trojan virus. 
If anyone else also got this, it might really be a virus, but I'm no expert I just wanted to report this in case it could be useful

**Comment by Alicev3** [comment]
desktop with bitdefender, same issue

**Comment by Asek3** [comment]
Windows Defender sometimes doesn't respond correctly to mods. Rubidium is compiled from sources in a repository, from which you can make sure that there is no virus in it
