### ISSUE TITLE
Dynamic Tree Roots Incorrectly Rendered.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Rubidium#75]
Rubidium 1.16.5-0.2.5
![2022-04-08_20 02 28](https://user-images.githubusercontent.com/47157784/162554058-9e4fd0de-1a29-46f7-99af-f9a1cfb2c6d9.png)

**Comment by Romoslayer** [comment]
Other issues with Dynamic Trees and Rubidium.
Video: https://www.youtube.com/watch?v=XFUXMGt3-oY
https://spark.lucko.me/75fpTCR5nj (used spark to find the issue, link no longer works)
![unknown](https://user-images.githubusercontent.com/47157784/167198256-5de33cee-7c9d-4eca-a316-4e3cd40884ff.png)
![unknown1](https://user-images.githubusercontent.com/47157784/167198327-070139de-4680-4b60-abab-931b9d9724b5.png)

**Comment by Asek3** [comment]
Fixed on latest versions
