### ISSUE TITLE
Cacti from Dynamic Trees + Incorrectly Rendered.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Rubidium#77]
Similar issue to what happened to dynamic trees.
Rubidium 1.16.5-0.2.5
![2022-04-10_20 29 24](https://user-images.githubusercontent.com/47157784/162660893-71a93bf5-7bba-4da4-925e-4ca09fa65157.png)

**Comment by Asek3** [comment]
dude wtf u created 3 issues related to one problem #75
