### ISSUE TITLE
Game randomly crash (java.lang.ArrayIndexOutOfBoundsException: null)

### ISSUE THREAD

**Issue by domanhthang2110** [Asek3/Rubidium#78]
This is the crash report, the game just crash randomly and I don't know if it's the mod or others, maybe you can figure why this is happening so I can filter out the conflicting mod if it's the case.
`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/11/22, 3:32 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: null (sometime it's java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16385)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%23148!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 2 total; [LocalPlayer['YukamiNeesan'/363, l='ClientLevel', x=-375.59, y=72.00, z=449.06], RemotePlayer['Astolfo'/273806, l='ClientLevel', x=-310.43, y=39.00, z=585.58]]
	Chunk stats: 4096, 1027
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,63,112), Section: (at 0,15,0 in 3,3,7; chunk contains blocks 48,-64,112 to 63,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 114856 game time, 124501 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%23148!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:683) ~[client-1.18.1-20211210.034407-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23148!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, VanillaTweaks_r839431.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2342842456 bytes (2234 MiB) / 4261412864 bytes (4064 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23297.24
	Virtual memory used (MB): 21232.21
	Swap memory total (MB): 7060.59
	Swap memory used (MB): 415.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.1-forge-39.1.0
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 1360x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/VanillaTweaks_r839431.zip
	Current Language: English (US)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Server Running: true
	Player Count: 2 / 8; [ServerPlayer['YukamiNeesan'/363, l='ServerLevel[vit]', x=-375.59, y=72.00, z=449.06], ServerPlayer['Astolfo'/273806, l='ServerLevel[vit]', x=-310.43, y=39.00, z=584.50]]
	Data Packs: vanilla, mod:treechop (incompatible), mod:skyvillages (incompatible), mod:kiwi, mod:stylisheffects, mod:betterdungeons, mod:peepomod, mod:blue_skies (incompatible), mod:rootsclassic, mod:no_null_processors, mod:bigbrain, mod:configmenusforge, mod:easymagic, mod:jei, mod:conjurer_illager (incompatible), mod:libraryferret, mod:rubidium, mod:bossmusicmod, mod:waystones, mod:villagernames, mod:placebo (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:mcwifipnp (incompatible), mod:configured (incompatible), mod:yungsapi, mod:stoneholm (incompatible), mod:feature_nbt_deadlock_be_gone, mod:criticalib, mod:farsightedmobs (incompatible), mod:guardvillagers (incompatible), mod:starlight, mod:catalogue (incompatible), mod:balm (incompatible), mod:jeresources, mod:dragonfight (incompatible), mod:cloth_config (incompatible), mod:sound_physics_remastered, mod:dragonmounts, mod:structure_gel, mod:equipmentcompare, mod:corpse, mod:tconstruct (incompatible), mod:ba_bt (incompatible), mod:swingthroughgrass, mod:ambientsounds (incompatible), mod:companion, mod:toolstats, mod:jade, mod:forge, mod:endrem (incompatible), mod:shouldersurfing, mod:improvedmounthud, mod:creativecore, mod:chunky, mod:deathfinder, mod:dungeons_enhanced, mod:goprone (incompatible), mod:goblinsanddungeons, mod:iceberg, mod:flywheel, mod:create, mod:curios, mod:cataclysm (incompatible), mod:patchouli, mod:mutil (incompatible), mod:mantle (incompatible), mod:lucent, mod:collective, mod:spyglass_improvements, mod:autoreglib (incompatible), mod:oreexcavation, mod:yungsextras, mod:entityculling (incompatible), mod:backpacked (incompatible), mod:effective_fg, mod:overweight_farming, mod:betterstrongholds, mod:damageindicator, mod:fastfurnace (incompatible), mod:inventoryprofilesnext (incompatible), mod:architectury (incompatible), mod:biomemakeover (incompatible), mod:appleskin, mod:ferritecore (incompatible), mod:aiimprovements, mod:puzzleslib, mod:invmove_compat, mod:invmove, mod:enhancedcelestials (incompatible), mod:easyshulkerboxes, mod:valhelsia_core, mod:valhelsia_structures, mod:geckolib3 (incompatible), mod:bettermodsbutton, mod:betteradvancements, mod:notenoughanimations (incompatible)
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		TreeChop-1.18.1-0.15.7.jar                        |HT's TreeChop                 |treechop                      |0.15.7              |DONE      |Manifest: NOSIGNATURE
		SkyVillages+1.0.1+1.18.jar                        |Sky Villages                  |skyvillages                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.18-forge-5.2.5.jar                         |Kiwi                          |kiwi                          |5.2.5               |DONE      |Manifest: NOSIGNATURE
		StylishEffects-v3.0.2-1.18.1-Forge.jar            |Stylish Effects               |stylisheffects                |3.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterDungeons-Forge-1.18.1-1.0.1.jar             |YUNG's Better Dungeons        |betterdungeons                |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Alex's+Mobs+Music+Mod.jar                         |Alex's Mobs Mod Music         |peepomod                      |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.18.1-1.3.4.jar                       |Blue Skies                    |blue_skies                    |1.3.4               |DONE      |Manifest: NOSIGNATURE
		RootsClassic-1.18.1-1.1.19.jar                    |Roots Classic                 |rootsclassic                  |1.18.1-1.1.19       |DONE      |Manifest: NOSIGNATURE
		no_null_processors_forge-2.0.2+1.18.1.jar         |No Null Processors            |no_null_processors            |2.0.2+1.18.1        |DONE      |Manifest: NOSIGNATURE
		bigbrain-1.4.1.jar                                |Big Brain                     |bigbrain                      |1.4.1               |DONE      |Manifest: NOSIGNATURE
		ConfigMenusForge-v3.1.0-1.18.1-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		EasyMagic-v3.2.1-1.18.1-Forge.jar                 |Easy Magic                    |easymagic                     |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.4.1.112.jar                          |Just Enough Items             |jei                           |9.4.1.112           |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.18.1-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.1-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.0.jar                                |Rubidium                      |rubidium                      |0.5.0               |DONE      |Manifest: NOSIGNATURE
		Boss+Music+Mod.jar                                |Boss Music Mod                |bossmusicmod                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.4.jar                  |Waystones                     |waystones                     |9.0.4               |DONE      |Manifest: NOSIGNATURE
		villagernames_1.18.1-3.5.jar                      |Villager Names                |villagernames                 |3.5                 |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.1.1.jar                          |Placebo                       |placebo                       |6.1.1               |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.10-1.18.jar                          |Citadel                       |citadel                       |1.10.10             |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		mcwifipnp-1.5.4-1.18.2-forge.jar                  |LAN World Plug-n-Play         |mcwifipnp                     |1.5.4               |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.1-Forge-26.jar                      |YUNG's API                    |yungsapi                      |1.18.1-Forge-26     |DONE      |Manifest: NOSIGNATURE
		stoneholm-1.4.1.jar                               |Stoneholm                     |stoneholm                     |1.4.1               |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |1.0.0+1.18.1        |DONE      |Manifest: NOSIGNATURE
		criticalib-forge-1.18.1-1.0.0.jar                 |CriticaLib                    |criticalib                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		farsightedmobs-forge-1.1-1.18.jar                 |Farsighted Mobs               |farsightedmobs                |1.1                 |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.1.4.0.jar                     |Guard Villagers               |guardvillagers                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.1+forge.fef9eb9.jar                 |Starlight                     |starlight                     |1.0.0+forge.b1f6a10 |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.0-1.18.1.jar                        |Catalogue                     |catalogue                     |1.6.0               |DONE      |Manifest: NOSIGNATURE
		balm-2.4.3+0.jar                                  |Balm                          |balm                          |2.4.3+0             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |DONE      |Manifest: NOSIGNATURE
		dragonfight-1.18.1-1.9.jar                        |dragonfight mod               |dragonfight                   |1.18.1-1.9          |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.1-1.0.4.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		dragonmounts-1.18.1-1.1.jar                       |Dragon Mounts: Legacy         |dragonmounts                  |1.18.1-1.1          |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.1-2.1.3.jar                    |Structure Gel API             |structure_gel                 |2.1.3               |DONE      |Manifest: NOSIGNATURE
		EquipmentCompare-1.18.1-1.2.10.jar                |Equipment Compare             |equipmentcompare              |1.2.10              |DONE      |Manifest: NOSIGNATURE
		corpse-1.18.1-1.0.4.jar                           |Corpse                        |corpse                        |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.1-3.4.2.60.jar                    |Tinkers' Construct            |tconstruct                    |3.4.2.60            |DONE      |Manifest: NOSIGNATURE
		BrassAmberBattleTowers-1.18.1-2.0.2.jar           |Brass Amber BattleTowers      |ba_bt                         |1.18.1-2.0.2        |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.0-pre02_mc1.18.1.jar           |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		Companion-1.18-forge-1.1.2.jar                    |Companion                     |companion                     |1.1.2               |DONE      |Manifest: NOSIGNATURE
		ToolStats-Forge-1.18.1-8.0.5.jar                  |ToolStats                     |toolstats                     |8.0.5               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Jade-1.18.1-4.4.1.jar                             |Jade                          |jade                          |4.4.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.1.0-universal.jar                 |Forge                         |forge                         |39.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		endrem_forge-5.0.1-R-1.18.1.jar                   |End Remastered                |endrem                        |5.0-R-1.18.1        |DONE      |Manifest: NOSIGNATURE
		ShoulderSurfing-1.18-2.2.2.jar                    |Shoulder Surfing              |shouldersurfing               |1.18-2.2.2          |DONE      |Manifest: NOSIGNATURE
		ImprovedMountHUD-v3.0.1-1.18.1-Forge.jar          |Improved Mount HUD            |improvedmounthud              |3.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		CreativeCore_v2.5.0_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.5.0               |DONE      |Manifest: NOSIGNATURE
		Chunky-1.2.164.jar                                |Chunky                        |chunky                        |1.2.164             |DONE      |Manifest: NOSIGNATURE
		DeathFinder-v3.1.0b1-1.18.1-Forge.jar             |Death Finder                  |deathfinder                   |3.1.0b1             |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		dungeons_enhanced-1.18.1-3.0.jar                  |Dungeons Enhanced             |dungeons_enhanced             |3.0                 |DONE      |Manifest: NOSIGNATURE
		goprone-1.18.2-1.7.0.jar                          |GoProne                       |goprone                       |1.18.2-1.7.0        |DONE      |Manifest: NOSIGNATURE
		Goblins_Dungeons_1.0.7.jar                        |Goblins & Dungeons            |goblinsanddungeons            |1.0.7               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.0-mc1.18.2.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.0               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.40.jar                         |Iceberg                       |iceberg                       |1.0.40              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.1.jar                     |Flywheel                      |flywheel                      |1.18-0.6.1.63       |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4f.jar                         |Create                        |create                        |0.4f                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.1.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.1      |DONE      |Manifest: NOSIGNATURE
		Cataclysm-0.16.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.4.0.jar                            |mutil                         |mutil                         |4.4.0               |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.1-1.8.37.jar                          |Mantle                        |mantle                        |1.8.37              |DONE      |Manifest: NOSIGNATURE
		lucent-1.18.1-1.2.0.jar                           |Lucent                        |lucent                        |1.2.0               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-4.7.jar                         |Collective                    |collective                    |4.7                 |DONE      |Manifest: NOSIGNATURE
		spyglass_improvements-1.1+mc1.18.1+forge.jar      |Spyglass Improvements         |spyglass_improvements         |1.1+mc1.18.1        |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.160.jar                        |OreExcavation                 |oreexcavation                 |1.10.160            |DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.18.1-1.0.jar                  |YUNG's Extras                 |yungsextras                   |1.18.1-1.0          |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-mc1.18-1.5.0.jar              |EntityCulling                 |entityculling                 |1.5.0               |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.2-1.18.1.jar                       |Backpacked                    |backpacked                    |2.1.2               |DONE      |Manifest: NOSIGNATURE
		effective_for_forge-1.001.jar                     |Effective (Forge)             |effective_fg                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		overweightfarming-1.18.1-1.0.1-forge.jar          |Overweight Farming            |overweight_farming            |1.18.1-1.0.1-forge  |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-Forge-1.18.1-1.0.1.jar          |YUNG's Better Strongholds     |betterstrongholds             |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		damage-indicator-forge-1.18.1-1.0.0.jar           |Damage Indicator              |damageindicator               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.18.1-6.0.2.jar                      |FastFurnace                   |fastfurnace                   |6.0.2               |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.18-1.3.5.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.3.5               |DONE      |Manifest: NOSIGNATURE
		architectury-3.7.42.jar                           |Architectury                  |architectury                  |3.7.42              |DONE      |Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.18.1-1.4.8.jar              |Biome Makeover                |biomemakeover                 |1.18.1-1.4.8        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.1.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.2               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		AI-Improvements-1.18-0.4.0.jar                    |AI-Improvements               |aiimprovements                |0.4.0               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.2.1-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		InvMoveCompats-1.18-0.1.0-Forge.jar               |InvMove Compat                |invmove_compat                |0.1.0               |DONE      |Manifest: NOSIGNATURE
		InvMove-1.18-0.6.1-Forge.jar                      |InvMove                       |invmove                       |0.6.1               |DONE      |Manifest: NOSIGNATURE
		enhancedcelestials-2.0.9-1.18.jar                 |Enhanced Celestials           |enhancedcelestials            |2.0.9               |DONE      |Manifest: NOSIGNATURE
		EasyShulkerBoxes-v3.0.0-1.18.1-Forge.jar          |Easy Shulker Boxes            |easyshulkerboxes              |3.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		valhelsia_core-1.18.1-0.3.2.jar                   |Valhelsia Core                |valhelsia_core                |1.18.1-0.3.2        |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.18.1-0.1.1.jar             |Valhelsia Structures          |valhelsia_structures          |1.18.1-0.1.1        |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |DONE      |Manifest: NOSIGNATURE
		BetterModsButton-v3.1.0-1.18.1-Forge.jar          |Better Mods Button            |bettermodsbutton              |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterAdvancements-1.18.1-0.1.2.122.jar           |Better Advancements           |betteradvancements            |0.1.2.122           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 8c9735ed-dee4-404c-9ddd-3918ff9fb810
	Flywheel Backend: GL33 Instanced Arrays
	FML: 39.1
	Forge: net.minecraftforge:39.1.0
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data`

**Comment by Asek3** [comment]
1.18.1 has no more Support
