### ISSUE TITLE
Issues with Create Mod

### ISSUE THREAD

**Issue by Atlantispy** [Asek3/Rubidium#8]
- [x] Difficulty rendering the entities such as shafts, cogwheels, flywheels, waterwheels.
- [x] Lack of connected textures, most notably on their pillars, but other blocks too.

**Comment by freopt** [comment]
all the tile entities render fine for me but connected textures are broken

**Comment by Atlantispy** [comment]
Perhaps it's only tile entities already placed in the world?

**Comment by Asek3** [comment]
Send some examples plz

**Comment by Atlantispy** [comment]
![2022-01-31_21 45 32](https://user-images.githubusercontent.com/8345523/151883225-a903dba4-08f0-4f01-8bf4-949f799fade5.png)
![2022-01-31_21 43 35](https://user-images.githubusercontent.com/8345523/151883230-fcaea7b7-ba25-4c11-881c-761cdee787b3.png)

**Comment by mosharky** [comment]
Connected textures needed the Indium mod back on Fabric, so I'm not sure if we'd need the same thing in this case

**Comment by Fnige** [comment]
> Connected textures needed the Indium mod back on Fabric, so I'm not sure if we'd need the same thing in this case

iirc thats because it needed to make use of the fabric api. Which i dont think is used on the forge version

**Comment by ruiluth** [comment]
Never mind, this is an issue with Oculus, not Rubidium. Rubidium works with Create now. Both gears and connected textures.

**Comment by jngeist** [comment]
I'm having this same issue using Rubidium 0.2.6, but no Oculus. I thought it might be Flywheel, but that doesn't seem to have any effect. Also, vanilla chests don't render, which is why I thought it might possibly be a Flywheel issue. Happy to give more information; I'm not entirely sure what other mods I should be looking at for interactions.

**Comment by Asek3** [comment]
Ok so all tasks are done
