### ISSUE TITLE
Dynamic Trees Bug.

### ISSUE THREAD

**Issue by Romoslayer** [Asek3/Rubidium#80]
Rubidium 1.16.5-0.2.5

Video:
https://www.youtube.com/watch?v=JhyL5WllZyU&ab_channel=Romoslayer2.0

**Comment by Asek3** [comment]
dude wtf u created 3 issues related to one problem #75

**Comment by Romoslayer** [comment]
This is a different bug #75 is just the roots being rendered incorrectly, this is a graphical glitch caused when you break a tree.
