### ISSUE TITLE
Game crashes on worldloading

### ISSUE THREAD

**Issue by ToastiMan** [Asek3/Rubidium#82]
Can't join a single or multiplayer game. Tried with Forge Versions 40.0.42 and 40.0.45. 

Everything worked fine until the point where i upgraded from 0.5.1a to 0.5.2

[crash-2022-04-12_15.10.14-client.txt](https://github.com/Asek3/Rubidium/files/8473156/crash-2022-04-12_15.10.14-client.txt)
[crash-2022-04-12_15.06.11-client.txt](https://github.com/Asek3/Rubidium/files/8473157/crash-2022-04-12_15.06.11-client.txt)
.

**Comment by Asek3** [comment]
Update Oculus and Rubidium
