### ISSUE TITLE
0.2.6 (MC 1.16.5) crashes when loading into world. (Still happening)

### ISSUE THREAD

**Issue by archieonic** [Asek3/Rubidium#83]
Up to 0.2.3, Rubidium was working fine. Upgraded to 0.2.5 to enjoy those Create/IE fixes but it crashes upon loading the world
[crash-2022-04-12_11.22.07-client.txt](https://github.com/Asek3/Rubidium/files/8474499/crash-2022-04-12_11.22.07-client.txt)

**Comment by archieonic** [comment]
Update: 0.2.6 still crashes. New crash log attached
[crash-2022-04-28_23.08.35-client.txt](https://github.com/Asek3/Rubidium/files/8587871/crash-2022-04-28_23.08.35-client.txt)
.

**Comment by jusjudge** [comment]
I am getting a similar crash.
I am not completely sure why. My chunks are also not loading properly.
Here is my crash report:
https://crashy.net/yg5Crv4P8PMAxdk9QnGb?raw

**Comment by callum641** [comment]
I am getting the exact same crash as @archieonic. Using 0.2.6 of Rubidium.
Modpack: Ragnamod 6
Crash Log:
[crash-2022-04-30_11.37.53-client.txt](https://github.com/Asek3/Rubidium/files/8605186/crash-2022-04-30_11.37.53-client.txt)

**Comment by archieonic** [comment]
Resolved. Modpack was using incompatible version of BetterEnd. Switching to the forked version fixed the crash.

**Comment by jusjudge** [comment]
@archieonic I cant seem to find the forked version. Mind sending me the link?
