### ISSUE TITLE
Crash on world load with BYG

### ISSUE THREAD

**Issue by brisingraerowing** [Asek3/Rubidium#87]
[Crash Log](https://gist.github.com/brisingraerowing/b005bb9ebc806924f99050f221af0ed6)

**Comment by Asek3** [comment]
Issue related to CaveBiomeApi. Not BYG

**Comment by brisingraerowing** [comment]
Apparently the CF app will install Magnesium when Magnesium / Rubidium Extras is installed even though it's not listed as a dependency. Removing it fixed the crash.
