### ISSUE TITLE
[Suggestion] Can there be an Indium Forge port?

### ISSUE THREAD

**Issue by MemeLord32** [Asek3/Rubidium#88]
Indium is what makes CTM work on Fabric Sodium. Just wondering if you could make an Indium Forge Port.

**Comment by SweepSwap** [comment]
indium is meant to give sodium the support for the fabric rendering api, and forge doesn't use the fabric rendering api. How would that work?

**Comment by MemeLord32** [comment]
Hmmmmm.... I didn't really think of that. What would make CTM works with Rubidium that doesn't mess up the liquids (Adding 'mixin.features.chunk_rendering=false' to the config allows for CTM to work with Rubidium, but the liquids become a tad bit wonky)?

**Comment by Asek3** [comment]
That's a stupid idea to port thing that adds Fabric Rendering API support for Forge
