### ISSUE TITLE
[1.18.2] Crashes when mining and using waystones

### ISSUE THREAD

**Issue by ffuentesm** [Asek3/Rubidium#93]
![image](https://user-images.githubusercontent.com/44974827/163916707-0597a9f5-045d-4abd-8406-192e96171866.png)
Rubidium 0.5.2a
Log: https://crashy.net/BhI9NM8HlmAPyxeeFRXU
Cause of crash: ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 32769

**Comment by Asek3** [comment]
Update to 0.5.4
