### ISSUE TITLE
[1.16.5] Crashes when rendering some items with Oculus

### ISSUE THREAD

**Issue by PuraNura** [Asek3/Rubidium#94]
When rendering Timer Gate（ProjectRed）,Minecraft is Crash. For example, when open CreativeTab.
I set TImer Gate Without Rubidium&Oculus, and enable these, Game is crashed in loading.
When, Disable Oculus, Game isnt crash, but some parts of Timer Gate are invisible.

Crasy ↓
https://crashy.net/KhN4LI1PGlq3BEHz8VFa

**Comment by Asek3** [comment]
Should be fixed in last releases
