### ISSUE TITLE
[1.16.5] Crash when entering certain areas of world/ loading into world

### ISSUE THREAD

**Issue by KaizerDC** [Asek3/Rubidium#96]
Modpack is Enigmatica 6 Expert,
No Roadrunner or Optifine
BetterEnd Reforked installed
Tested with flywheel enabled and disabled
Exact same/ similar crash using magnesium and calcium
Crash still occurs on a fresh install

Crash Log with Rubidium
[crash-2022-04-21_21.58.25-client.txt](https://github.com/Asek3/Rubidium/files/8533301/crash-2022-04-21_21.58.25-client.txt)

Crash Log with Magnesium
[crash-2022-04-21_15.07.24-client.txt](https://github.com/Asek3/Rubidium/files/8533312/crash-2022-04-21_15.07.24-client.txt)

**Comment by Asek3** [comment]
Fixed in 341dd61680f7a2dd9307dad2790fb80334204093
Update Rubidium
